// frontend/src/libraries/sg-ds-library/components/AudioBlock.tsx
import { useEffect, useState, type CSSProperties, type HTMLAttributes } from 'react';
import { SgDsLibraryAudioPlayer } from './AudioPlayer';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryAudioBlockProps = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
  artAlt?: string;
  artBackground?: string;
  artImageUrl?: string;
  artName?: string;
  bars?: number[];
  endTime?: string;
  onProgressChange?: (progress: number) => void;
  playedBars?: number | string;
  playLabel?: string;
  progress?: number | string;
  progressLabel?: string;
  startTime?: string;
};

const DEFAULT_AUDIO_BLOCK_BAR_COUNT = 32;

export function SgDsLibraryAudioBlock(rawProps: SgDsLibraryAudioBlockProps) {
  const {
  artAlt = '',
  artBackground = 'linear-gradient(135deg, #111827 0%, #7c3aed 48%, #f43f5e 100%)',
  artImageUrl = '',
  artName = 'dusk.exe',
  bars,
  className = '',
  endTime = '3:25',
  onProgressChange,
  playedBars = 16,
  playLabel = 'Play track',
  progress: progressProp,
  progressLabel = 'Audio progress',
  startTime = '1:14',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const artStyle: CSSProperties = { background: artBackground };
  const sourceBarCount = bars && bars.length > 0 ? bars.length : DEFAULT_AUDIO_BLOCK_BAR_COUNT;
  const playedBarCount = toFiniteNumber(playedBars, 16);
  const derivedProgress = clampProgress(
    progressProp ?? (playedBarCount <= sourceBarCount
      ? (playedBarCount / sourceBarCount) * 100
      : playedBarCount),
  );
  const [localProgress, setLocalProgress] = useState(derivedProgress);
  const controlledProgress = progressProp !== undefined;
  const progress = controlledProgress ? derivedProgress : localProgress;
  const trackStyle = { '--audio-block-progress': `${progress}%` } as CSSProperties;

  useEffect(() => {
    setLocalProgress(derivedProgress);
  }, [derivedProgress]);

  function handleProgressChange(nextProgress: number) {
    const clamped = clampProgress(nextProgress);
    if (!controlledProgress) setLocalProgress(clamped);
    onProgressChange?.(clamped);
  }

  return (
    <div {...props} className={['sg-ds-library-scope', 'audio-block', className].filter(Boolean).join(' ')}>
      <div className="audio-block-art" style={artStyle}>
        {artImageUrl ? <img className="audio-block-art-image" src={artImageUrl} alt={artAlt} /> : null}
        <span className="audio-block-art-name">{artName}</span>
      </div>
      <div className="audio-block-content">
        <SgDsLibraryAudioPlayer
          bars={bars}
          playedBars={playedBars}
          playLabel={playLabel}
          progress={progress}
          time=""
          variant="inline"
        />
        <div className="audio-block-timecode">
          <span>{startTime}</span>
          <input
            aria-label={progressLabel}
            className="audio-block-timecode-track"
            max={100}
            min={0}
            step={1}
            style={trackStyle}
            type="range"
            value={Math.round(progress)}
            onChange={(event) => handleProgressChange(Number(event.currentTarget.value))}
          />
          <span>{endTime}</span>
        </div>
      </div>
    </div>
  );
}

function clampProgress(value: number | string): number {
  return Math.max(0, Math.min(100, toFiniteNumber(value, 0)));
}

function toFiniteNumber(value: number | string | undefined, fallback: number): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return fallback;
}

export default SgDsLibraryAudioBlock;

// frontend/src/components/AudioBlock.vue
<script setup>
import { ref, computed, watch, useAttrs } from 'vue'
import AudioPlayer from './AudioPlayer.vue'

const attrs = useAttrs()

const props = defineProps({
  artAlt: { default: '' },
  artBackground: { default: 'linear-gradient(135deg, #111827 0%, #7c3aed 48%, #f43f5e 100%)' },
  artImageUrl: { default: '' },
  artName: { default: 'dusk.exe' },
  bars: { default: undefined },
  endTime: { default: '3:25' },
  onProgressChange: { default: undefined },
  playedBars: { default: 16 },
  playLabel: { default: 'Play track' },
  progress: { default: undefined },
  progressLabel: { default: 'Audio progress' },
  startTime: { default: '1:14' },
})

const DEFAULT_AUDIO_BLOCK_BAR_COUNT = 32

function toFiniteNumber(value, fallback) {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value)
    if (Number.isFinite(parsed)) return parsed
  }
  return fallback
}

function clampProgress(value) {
  return Math.max(0, Math.min(100, toFiniteNumber(value, 0)))
}

const derivedProgress = computed(() => {
  const sourceBarCount = props.bars && props.bars.length > 0 ? props.bars.length : DEFAULT_AUDIO_BLOCK_BAR_COUNT
  const playedBarCount = toFiniteNumber(props.playedBars, 16)
  return clampProgress(
    props.progress !== undefined
      ? props.progress
      : (playedBarCount <= sourceBarCount
          ? (playedBarCount / sourceBarCount) * 100
          : playedBarCount)
  )
})

const localProgress = ref(derivedProgress.value)

watch(derivedProgress, (val) => {
  localProgress.value = val
})

const controlledProgress = computed(() => props.progress !== undefined)

const progress = computed(() => controlledProgress.value ? derivedProgress.value : localProgress.value)

const artStyle = computed(() => ({ background: props.artBackground }))

const trackStyle = computed(() => ({ '--audio-block-progress': `${progress.value}%` }))

const classes = computed(() =>
  ['sg-ds-library-scope', 'audio-block', attrs.class].filter(Boolean).join(' ')
)

function handleProgressChange(event) {
  const nextProgress = Number(event.currentTarget.value)
  const clamped = clampProgress(nextProgress)
  if (!controlledProgress.value) localProgress.value = clamped
  if (props.onProgressChange) props.onProgressChange(clamped)
}
</script>

<template>
  <div v-bind="{ ...$attrs, class: undefined }" :class="classes">
    <div class="audio-block-art" :style="artStyle">
      <img v-if="props.artImageUrl" class="audio-block-art-image" :src="props.artImageUrl" :alt="props.artAlt" />
      <span class="audio-block-art-name">{{ props.artName }}</span>
    </div>
    <div class="audio-block-content">
      <AudioPlayer
        :bars="props.bars"
        :played-bars="props.playedBars"
        :play-label="props.playLabel"
        :progress="progress"
        time=""
        variant="inline"
      />
      <div class="audio-block-timecode">
        <span>{{ props.startTime }}</span>
        <input
          :aria-label="props.progressLabel"
          class="audio-block-timecode-track"
          :max="100"
          :min="0"
          :step="1"
          :style="trackStyle"
          type="range"
          :value="Math.round(progress)"
          @change="handleProgressChange"
        />
        <span>{{ props.endTime }}</span>
      </div>
    </div>
  </div>
</template>
