// frontend/src/libraries/sg-ds-library/components/AudioPlayer.tsx
import { useEffect, useMemo, useRef, useState, type HTMLAttributes } from 'react';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryAudioPlayerSize = 'sm' | 'md';
export type SgDsLibraryAudioPlayerVariant = 'default' | 'inline' | 'compact';

export type SgDsLibraryAudioPlayerProps = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
  autoFillBars?: boolean;
  bars?: number[];
  playedBars?: number | string;
  playLabel?: string;
  progress?: number | string;
  size?: SgDsLibraryAudioPlayerSize;
  time?: string;
  variant?: SgDsLibraryAudioPlayerVariant;
};

const DEFAULT_WAVEFORM = [
  32, 54, 72, 48, 64, 84, 46, 36, 68, 58, 76, 42,
  52, 88, 62, 34, 74, 56, 44, 82, 66, 38, 58, 78,
  48, 70, 52, 40, 86, 60, 36, 68,
];

export function SgDsLibraryAudioPlayer(rawProps: SgDsLibraryAudioPlayerProps) {
  const {
  autoFillBars = true,
  bars = DEFAULT_WAVEFORM,
  className = '',
  playedBars = 12,
  playLabel = 'Play audio',
  progress,
  size = 'md',
  time = '0:14 / 0:36',
  variant = 'default',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const waveformRef = useRef<HTMLDivElement>(null);
  const sourceBars = bars.length > 0 ? bars : DEFAULT_WAVEFORM;
  const [autoBarCount, setAutoBarCount] = useState(sourceBars.length);
  const renderedBars = useMemo(() => {
    const targetCount = autoFillBars ? Math.max(sourceBars.length, autoBarCount) : sourceBars.length;
    return Array.from({ length: targetCount }, (_item, index) => sourceBars[index % sourceBars.length] ?? 50);
  }, [autoBarCount, autoFillBars, sourceBars]);
  const safeProgress = clampProgress(progress);
  const safePlayedBars = safeProgress === null
    ? Math.max(0, Math.min(Math.round(toFiniteNumber(playedBars, 0)), renderedBars.length))
    : Math.max(0, Math.min(Math.round(renderedBars.length * (safeProgress / 100)), renderedBars.length));

  useEffect(() => {
    if (!autoFillBars) {
      setAutoBarCount(sourceBars.length);
      return undefined;
    }

    const waveform = waveformRef.current;
    if (!waveform) return undefined;

    function updateBarCount() {
      const computed = window.getComputedStyle(waveform);
      const gap = parseCssLength(computed.columnGap || computed.gap, 2);
      const barWidth = parseCssLength(computed.getPropertyValue('--c-audio-player-bar-width'), 2);
      const availableWidth = waveform.clientWidth;
      if (availableWidth <= 0) {
        setAutoBarCount(sourceBars.length);
        return;
      }
      const nextCount = Math.max(
        sourceBars.length,
        Math.min(160, Math.floor((availableWidth + gap) / Math.max(1, barWidth + gap))),
      );
      setAutoBarCount((current) => current === nextCount ? current : nextCount);
    }

    updateBarCount();
    const observer = new ResizeObserver(updateBarCount);
    observer.observe(waveform);
    return () => observer.disconnect();
  }, [autoFillBars, sourceBars.length]);

  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'audio-player', className].filter(Boolean).join(' ')}
      data-size={size === 'sm' ? 'sm' : undefined}
      data-variant={variant === 'default' ? undefined : variant}
    >
      <button className="audio-player-play" type="button" aria-label={playLabel}>
        <SgDsLibraryIcon name="play" size="42%" />
      </button>
      <div className="audio-player-waveform" aria-hidden="true" ref={waveformRef}>
        {renderedBars.map((height, index) => (
          <span
            className={index < safePlayedBars ? 'played' : undefined}
            key={`${height}-${index}`}
            style={{ height: `${clampBarHeight(height)}%` }}
          />
        ))}
      </div>
      {time ? <span className="audio-player-time">{time}</span> : null}
    </div>
  );
}

function parseCssLength(value: string, fallback: number): number {
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function clampBarHeight(value: number): number {
  if (!Number.isFinite(value)) return 50;
  return Math.max(16, Math.min(100, Math.round(value)));
}

function clampProgress(value: number | string | undefined): number | null {
  const numeric = toFiniteNumber(value, Number.NaN);
  if (!Number.isFinite(numeric)) return null;
  return Math.max(0, Math.min(100, numeric));
}

function toFiniteNumber(value: number | string | undefined, fallback: number): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return fallback;
}

export default SgDsLibraryAudioPlayer;

// frontend/src/components/AudioPlayer.vue
<script>
const DEFAULT_WAVEFORM = [
  32, 54, 72, 48, 64, 84, 46, 36, 68, 58, 76, 42,
  52, 88, 62, 34, 74, 56, 44, 82, 66, 38, 58, 78,
  48, 70, 52, 40, 86, 60, 36, 68,
]
</script>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch, useAttrs } from 'vue'
import Icon from './Icon.vue'

const attrs = useAttrs()

const props = defineProps({
  autoFillBars: { default: true },
  bars: { default: () => DEFAULT_WAVEFORM },
  playedBars: { default: 12 },
  playLabel: { default: 'Play audio' },
  progress: { default: undefined },
  size: { default: 'md' },
  time: { default: '0:14 / 0:36' },
  variant: { default: 'default' },
})

const waveformRef = ref(null)
const autoBarCount = ref(DEFAULT_WAVEFORM.length)

const sourceBars = computed(() => props.bars.length > 0 ? props.bars : DEFAULT_WAVEFORM)

const renderedBars = computed(() => {
  const targetCount = props.autoFillBars
    ? Math.max(sourceBars.value.length, autoBarCount.value)
    : sourceBars.value.length
  return Array.from({ length: targetCount }, (_item, index) => sourceBars.value[index % sourceBars.value.length] ?? 50)
})

const safeProgress = computed(() => clampProgress(props.progress))

const safePlayedBars = computed(() => {
  if (safeProgress.value === null) {
    return Math.max(0, Math.min(Math.round(toFiniteNumber(props.playedBars, 0)), renderedBars.value.length))
  }
  return Math.max(0, Math.min(Math.round(renderedBars.value.length * (safeProgress.value / 100)), renderedBars.value.length))
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'audio-player', attrs.class].filter(Boolean).join(' ')
)

function parseCssLength(value, fallback) {
  const parsed = Number.parseFloat(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function clampBarHeight(value) {
  if (!Number.isFinite(value)) return 50
  return Math.max(16, Math.min(100, Math.round(value)))
}

function clampProgress(value) {
  const numeric = toFiniteNumber(value, Number.NaN)
  if (!Number.isFinite(numeric)) return null
  return Math.max(0, Math.min(100, numeric))
}

function toFiniteNumber(value, fallback) {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value)
    if (Number.isFinite(parsed)) return parsed
  }
  return fallback
}

let observer = null

function updateBarCount() {
  const waveform = waveformRef.value
  if (!waveform) return
  const computedStyle = window.getComputedStyle(waveform)
  const gap = parseCssLength(computedStyle.columnGap || computedStyle.gap, 2)
  const barWidth = parseCssLength(computedStyle.getPropertyValue('--c-audio-player-bar-width'), 2)
  const availableWidth = waveform.clientWidth
  if (availableWidth <= 0) {
    autoBarCount.value = sourceBars.value.length
    return
  }
  const nextCount = Math.max(
    sourceBars.value.length,
    Math.min(160, Math.floor((availableWidth + gap) / Math.max(1, barWidth + gap))),
  )
  if (autoBarCount.value !== nextCount) {
    autoBarCount.value = nextCount
  }
}

function setupObserver() {
  if (observer) {
    observer.disconnect()
    observer = null
  }
  if (!props.autoFillBars) {
    autoBarCount.value = sourceBars.value.length
    return
  }
  const waveform = waveformRef.value
  if (!waveform) return
  updateBarCount()
  observer = new ResizeObserver(updateBarCount)
  observer.observe(waveform)
}

onMounted(() => {
  setupObserver()
})

onUnmounted(() => {
  if (observer) {
    observer.disconnect()
    observer = null
  }
})

watch([() => props.autoFillBars, () => sourceBars.value.length], () => {
  setupObserver()
})
</script>

<template>
  <div
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-size="props.size === 'sm' ? 'sm' : undefined"
    :data-variant="props.variant !== 'default' ? props.variant : undefined"
  >
    <button class="audio-player-play" type="button" :aria-label="props.playLabel">
      <Icon name="play" size="42%" />
    </button>
    <div class="audio-player-waveform" aria-hidden="true" ref="waveformRef">
      <span
        v-for="(height, index) in renderedBars"
        :key="`${height}-${index}`"
        :class="index < safePlayedBars ? 'played' : undefined"
        :style="{ height: `${clampBarHeight(height)}%` }"
      />
    </div>
    <span v-if="props.time" class="audio-player-time">{{ props.time }}</span>
  </div>
</template>
