// frontend/src/libraries/sg-ds-library/components/AudioFrame.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryAudioFrameVariant = 'music' | 'voice' | 'neutral';
export type SgDsLibraryAudioFrameBackground = 'default' | 'auto' | 'surface' | 'soft' | 'brand' | 'mint' | 'sunset' | 'mono';

export type SgDsLibraryAudioFrameProps = Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'title'> & {
  actionSlot?: ReactNode;
  background?: SgDsLibraryAudioFrameBackground;
  children?: ReactNode;
  eyebrow?: string;
  footerSlot?: ReactNode;
  meta?: string;
  title?: string;
  variant?: SgDsLibraryAudioFrameVariant;
};

export function SgDsLibraryAudioFrame(rawProps: SgDsLibraryAudioFrameProps) {
  const {
  actionSlot,
  background = 'default',
  children,
  className = '',
  eyebrow = '',
  footerSlot,
  meta = '',
  title = '',
  variant = 'neutral',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const hasHeader = Boolean(eyebrow || title || meta || actionSlot);

  return (
    <section
      {...props}
      className={['sg-ds-library-scope', 'audio-frame', className].filter(Boolean).join(' ')}
      data-background={background === 'default' || background === 'auto' ? undefined : background}
      data-variant={variant === 'neutral' ? undefined : variant}
    >
      {hasHeader ? (
        <header className="audio-frame-head">
          <div className="audio-frame-copy">
            {eyebrow ? <span className="audio-frame-eyebrow">{eyebrow}</span> : null}
            {title ? <strong className="audio-frame-title">{title}</strong> : null}
            {meta ? <span className="audio-frame-meta">{meta}</span> : null}
          </div>
          {actionSlot ? <div className="audio-frame-action">{actionSlot}</div> : null}
        </header>
      ) : null}
      {children ? <div className="audio-frame-body">{children}</div> : null}
      {footerSlot ? <footer className="audio-frame-footer">{footerSlot}</footer> : null}
    </section>
  );
}

export default SgDsLibraryAudioFrame;

// frontend/src/components/AudioFrame.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  background: { default: 'default' },
  eyebrow: { default: '' },
  meta: { default: '' },
  title: { default: '' },
  variant: { default: 'neutral' },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'audio-frame', attrs.class].filter(Boolean).join(' ')
)

const hasHeader = computed(() =>
  Boolean(props.eyebrow || props.title || props.meta)
)
</script>

<template>
  <section
    v-bind="{ ...attrs, class: undefined }"
    :class="classes"
    :data-background="props.background !== 'default' && props.background !== 'auto' ? props.background : undefined"
    :data-variant="props.variant !== 'neutral' ? props.variant : undefined"
  >
    <header v-if="hasHeader || $slots.action" class="audio-frame-head">
      <div class="audio-frame-copy">
        <span v-if="props.eyebrow" class="audio-frame-eyebrow">{{ props.eyebrow }}</span>
        <strong v-if="props.title" class="audio-frame-title">{{ props.title }}</strong>
        <span v-if="props.meta" class="audio-frame-meta">{{ props.meta }}</span>
      </div>
      <div v-if="$slots.action" class="audio-frame-action">
        <slot name="action" />
      </div>
    </header>
    <div v-if="$slots.default" class="audio-frame-body">
      <slot />
    </div>
    <footer v-if="$slots.footer" class="audio-frame-footer">
      <slot name="footer" />
    </footer>
  </section>
</template>
