// frontend/src/libraries/sg-ds-library/components/Avatar.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryAvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
export type SgDsLibraryAvatarShape = 'circle' | 'square' | 'rounded';
export type SgDsLibraryAvatarTone =
  | 'neutral'
  | 'brand'
  | 'teal'
  | 'amber'
  | 'purple'
  | 'coral'
  | 'blue'
  | 'pink'
  | 'green';
export type SgDsLibraryAvatarStatus = 'online' | 'offline' | 'busy' | 'away' | 'live';

export type SgDsLibraryAvatarProps = Omit<HTMLAttributes<HTMLSpanElement>, 'children'> & {
  src?: string;
  alt?: string;
  initials?: string;
  icon?: ReactNode;
  size?: SgDsLibraryAvatarSize;
  shape?: SgDsLibraryAvatarShape;
  tone?: SgDsLibraryAvatarTone;
  status?: SgDsLibraryAvatarStatus;
  statusLabel?: string;
  /** Suppress the pulsing animation on `status="live"` while keeping the
   *  red perimeter ring. Use for crowded grids / lists where movement
   *  becomes distracting. No effect on the other status values. */
  quietStatus?: boolean;
};

export function SgDsLibraryAvatar(rawProps: SgDsLibraryAvatarProps) {
  const {
  alt = '',
  className = '',
  icon,
  initials,
  quietStatus = false,
  shape = 'circle',
  size = 'md',
  src,
  status,
  statusLabel,
  tone = 'neutral',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <span
      {...props}
      className={['sg-ds-library-scope', 'avatar', className].filter(Boolean).join(' ')}
      data-size={size}
      data-shape={shape === 'circle' ? undefined : shape}
      data-tone={tone === 'neutral' ? undefined : tone}
    >
      {src ? <img className="avatar-image" src={src} alt={alt} /> : null}
      <span className="avatar-fallback" aria-hidden="true">
        {icon ?? initials ?? '?'}
      </span>
      {status ? (
        <span
          className="avatar-status"
          data-status={status}
          data-quiet={status === 'live' && quietStatus ? 'true' : undefined}
          aria-label={statusLabel ?? status}
        />
      ) : null}
    </span>
  );
}

export default SgDsLibraryAvatar;

// frontend/src/components/Avatar.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  src: { type: String, default: undefined },
  alt: { type: String, default: '' },
  initials: { type: String, default: undefined },
  size: { type: String, default: 'md' },
  shape: { type: String, default: 'circle' },
  tone: { type: String, default: 'neutral' },
  status: { type: String, default: undefined },
  statusLabel: { type: String, default: undefined },
  quietStatus: { type: Boolean, default: false },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'avatar', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <span
    v-bind="{ ...attrs, class: undefined }"
    :class="classes"
    :data-size="props.size"
    :data-shape="props.shape !== 'circle' ? props.shape : undefined"
    :data-tone="props.tone !== 'neutral' ? props.tone : undefined"
  >
    <img v-if="props.src" class="avatar-image" :src="props.src" :alt="props.alt" />
    <span class="avatar-fallback" aria-hidden="true">
      <slot name="icon">{{ props.initials ?? '?' }}</slot>
    </span>
    <span
      v-if="props.status"
      class="avatar-status"
      :data-status="props.status"
      :data-quiet="props.status === 'live' && props.quietStatus ? 'true' : undefined"
      :aria-label="props.statusLabel ?? props.status"
    />
  </span>
</template>
