// frontend/src/libraries/sg-ds-library/components/Breadcrumb.tsx
import type { AnchorHTMLAttributes, HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryBreadcrumbSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryBreadcrumbSeparator = 'slash' | 'chevron' | 'dot';

export type SgDsLibraryBreadcrumbPathItem = {
  href?: string;
  label: ReactNode;
};

export type SgDsLibraryBreadcrumbProps = HTMLAttributes<HTMLElement> & {
  children?: ReactNode;
  current?: ReactNode;
  items?: SgDsLibraryBreadcrumbPathItem[];
  label?: string;
  parent?: ReactNode;
  root?: ReactNode;
  separator?: SgDsLibraryBreadcrumbSeparator;
  size?: SgDsLibraryBreadcrumbSize;
};

export type SgDsLibraryBreadcrumbItemProps = HTMLAttributes<HTMLLIElement> & {
  children?: ReactNode;
};

export type SgDsLibraryBreadcrumbLinkProps = AnchorHTMLAttributes<HTMLAnchorElement> & {
  children?: ReactNode;
};

export type SgDsLibraryBreadcrumbCurrentProps = HTMLAttributes<HTMLSpanElement> & {
  children?: ReactNode;
};

const DEFAULT_BREADCRUMB_ITEMS: SgDsLibraryBreadcrumbPathItem[] = [
  { href: '#', label: 'Home' },
  { href: '#', label: 'Library' },
  { label: 'Components' },
];

export function SgDsLibraryBreadcrumb(rawProps: SgDsLibraryBreadcrumbProps) {
  const {
  children,
  className = '',
  current,
  items,
  label = 'Breadcrumb',
  parent,
  root,
  separator = 'slash',
  size = 'md',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const resolvedItems = items ?? (
    root !== undefined || parent !== undefined || current !== undefined
      ? [
          { href: '#', label: root ?? 'Home' },
          { href: '#', label: parent ?? 'Products' },
          { label: current ?? 'Headphones' },
        ]
      : DEFAULT_BREADCRUMB_ITEMS
  );

  return (
    <nav
      {...props}
      aria-label={label}
      className={['sg-ds-library-scope', 'breadcrumb', className].filter(Boolean).join(' ')}
      data-separator={separator}
      data-size={size}
    >
      <ol className="breadcrumb-list">
        {children ?? resolvedItems.map((item, index) => {
          const isCurrent = index === resolvedItems.length - 1 || !item.href;
          return (
            <SgDsLibraryBreadcrumbItem key={`${String(item.label)}-${index}`}>
              {isCurrent ? (
                <SgDsLibraryBreadcrumbCurrent>{item.label}</SgDsLibraryBreadcrumbCurrent>
              ) : (
                <SgDsLibraryBreadcrumbLink href={item.href}>{item.label}</SgDsLibraryBreadcrumbLink>
              )}
            </SgDsLibraryBreadcrumbItem>
          );
        })}
      </ol>
    </nav>
  );
}

export function SgDsLibraryBreadcrumbItem(rawProps: SgDsLibraryBreadcrumbItemProps) {
  const { children, className = '', ...props } = resolveWorkbenchModeProps(rawProps);
  return <li {...props} className={['sg-ds-library-scope', 'breadcrumb-item', className].filter(Boolean).join(' ')}>{children}</li>;
}

export function SgDsLibraryBreadcrumbLink(rawProps: SgDsLibraryBreadcrumbLinkProps) {
  const { children = 'Link', className = '', href = '#', ...props } = resolveWorkbenchModeProps(rawProps);
  return <a {...props} className={['sg-ds-library-scope', 'breadcrumb-link', className].filter(Boolean).join(' ')} href={href}>{children}</a>;
}

export function SgDsLibraryBreadcrumbCurrent(rawProps: SgDsLibraryBreadcrumbCurrentProps) {
  const { children = 'Current page', className = '', ...props } = resolveWorkbenchModeProps(rawProps);
  return <span {...props} aria-current="page" className={['sg-ds-library-scope', 'breadcrumb-current', className].filter(Boolean).join(' ')}>{children}</span>;
}

export default SgDsLibraryBreadcrumb;

// frontend/src/components/Breadcrumb.vue
<script setup>
import { computed, useAttrs, useSlots } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const slots = useSlots()

const props = defineProps({
  current: { default: undefined },
  items: { default: undefined },
  label: { default: 'Breadcrumb' },
  parent: { default: undefined },
  root: { default: undefined },
  separator: { default: 'slash' },
  size: { default: 'md' },
})

const DEFAULT_BREADCRUMB_ITEMS = [
  { href: '#', label: 'Home' },
  { href: '#', label: 'Library' },
  { label: 'Components' },
]

const resolvedItems = computed(() => {
  if (props.items !== undefined) return props.items
  if (props.root !== undefined || props.parent !== undefined || props.current !== undefined) {
    return [
      { href: '#', label: props.root ?? 'Home' },
      { href: '#', label: props.parent ?? 'Products' },
      { label: props.current ?? 'Headphones' },
    ]
  }
  return DEFAULT_BREADCRUMB_ITEMS
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'breadcrumb', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <nav
    v-bind="{ ...attrs, class: undefined }"
    :aria-label="props.label"
    :class="classes"
    :data-separator="props.separator"
    :data-size="props.size"
  >
    <ol class="breadcrumb-list">
      <slot>
        <li
          v-for="(item, index) in resolvedItems"
          :key="`${String(item.label)}-${index}`"
          class="sg-ds-library-scope breadcrumb-item"
        >
          <span
            v-if="index === resolvedItems.length - 1 || !item.href"
            aria-current="page"
            class="sg-ds-library-scope breadcrumb-current"
          >{{ item.label }}</span>
          <a
            v-else
            :href="item.href"
            class="sg-ds-library-scope breadcrumb-link"
          >{{ item.label }}</a>
        </li>
      </slot>
    </ol>
  </nav>
</template>
