// frontend/src/libraries/sg-ds-library/components/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryButtonVariant =
  | 'primary'
  | 'secondary'
  | 'outline'
  | 'soft'
  | 'ghost'
  | 'danger';
export type SgDsLibraryButtonSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryButtonShape = 'default' | 'pill';
export type SgDsLibraryButtonBadgeVariant =
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'neutral';

export type SgDsLibraryButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  children?: ReactNode;
  /** Backward-compatible label prop for Workbench/story args; `children` remains preferred. */
  label?: ReactNode;
  variant?: SgDsLibraryButtonVariant;
  size?: SgDsLibraryButtonSize;
  shape?: SgDsLibraryButtonShape;
  /** Icon name from the project asset picker (workbench `control: 'icon'`). */
  leadingIcon?: string;
  /** Direct React node override for the leading slot. */
  leadingIconNode?: ReactNode;
  /** Icon name from the project asset picker (workbench `control: 'icon'`). */
  trailingIcon?: string;
  /** Direct React node override for the trailing slot. */
  trailingIconNode?: ReactNode;
  iconOnly?: boolean;
  loading?: boolean;
  /** Render a count/notification badge in the top-right of the button. */
  badge?: boolean;
  badgeText?: string;
  badgeVariant?: SgDsLibraryButtonBadgeVariant;
};

function renderIconSlot(
  name: string | undefined,
  node: ReactNode | undefined,
): ReactNode {
  if (node !== undefined) return node;
  if (name) return <SgDsLibraryIcon name={name} size="1em" />;
  return null;
}

export function SgDsLibraryButton(rawProps: SgDsLibraryButtonProps) {
  const {
  badge = false,
  badgeText = '',
  badgeVariant = 'danger',
  children,
  className = '',
  disabled,
  iconOnly = false,
  label = '버튼',
  leadingIcon,
  leadingIconNode,
  loading = false,
  shape = 'default',
  size = 'md',
  trailingIcon,
  trailingIconNode,
  type = 'button',
  variant = 'primary',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const lead = renderIconSlot(leadingIcon, leadingIconNode);
  const trail = renderIconSlot(trailingIcon, trailingIconNode);
  const labelContent = children ?? label;
  const showBadge = badge && (badgeText || '').toString().length > 0;

  return (
    <button
      {...props}
      type={type}
      className={['sg-ds-library-scope', 'btn', className].filter(Boolean).join(' ')}
      data-variant={variant}
      data-size={size}
      data-shape={shape === 'pill' ? 'pill' : undefined}
      data-loading={loading || undefined}
      data-icon-only={iconOnly || undefined}
      disabled={disabled}
      aria-disabled={disabled || undefined}
      aria-busy={loading || undefined}
    >
      {loading ? <span className="btn-spinner" aria-hidden="true" /> : null}
      {lead ? (
        <span className="btn-icon" aria-hidden="true">
          {lead}
        </span>
      ) : null}
      {iconOnly ? null : <span className="btn-label">{labelContent}</span>}
      {/* Inline badge sits between the label and any trailing icon —
       * it rides the same flex gap as the icon slots, so multi-character
       * counts ("99+") never overflow the button hit area. */}
      {showBadge && !iconOnly ? (
        <span className="btn-badge" data-status={badgeVariant} aria-hidden="true">
          {badgeText}
        </span>
      ) : null}
      {trail && !iconOnly ? (
        <span className="btn-icon" aria-hidden="true">
          {trail}
        </span>
      ) : null}
    </button>
  );
}

export default SgDsLibraryButton;

// frontend/src/components/Button.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Icon from './Icon.vue'

const attrs = useAttrs()

const props = defineProps({
  label: { default: '버튼' },
  variant: { default: 'primary' },
  size: { default: 'md' },
  shape: { default: 'default' },
  leadingIcon: { default: undefined },
  trailingIcon: { default: undefined },
  iconOnly: { default: false },
  loading: { default: false },
  badge: { default: false },
  badgeText: { default: '' },
  badgeVariant: { default: 'danger' },
  type: { default: 'button' },
  disabled: { default: false },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'btn', attrs.class].filter(Boolean).join(' ')
)

const showBadge = computed(() =>
  props.badge && String(props.badgeText).length > 0
)
</script>

<template>
  <button
    v-bind="{ ...($attrs), class: undefined }"
    :class="classes"
    :type="props.type"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-shape="props.shape === 'pill' ? 'pill' : undefined"
    :data-loading="props.loading || undefined"
    :data-icon-only="props.iconOnly || undefined"
    :disabled="props.disabled"
    :aria-disabled="props.disabled || undefined"
    :aria-busy="props.loading || undefined"
  >
    <span v-if="props.loading" class="btn-spinner" aria-hidden="true" />

    <span v-if="$slots.leadingIcon || props.leadingIcon" class="btn-icon" aria-hidden="true">
      <slot name="leadingIcon">
        <Icon :name="props.leadingIcon" size="1em" />
      </slot>
    </span>

    <span v-if="!props.iconOnly" class="btn-label">
      <slot>{{ props.label }}</slot>
    </span>

    <span
      v-if="showBadge && !props.iconOnly"
      class="btn-badge"
      :data-status="props.badgeVariant"
      aria-hidden="true"
    >{{ props.badgeText }}</span>

    <span v-if="($slots.trailingIcon || props.trailingIcon) && !props.iconOnly" class="btn-icon" aria-hidden="true">
      <slot name="trailingIcon">
        <Icon :name="props.trailingIcon" size="1em" />
      </slot>
    </span>
  </button>
</template>
