// frontend/src/libraries/sg-ds-library/components/CommentInput.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryAvatar, type SgDsLibraryAvatarTone } from './Avatar';
import { SgDsLibraryButton } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { SgDsLibraryTextarea } from './Textarea';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryCommentInputProps = Omit<HTMLAttributes<HTMLDivElement>, 'defaultValue'> & {
  autoFocus?: boolean;
  avatarSrc?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  cancelLabel?: ReactNode;
  context?: ReactNode;
  defaultValue?: string;
  disabled?: boolean;
  helperText?: ReactNode;
  initials?: string;
  maxLength?: number | string;
  name?: string;
  placeholder?: string;
  readOnly?: boolean;
  required?: boolean;
  rows?: number | string;
  showAttachment?: boolean;
  showAvatar?: boolean;
  showCancel?: boolean;
  showCounter?: boolean;
  showEmoji?: boolean;
  showMention?: boolean;
  submitDisabled?: boolean;
  submitLabel?: ReactNode;
  textareaId?: string;
  textareaLabel?: string;
};

export function SgDsLibraryCommentInput(rawProps: SgDsLibraryCommentInputProps) {
  const {
    autoFocus,
    avatarSrc,
    avatarTone = 'brand',
    cancelLabel = '취소',
    className = '',
    context,
    defaultValue = '',
    disabled = false,
    helperText,
    initials = 'U',
    maxLength,
    name,
    placeholder = '댓글을 입력하세요',
    readOnly = false,
    required = false,
    rows = 3,
    showAttachment = true,
    showAvatar = true,
    showCancel = false,
    showCounter = true,
    showEmoji = true,
    showMention = false,
    submitDisabled = false,
    submitLabel = '등록',
    textareaId,
    textareaLabel = '댓글 입력',
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const normalizedMaxLength = normalizeOptionalNumber(maxLength);
  const hasTools = showAttachment || showEmoji || showMention;
  const counter = showCounter && normalizedMaxLength ? `${defaultValue.length}/${normalizedMaxLength}` : '';
  const hasMeta = Boolean(helperText || counter);
  const lockControls = disabled || readOnly;

  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'comment-input', className].filter(Boolean).join(' ')}
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
      data-show-avatar={showAvatar ? undefined : 'false'}
    >
      {showAvatar ? <SgDsLibraryAvatar size="sm" tone={avatarTone} initials={initials} src={avatarSrc} /> : null}
      <div className="comment-input-panel">
        {context ? (
          <div className="comment-input-context">
            <SgDsLibraryIcon name="corner-down-right" size="1em" />
            <span>{context}</span>
          </div>
        ) : null}
        <SgDsLibraryTextarea
          id={textareaId}
          name={name}
          className="comment-input-textarea"
          aria-label={textareaLabel}
          autoFocus={autoFocus}
          defaultValue={defaultValue}
          disabled={disabled}
          maxLength={normalizedMaxLength}
          placeholder={placeholder}
          readOnly={readOnly}
          required={required}
          rows={rows}
          size="md"
        />
        <div className="comment-input-toolbar">
          {hasTools ? (
            <div className="comment-input-tools">
              {showAttachment ? (
                <SgDsLibraryButton
                  aria-label="파일 첨부"
                  className="comment-input-tool"
                  disabled={lockControls}
                  iconOnly
                  label="파일 첨부"
                  leadingIcon="paperclip"
                  size="sm"
                  variant="ghost"
                />
              ) : null}
              {showEmoji ? (
                <SgDsLibraryButton
                  aria-label="이모지 추가"
                  className="comment-input-tool"
                  disabled={lockControls}
                  iconOnly
                  label="이모지 추가"
                  leadingIcon="smile"
                  size="sm"
                  variant="ghost"
                />
              ) : null}
              {showMention ? (
                <SgDsLibraryButton
                  aria-label="멘션 추가"
                  className="comment-input-tool"
                  disabled={lockControls}
                  iconOnly
                  label="멘션 추가"
                  leadingIcon="at-sign"
                  size="sm"
                  variant="ghost"
                />
              ) : null}
            </div>
          ) : (
            <span className="comment-input-toolbar-spacer" aria-hidden="true" />
          )}
          <div className="comment-input-actions">
            {hasMeta ? (
              <span className="comment-input-meta">
                {helperText ? <span className="comment-input-helper">{helperText}</span> : null}
                {counter ? <span className="comment-input-counter">{counter}</span> : null}
              </span>
            ) : null}
            {showCancel ? (
              <SgDsLibraryButton
                className="comment-input-cancel"
                disabled={disabled}
                label={cancelLabel}
                size="sm"
                variant="ghost"
              />
            ) : null}
            <SgDsLibraryButton
              className="comment-input-submit"
              disabled={disabled || submitDisabled || readOnly}
              label={submitLabel}
              leadingIcon="send"
              size="sm"
              variant="primary"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function normalizeOptionalNumber(value: number | string | undefined): number | undefined {
  if (typeof value === 'undefined') return undefined;
  const parsed = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : undefined;
}

export default SgDsLibraryCommentInput;

// frontend/src/components/CommentInput.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Avatar from './Avatar.vue'
import Button from './Button.vue'
import Icon from './Icon.vue'
import Textarea from './Textarea.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  autoFocus: { default: false },
  avatarSrc: { default: undefined },
  avatarTone: { default: 'brand' },
  cancelLabel: { default: '취소' },
  context: { default: undefined },
  defaultValue: { default: '' },
  disabled: { default: false },
  helperText: { default: undefined },
  initials: { default: 'U' },
  maxLength: { default: undefined },
  name: { default: undefined },
  placeholder: { default: '댓글을 입력하세요' },
  readOnly: { default: false },
  required: { default: false },
  rows: { default: 3 },
  showAttachment: { default: true },
  showAvatar: { default: true },
  showCancel: { default: false },
  showCounter: { default: true },
  showEmoji: { default: true },
  showMention: { default: false },
  submitDisabled: { default: false },
  submitLabel: { default: '등록' },
  textareaId: { default: undefined },
  textareaLabel: { default: '댓글 입력' },
})

function normalizeOptionalNumber(value) {
  if (typeof value === 'undefined') return undefined
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : undefined
}

const normalizedMaxLength = computed(() => normalizeOptionalNumber(props.maxLength))
const hasTools = computed(() => props.showAttachment || props.showEmoji || props.showMention)
const counter = computed(() =>
  props.showCounter && normalizedMaxLength.value
    ? `${props.defaultValue.length}/${normalizedMaxLength.value}`
    : ''
)
const hasMeta = computed(() => Boolean(props.helperText || counter.value))
const lockControls = computed(() => props.disabled || props.readOnly)

const classes = computed(() =>
  ['sg-ds-library-scope', 'comment-input', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <div
    v-bind="{ ...attrs, class: undefined }"
    :class="classes"
    :data-disabled="props.disabled || undefined"
    :data-readonly="props.readOnly || undefined"
    :data-show-avatar="props.showAvatar ? undefined : 'false'"
  >
    <Avatar v-if="props.showAvatar" size="sm" :tone="props.avatarTone" :initials="props.initials" :src="props.avatarSrc" />
    <div class="comment-input-panel">
      <div v-if="props.context" class="comment-input-context">
        <Icon name="corner-down-right" size="1em" />
        <span>{{ props.context }}</span>
      </div>
      <Textarea
        :id="props.textareaId"
        :name="props.name"
        class="comment-input-textarea"
        :aria-label="props.textareaLabel"
        :auto-focus="props.autoFocus"
        :default-value="props.defaultValue"
        :disabled="props.disabled"
        :max-length="normalizedMaxLength"
        :placeholder="props.placeholder"
        :read-only="props.readOnly"
        :required="props.required"
        :rows="props.rows"
        size="md"
      />
      <div class="comment-input-toolbar">
        <div v-if="hasTools" class="comment-input-tools">
          <Button
            v-if="props.showAttachment"
            aria-label="파일 첨부"
            class="comment-input-tool"
            :disabled="lockControls"
            :icon-only="true"
            label="파일 첨부"
            leading-icon="paperclip"
            size="sm"
            variant="ghost"
          />
          <Button
            v-if="props.showEmoji"
            aria-label="이모지 추가"
            class="comment-input-tool"
            :disabled="lockControls"
            :icon-only="true"
            label="이모지 추가"
            leading-icon="smile"
            size="sm"
            variant="ghost"
          />
          <Button
            v-if="props.showMention"
            aria-label="멘션 추가"
            class="comment-input-tool"
            :disabled="lockControls"
            :icon-only="true"
            label="멘션 추가"
            leading-icon="at-sign"
            size="sm"
            variant="ghost"
          />
        </div>
        <span v-else class="comment-input-toolbar-spacer" aria-hidden="true" />
        <div class="comment-input-actions">
          <span v-if="hasMeta" class="comment-input-meta">
            <span v-if="props.helperText" class="comment-input-helper">{{ props.helperText }}</span>
            <span v-if="counter" class="comment-input-counter">{{ counter }}</span>
          </span>
          <Button
            v-if="props.showCancel"
            class="comment-input-cancel"
            :disabled="props.disabled"
            :label="props.cancelLabel"
            size="sm"
            variant="ghost"
          />
          <Button
            class="comment-input-submit"
            :disabled="props.disabled || props.submitDisabled || props.readOnly"
            :label="props.submitLabel"
            leading-icon="send"
            size="sm"
            variant="primary"
          />
        </div>
      </div>
    </div>
  </div>
</template>
