// frontend/src/libraries/sg-ds-library/components/Comment.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryAvatar, type SgDsLibraryAvatarTone } from './Avatar';
import { SgDsLibraryButton } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryCommentProps = HTMLAttributes<HTMLDivElement> & {
  author?: ReactNode;
  authorMeta?: ReactNode;
  avatarSrc?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  body?: ReactNode;
  comment?: ReactNode;
  initials?: string;
  liked?: boolean;
  likeCount?: number | string;
  pinned?: boolean;
  replyCount?: number | string;
  time?: ReactNode;
  verified?: boolean;
};

export function SgDsLibraryComment(rawProps: SgDsLibraryCommentProps) {
  const {
  author = 'User',
  authorMeta,
  avatarSrc,
  avatarTone = 'brand',
  body,
  className = '',
  comment,
  initials = 'U',
  liked = false,
  likeCount,
  pinned = false,
  replyCount,
  time,
  verified = false,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const resolvedBody = body ?? comment;
  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'comment', className].filter(Boolean).join(' ')}
      data-pinned={pinned || undefined}
    >
      <SgDsLibraryAvatar size="sm" tone={avatarTone} initials={initials} src={avatarSrc} />
      <div className="comment-body">
        <div className="comment-head">
          <span className="comment-author">
            {author}
            {verified ? (
              <span className="comment-verified" aria-label="Verified">
                <SgDsLibraryIcon name="badge-check" size="1em" />
              </span>
            ) : null}
          </span>
          {authorMeta ? <span className="comment-author-meta">{authorMeta}</span> : null}
          {time ? <span className="comment-time">{time}</span> : null}
          {pinned ? <span className="comment-pinned" aria-label="Pinned"><SgDsLibraryIcon name="pin" size="1em" /> 고정됨</span> : null}
        </div>
        {resolvedBody ? <p className="comment-text">{resolvedBody}</p> : null}
        <div className="comment-reactions">
          <SgDsLibraryButton
            className={liked ? 'is-liked' : ''}
            variant="ghost"
            size="sm"
            leadingIcon={liked ? 'heart' : 'heart'}
            label={typeof likeCount === 'undefined' ? '좋아요' : String(likeCount)}
          />
          <SgDsLibraryButton
            variant="ghost"
            size="sm"
            leadingIcon="corner-down-right"
            label={typeof replyCount === 'undefined' || replyCount === 0 ? '답글' : `답글 ${replyCount}`}
          />
          <SgDsLibraryButton
            variant="ghost"
            size="sm"
            iconOnly
            leadingIcon="flag"
            aria-label="신고"
          />
          <SgDsLibraryButton
            variant="ghost"
            size="sm"
            iconOnly
            leadingIcon="ellipsis"
            aria-label="더보기"
          />
        </div>
      </div>
    </div>
  );
}

export default SgDsLibraryComment;

// frontend/src/components/Comment.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Avatar from './Avatar.vue'
import Button from './Button.vue'
import Icon from './Icon.vue'

const attrs = useAttrs()

const props = defineProps({
  author: { default: 'User' },
  authorMeta: { default: undefined },
  avatarSrc: { default: undefined },
  avatarTone: { default: 'brand' },
  body: { default: undefined },
  comment: { default: undefined },
  initials: { default: 'U' },
  liked: { default: false },
  likeCount: { default: undefined },
  pinned: { default: false },
  replyCount: { default: undefined },
  time: { default: undefined },
  verified: { default: false },
})

const resolvedBody = computed(() => props.body ?? props.comment)

const classes = computed(() =>
  ['sg-ds-library-scope', 'comment', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <div
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-pinned="props.pinned || undefined"
  >
    <Avatar size="sm" :tone="props.avatarTone" :initials="props.initials" :src="props.avatarSrc" />
    <div class="comment-body">
      <div class="comment-head">
        <span class="comment-author">
          {{ props.author }}
          <span v-if="props.verified" class="comment-verified" aria-label="Verified">
            <Icon name="badge-check" size="1em" />
          </span>
        </span>
        <span v-if="props.authorMeta" class="comment-author-meta">{{ props.authorMeta }}</span>
        <span v-if="props.time" class="comment-time">{{ props.time }}</span>
        <span v-if="props.pinned" class="comment-pinned" aria-label="Pinned">
          <Icon name="pin" size="1em" /> 고정됨
        </span>
      </div>
      <p v-if="resolvedBody" class="comment-text">{{ resolvedBody }}</p>
      <div class="comment-reactions">
        <Button
          :class="props.liked ? 'is-liked' : ''"
          variant="ghost"
          size="sm"
          leading-icon="heart"
          :label="typeof props.likeCount === 'undefined' ? '좋아요' : String(props.likeCount)"
        />
        <Button
          variant="ghost"
          size="sm"
          leading-icon="corner-down-right"
          :label="typeof props.replyCount === 'undefined' || props.replyCount === 0 ? '답글' : `답글 ${props.replyCount}`"
        />
        <Button
          variant="ghost"
          size="sm"
          :icon-only="true"
          leading-icon="flag"
          aria-label="신고"
        />
        <Button
          variant="ghost"
          size="sm"
          :icon-only="true"
          leading-icon="ellipsis"
          aria-label="더보기"
        />
      </div>
    </div>
  </div>
</template>
