// frontend/src/libraries/sg-ds-library/components/FollowRow.tsx
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, HTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryAvatar, type SgDsLibraryAvatarTone } from './Avatar';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryFollowRowSize = 'sm' | 'md';
export type SgDsLibraryFollowRowState = 'default' | 'live';
export type SgDsLibraryFollowRowAs = 'a' | 'button' | 'div';
export type SgDsLibraryFollowRowTailStatus = 'neutral' | 'info' | 'success' | 'warning' | 'danger' | 'live';
export type SgDsLibraryFollowRowTailVariant = 'plain' | 'subtle' | 'solid';

export type SgDsLibraryFollowRowProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'type'> & {
  as?: SgDsLibraryFollowRowAs;
  avatarSrc?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  buttonType?: ButtonHTMLAttributes<HTMLButtonElement>['type'];
  initials?: string;
  name?: ReactNode;
  size?: SgDsLibraryFollowRowSize;
  state?: SgDsLibraryFollowRowState;
  tail?: ReactNode;
  tailStatus?: SgDsLibraryFollowRowTailStatus;
  tailVariant?: SgDsLibraryFollowRowTailVariant;
};

export function SgDsLibraryFollowRow(rawProps: SgDsLibraryFollowRowProps) {
  const {
  as = 'a',
  avatarSrc,
  avatarTone = 'brand',
  buttonType = 'button',
  className = '',
  href = '#',
  initials = 'HL',
  name = 'Hailey Luna',
  size = 'sm',
  state = 'default',
  tail,
  tailStatus,
  tailVariant,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const isLive = state === 'live';
  const classNames = ['sg-ds-library-scope', 'follow-row', className].filter(Boolean).join(' ');
  const isPrimitiveTail = typeof tail === 'string' || typeof tail === 'number';
  const resolvedTailStatus: SgDsLibraryFollowRowTailStatus = tailStatus ?? (isLive ? 'live' : 'neutral');
  const resolvedTailVariant: SgDsLibraryFollowRowTailVariant = tailVariant ?? 'plain';
  let resolvedTail: ReactNode;
  if (tail == null) {
    resolvedTail = (
      <span
        className="follow-row-tail"
        data-status={resolvedTailStatus}
        data-variant={resolvedTailVariant}
        data-tone={resolvedTailStatus === 'live' ? 'live' : undefined}
      >
        {isLive ? 'LIVE' : '5m'}
      </span>
    );
  } else if (tail === '') {
    resolvedTail = null;
  } else if (isPrimitiveTail) {
    resolvedTail = (
      <span
        className="follow-row-tail"
        data-status={resolvedTailStatus}
        data-variant={resolvedTailVariant}
        data-tone={resolvedTailStatus === 'live' ? 'live' : undefined}
      >
        {tail}
      </span>
    );
  } else {
    resolvedTail = tail;
  }
  const content = (
    <>
      <SgDsLibraryAvatar
        initials={initials}
        size={size === 'md' ? 'md' : 'sm'}
        src={avatarSrc}
        status={isLive ? 'live' : undefined}
        tone={avatarTone}
      />
      <span className="follow-row-name">{name}</span>
      {resolvedTail}
    </>
  );
  const hostProps = {
    ...props,
    className: classNames,
    'data-size': size,
    'data-state': isLive ? 'live' : undefined,
  };

  if (as === 'button') {
    return <button {...(hostProps as ButtonHTMLAttributes<HTMLButtonElement>)} type={buttonType}>{content}</button>;
  }
  if (as === 'div') {
    return <div {...(hostProps as HTMLAttributes<HTMLDivElement>)}>{content}</div>;
  }
  return (
    <a {...(hostProps as AnchorHTMLAttributes<HTMLAnchorElement>)} href={href}>
      {content}
    </a>
  );
}

export default SgDsLibraryFollowRow;

// frontend/src/components/FollowRow.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Avatar from './Avatar.vue'

const attrs = useAttrs()

const props = defineProps({
  as: { default: 'a' },
  avatarSrc: { default: undefined },
  avatarTone: { default: 'brand' },
  buttonType: { default: 'button' },
  href: { default: '#' },
  initials: { default: 'HL' },
  name: { default: 'Hailey Luna' },
  size: { default: 'sm' },
  state: { default: 'default' },
  tail: { default: undefined },
  tailStatus: { default: undefined },
  tailVariant: { default: undefined },
})

const isLive = computed(() => props.state === 'live')

const classes = computed(() =>
  ['sg-ds-library-scope', 'follow-row', attrs.class].filter(Boolean).join(' ')
)

const resolvedTailStatus = computed(() =>
  props.tailStatus ?? (isLive.value ? 'live' : 'neutral')
)

const resolvedTailVariant = computed(() =>
  props.tailVariant ?? 'plain'
)

const isPrimitiveTail = computed(() =>
  typeof props.tail === 'string' || typeof props.tail === 'number'
)

// tail rendering logic:
// tail == null  → default span ('LIVE' or '5m')
// tail === ''   → nothing
// isPrimitiveTail → span with tail value
// otherwise    → use slot named "tail"
const showDefaultTail = computed(() => props.tail == null)
const showEmptyTail = computed(() => props.tail === '')
const showPrimitiveTail = computed(() => !showDefaultTail.value && !showEmptyTail.value && isPrimitiveTail.value)
const showSlotTail = computed(() => !showDefaultTail.value && !showEmptyTail.value && !isPrimitiveTail.value)
</script>

<template>
  <component
    :is="props.as"
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-size="props.size"
    :data-state="isLive ? 'live' : undefined"
    :href="props.as === 'a' ? props.href : undefined"
    :type="props.as === 'button' ? props.buttonType : undefined"
  >
    <Avatar
      :initials="props.initials"
      :size="props.size === 'md' ? 'md' : 'sm'"
      :src="props.avatarSrc"
      :status="isLive ? 'live' : undefined"
      :tone="props.avatarTone"
    />
    <span class="follow-row-name">{{ props.name }}</span>

    <!-- default tail (null) -->
    <span
      v-if="showDefaultTail"
      class="follow-row-tail"
      :data-status="resolvedTailStatus"
      :data-variant="resolvedTailVariant"
      :data-tone="resolvedTailStatus === 'live' ? 'live' : undefined"
    >{{ isLive ? 'LIVE' : '5m' }}</span>

    <!-- empty string tail → render nothing -->

    <!-- primitive tail (string/number) -->
    <span
      v-else-if="showPrimitiveTail"
      class="follow-row-tail"
      :data-status="resolvedTailStatus"
      :data-variant="resolvedTailVariant"
      :data-tone="resolvedTailStatus === 'live' ? 'live' : undefined"
    >{{ props.tail }}</span>

    <!-- custom tail slot -->
    <slot v-else-if="showSlotTail" name="tail" />
  </component>
</template>
