// frontend/src/libraries/sg-ds-library/components/Media.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryMediaFit = 'cover' | 'contain';
export type SgDsLibraryMediaMask = 'none' | 'fade';
export type SgDsLibraryMediaRounded = 'none' | 'sm' | 'md' | 'lg' | 'pill';
export type SgDsLibraryMediaOverlay = 'none' | 'subtle' | 'muted' | 'inverse' | 'accent' | 'glass';

export type SgDsLibraryMediaProps = HTMLAttributes<HTMLDivElement> & {
  alt?: string;
  aspectRatio?: string;
  backgroundPosition?: CSSProperties['backgroundPosition'];
  backgroundRepeat?: CSSProperties['backgroundRepeat'];
  backgroundSize?: CSSProperties['backgroundSize'];
  children?: ReactNode;
  fit?: SgDsLibraryMediaFit;
  /** Fades the media (image/video) itself toward transparent, independent of any
   *  overlay tint — use it to blend the media into the surrounding background.
   *  `overlayMask` only masks the overlay tint; `mask` masks the media itself. */
  mask?: SgDsLibraryMediaMask;
  maskAngle?: number | string;
  maskEnd?: number | string;
  maskStart?: number | string;
  overlay?: SgDsLibraryMediaOverlay;
  /** Custom overlay color or gradient (any CSS color/gradient). Overrides the
   *  `overlay` variant's preset tint so you control the opacity yourself. When
   *  set, the overlay renders even if `overlay` is `none`. */
  overlayColor?: string;
  overlayGlassBlur?: number | string;
  overlayMask?: SgDsLibraryMediaMask;
  overlayMaskAngle?: number | string;
  overlayMaskEnd?: number | string;
  overlayMaskStart?: number | string;
  /** Custom corner radius as a CSS length (e.g. "20px", "1.5rem"). Overrides the
   *  `rounded` preset when set. */
  radius?: number | string;
  rounded?: SgDsLibraryMediaRounded;
  src?: string;
  videoAutoPlay?: boolean;
  videoControls?: boolean;
  videoLoop?: boolean;
  videoMuted?: boolean;
  videoPlaysInline?: boolean;
};

export function SgDsLibraryMedia(rawProps: SgDsLibraryMediaProps) {
  const {
  alt = '',
  aspectRatio = '16 / 9',
  backgroundPosition = 'center',
  backgroundRepeat = 'no-repeat',
  backgroundSize,
  children,
  className = '',
  fit = 'cover',
  mask = 'none',
  maskAngle = 0,
  maskEnd = 100,
  maskStart = 45,
  overlay = 'none',
  overlayColor,
  overlayGlassBlur,
  overlayMask = 'none',
  overlayMaskAngle = 0,
  overlayMaskEnd = 100,
  overlayMaskStart = 45,
  radius,
  rounded = 'md',
  src,
  style,
  videoAutoPlay = true,
  videoControls = false,
  videoLoop = true,
  videoMuted = true,
  videoPlaysInline = true,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const isVideo = isMediaVideoSource(src);
  const hasOverlay = overlay !== 'none' || Boolean(overlayColor);
  const mediaStyle = {
    aspectRatio,
    ...(hasOverlay && overlayMask !== 'none' ? {
      '--c-media-mask-angle': formatMediaAngle(overlayMaskAngle),
      '--c-media-mask-end': formatMediaPercentage(overlayMaskEnd),
      '--c-media-mask-start': formatMediaPercentage(overlayMaskStart),
    } : null),
    ...(mask !== 'none' ? {
      '--c-media-fade-angle': formatMediaAngle(maskAngle),
      '--c-media-fade-end': formatMediaPercentage(maskEnd),
      '--c-media-fade-start': formatMediaPercentage(maskStart),
    } : null),
    ...(overlayColor ? { '--c-media-overlay-color': overlayColor } : null),
    ...(radius !== undefined && radius !== '' ? { borderRadius: formatMediaLength(radius) } : null),
    ...(overlayGlassBlur !== undefined ? { '--c-media-glass-blur': formatMediaLength(overlayGlassBlur) } : null),
    ...(src && !isVideo ? {
      backgroundImage: formatMediaBackgroundImage(src),
      backgroundPosition,
      backgroundRepeat,
      backgroundSize: backgroundSize ?? fit,
    } : null),
    ...style,
  } as CSSProperties;
  return (
    <div
      {...props}
      aria-label={src && alt && !isVideo ? alt : props['aria-label']}
      className={['sg-ds-library-scope', 'media', `media--fit-${fit}`, `media--rounded-${rounded}`, className].filter(Boolean).join(' ')}
      data-has-media={src ? 'true' : undefined}
      data-overlay={overlay === 'none' ? (overlayColor ? 'custom' : undefined) : overlay}
      data-overlay-color={overlayColor ? 'true' : undefined}
      data-overlay-mask={hasOverlay && overlayMask !== 'none' ? overlayMask : undefined}
      data-mask={mask === 'none' ? undefined : mask}
      role={src && alt && !isVideo ? 'img' : props.role}
      style={mediaStyle}
    >
      {src && isVideo ? (
        <video
          aria-label={alt || undefined}
          autoPlay={videoAutoPlay}
          className="media-video"
          controls={videoControls}
          loop={videoLoop}
          muted={videoMuted}
          playsInline={videoPlaysInline}
          src={src}
        />
      ) : null}
      {children ?? (!src ? <span className="media-placeholder" /> : null)}
      {hasOverlay ? <span aria-hidden="true" className="media-overlay" /> : null}
    </div>
  );
}

function formatMediaBackgroundImage(src: string): string {
  return `url("${src.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}")`;
}

function isMediaVideoSource(src: string | undefined): src is string {
  const value = src?.trim() ?? '';
  const path = value.split(/[?#]/, 1)[0].toLowerCase();
  return value.toLowerCase().startsWith('data:video/') || /\.(?:webm|mp4|m4v|mov|ogv|ogg)$/.test(path);
}

function formatMediaAngle(value: number | string): string {
  const text = String(value).trim();
  return /[a-z)]$/i.test(text) ? text : `${text}deg`;
}

function formatMediaPercentage(value: number | string): string {
  const text = String(value).trim();
  return text.endsWith('%') ? text : `${text}%`;
}

function formatMediaLength(value: number | string): string {
  const text = String(value).trim();
  if (!text) return '0px';
  return /[a-z%)]$/i.test(text) ? text : `${text}px`;
}

export default SgDsLibraryMedia;

// frontend/src/components/Media.vue
<script setup>
import { computed, useAttrs } from 'vue'

const attrs = useAttrs()

const props = defineProps({
  alt: { default: '' },
  aspectRatio: { default: '16 / 9' },
  backgroundPosition: { default: 'center' },
  backgroundRepeat: { default: 'no-repeat' },
  backgroundSize: { default: undefined },
  fit: { default: 'cover' },
  mask: { default: 'none' },
  maskAngle: { default: 0 },
  maskEnd: { default: 100 },
  maskStart: { default: 45 },
  overlay: { default: 'none' },
  overlayColor: { default: undefined },
  overlayGlassBlur: { default: undefined },
  overlayMask: { default: 'none' },
  overlayMaskAngle: { default: 0 },
  overlayMaskEnd: { default: 100 },
  overlayMaskStart: { default: 45 },
  radius: { default: undefined },
  rounded: { default: 'md' },
  src: { default: undefined },
  videoAutoPlay: { default: true },
  videoControls: { default: false },
  videoLoop: { default: true },
  videoMuted: { default: true },
  videoPlaysInline: { default: true },
})

function formatMediaBackgroundImage(src) {
  return `url("${src.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}")`
}

function isMediaVideoSource(src) {
  const value = src?.trim() ?? ''
  const path = value.split(/[?#]/, 1)[0].toLowerCase()
  return value.toLowerCase().startsWith('data:video/') || /\.(?:webm|mp4|m4v|mov|ogv|ogg)$/.test(path)
}

function formatMediaAngle(value) {
  const text = String(value).trim()
  return /[a-z)]$/i.test(text) ? text : `${text}deg`
}

function formatMediaPercentage(value) {
  const text = String(value).trim()
  return text.endsWith('%') ? text : `${text}%`
}

function formatMediaLength(value) {
  const text = String(value).trim()
  if (!text) return '0px'
  return /[a-z%)]$/i.test(text) ? text : `${text}px`
}

const isVideo = computed(() => isMediaVideoSource(props.src))
const hasOverlay = computed(() => props.overlay !== 'none' || Boolean(props.overlayColor))

const classes = computed(() =>
  ['sg-ds-library-scope', 'media', `media--fit-${props.fit}`, `media--rounded-${props.rounded}`, attrs.class]
    .filter(Boolean)
    .join(' ')
)

const mediaStyle = computed(() => {
  const style = {}
  style.aspectRatio = props.aspectRatio
  if (hasOverlay.value && props.overlayMask !== 'none') {
    style['--c-media-mask-angle'] = formatMediaAngle(props.overlayMaskAngle)
    style['--c-media-mask-end'] = formatMediaPercentage(props.overlayMaskEnd)
    style['--c-media-mask-start'] = formatMediaPercentage(props.overlayMaskStart)
  }
  if (props.mask !== 'none') {
    style['--c-media-fade-angle'] = formatMediaAngle(props.maskAngle)
    style['--c-media-fade-end'] = formatMediaPercentage(props.maskEnd)
    style['--c-media-fade-start'] = formatMediaPercentage(props.maskStart)
  }
  if (props.overlayColor) {
    style['--c-media-overlay-color'] = props.overlayColor
  }
  if (props.radius !== undefined && props.radius !== '') {
    style.borderRadius = formatMediaLength(props.radius)
  }
  if (props.overlayGlassBlur !== undefined) {
    style['--c-media-glass-blur'] = formatMediaLength(props.overlayGlassBlur)
  }
  if (props.src && !isVideo.value) {
    style.backgroundImage = formatMediaBackgroundImage(props.src)
    style.backgroundPosition = props.backgroundPosition
    style.backgroundRepeat = props.backgroundRepeat
    style.backgroundSize = props.backgroundSize ?? props.fit
  }
  if (attrs.style) {
    Object.assign(style, attrs.style)
  }
  return style
})

const ariaLabel = computed(() =>
  props.src && props.alt && !isVideo.value ? props.alt : attrs['aria-label']
)

const role = computed(() =>
  props.src && props.alt && !isVideo.value ? 'img' : attrs.role
)

const dataOverlay = computed(() => {
  if (props.overlay !== 'none') return props.overlay
  if (props.overlayColor) return 'custom'
  return undefined
})
</script>

<template>
  <div
    v-bind="{ ...($attrs), class: undefined, style: undefined, 'aria-label': undefined, role: undefined }"
    :aria-label="ariaLabel"
    :class="classes"
    :style="mediaStyle"
    :role="role"
    :data-has-media="props.src ? 'true' : undefined"
    :data-overlay="dataOverlay"
    :data-overlay-color="props.overlayColor ? 'true' : undefined"
    :data-overlay-mask="hasOverlay && props.overlayMask !== 'none' ? props.overlayMask : undefined"
    :data-mask="props.mask === 'none' ? undefined : props.mask"
  >
    <video
      v-if="props.src && isVideo"
      :aria-label="props.alt || undefined"
      :autoplay="props.videoAutoPlay"
      class="media-video"
      :controls="props.videoControls"
      :loop="props.videoLoop"
      :muted="props.videoMuted"
      :playsinline="props.videoPlaysInline"
      :src="props.src"
    />
    <slot v-if="$slots.default" />
    <span v-else-if="!props.src" class="media-placeholder" />
    <span v-if="hasOverlay" aria-hidden="true" class="media-overlay" />
  </div>
</template>
