// frontend/src/libraries/sg-ds-library/components/ReplyComment.tsx
import type { ReactNode } from 'react';
import { SgDsLibraryComment, type SgDsLibraryCommentProps } from './Comment';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryReplyCommentProps = SgDsLibraryCommentProps & {
  replyTo?: ReactNode;
  showConnector?: boolean;
};

export function SgDsLibraryReplyComment(rawProps: SgDsLibraryReplyCommentProps) {
  const {
    authorMeta,
    className = '',
    replyTo,
    showConnector = true,
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const resolvedAuthorMeta = authorMeta ?? (replyTo ? <span className="reply-comment-target">@{replyTo}에게 답글</span> : undefined);

  return (
    <SgDsLibraryComment
      {...props}
      authorMeta={resolvedAuthorMeta}
      className={['reply-comment', className].filter(Boolean).join(' ')}
      data-reply-connector={showConnector || undefined}
    />
  );
}

export default SgDsLibraryReplyComment;

// frontend/src/components/ReplyComment.vue
<script setup>
import { computed } from 'vue'
import Comment from './Comment.vue'

const props = defineProps({
  author: { default: 'User' },
  authorMeta: { default: undefined },
  avatarSrc: { default: undefined },
  avatarTone: { default: 'brand' },
  body: { default: undefined },
  comment: { default: undefined },
  initials: { default: 'U' },
  liked: { default: false },
  likeCount: { default: undefined },
  pinned: { default: false },
  replyCount: { default: undefined },
  time: { default: undefined },
  verified: { default: false },
  replyTo: { default: undefined },
  showConnector: { default: true },
  class: { default: '' },
})

const resolvedAuthorMeta = computed(() => {
  return props.authorMeta ?? (props.replyTo ? `@${props.replyTo}에게 답글` : undefined)
})

const resolvedClass = computed(() =>
  ['reply-comment', props.class].filter(Boolean).join(' ')
)
</script>

<template>
  <Comment
    :author="props.author"
    :author-meta="resolvedAuthorMeta"
    :avatar-src="props.avatarSrc"
    :avatar-tone="props.avatarTone"
    :body="props.body"
    :comment="props.comment"
    :initials="props.initials"
    :liked="props.liked"
    :like-count="props.likeCount"
    :pinned="props.pinned"
    :reply-count="props.replyCount"
    :time="props.time"
    :verified="props.verified"
    :class="resolvedClass"
    :data-reply-connector="props.showConnector || undefined"
  />
</template>
