// frontend/src/libraries/sg-ds-library/components/SectionTitle.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryButton, type SgDsLibraryButtonSize, type SgDsLibraryButtonVariant } from './Button';
import { SgDsLibraryIcon } from './Icon';
import {
  SgDsLibraryText,
  type SgDsLibraryTextAs,
  type SgDsLibraryTextTone,
  type SgDsLibraryTextVariant,
  type SgDsLibraryTextWeight,
} from './Text';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibrarySectionTitleAs = 'header' | 'div' | 'section';
export type SgDsLibrarySectionTitleAlign = 'start' | 'center';
export type SgDsLibrarySectionTitleIconTone =
  | 'brand'
  | 'purple'
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'neutral'
  | 'none';
export type SgDsLibrarySectionTitleIconPosition = 'leading' | 'trailing';
export type SgDsLibrarySectionTitleGroupAlign = 'start' | 'end';

export type SgDsLibrarySectionTitleProps = Omit<HTMLAttributes<HTMLElement>, 'title'> & {
  action1Icon?: string;
  action1IconPosition?: SgDsLibrarySectionTitleIconPosition;
  action1Label?: string;
  action1Variant?: SgDsLibraryButtonVariant;
  action2Icon?: string;
  action2IconPosition?: SgDsLibrarySectionTitleIconPosition;
  action2Label?: string;
  action2Variant?: SgDsLibraryButtonVariant;
  actionSize?: SgDsLibraryButtonSize;
  align?: SgDsLibrarySectionTitleAlign;
  as?: SgDsLibrarySectionTitleAs;
  children?: ReactNode;
  icon?: string;
  iconAction1Icon?: string;
  iconAction1Label?: string;
  iconAction2Icon?: string;
  iconAction2Label?: string;
  iconActionVariant?: SgDsLibraryButtonVariant;
  iconColor?: string;
  iconColorToken?: string;
  iconColorTokenCollection?: string;
  iconLabel?: string;
  iconTone?: SgDsLibrarySectionTitleIconTone;
  showIcon?: boolean;
  subtitle?: ReactNode;
  subtitleTone?: SgDsLibraryTextTone;
  subtitleVariant?: SgDsLibraryTextVariant;
  title?: ReactNode;
  titleAs?: SgDsLibraryTextAs;
  titleVariant?: SgDsLibraryTextVariant;
  titleWeight?: SgDsLibraryTextWeight;
  wrapActions?: boolean;
};

export function SgDsLibrarySectionTitle(rawProps: SgDsLibrarySectionTitleProps) {
  const {
    action1Icon = '',
    action1IconPosition = 'trailing',
    action1Label = '',
    action1Variant = 'soft',
    action2Icon = '',
    action2IconPosition = 'trailing',
    action2Label = '',
    action2Variant = 'soft',
    actionSize = 'sm',
    align = 'start',
    as: Component = 'header',
    children,
    className = '',
    icon = 'sparkles',
    iconAction1Icon = '',
    iconAction1Label = '',
    iconAction2Icon = '',
    iconAction2Label = '',
    iconActionVariant = 'soft',
    iconColor = '',
    iconColorToken = '',
    iconColorTokenCollection = '',
    iconLabel = '',
    iconTone = 'brand',
    showIcon = true,
    subtitle = '',
    subtitleTone = 'tertiary',
    subtitleVariant = 'body-sm',
    title = '섹션 타이틀',
    titleAs = 'h3',
    titleVariant = 'heading-3',
    titleWeight = 'bold',
    wrapActions = true,
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const showMainIcon = showIcon && Boolean(icon);
  const hasTitle = title !== null && title !== undefined && title !== '';
  const hasSubtitle = subtitle !== null && subtitle !== undefined && subtitle !== '';
  const hasTextAction1 = Boolean(action1Label);
  const hasTextAction2 = Boolean(action2Label);
  const hasIconAction1 = Boolean(iconAction1Icon && iconAction1Label);
  const hasIconAction2 = Boolean(iconAction2Icon && iconAction2Label);
  const hasActions = hasTextAction1 || hasTextAction2 || hasIconAction1 || hasIconAction2;
  const hasCustomGroups = Boolean(children);
  const resolvedIconColor = formatSectionTitleTokenReference(iconColorTokenCollection, iconColorToken) ?? iconColor;
  const iconStyle = resolvedIconColor
    ? ({ '--c-section-title-icon-color': resolvedIconColor } as CSSProperties)
    : undefined;

  return (
    <Component
      {...props}
      className={['sg-ds-library-scope', 'section-title', className].filter(Boolean).join(' ')}
      data-align={align}
      data-custom-actions={hasCustomGroups || undefined}
      data-wrap-actions={wrapActions || undefined}
    >
      <div className="section-title-copy">
        <div className="section-title-main">
          {showMainIcon ? (
            <span
              aria-hidden={iconLabel ? undefined : true}
              aria-label={iconLabel || undefined}
              className="section-title-icon"
              data-tone={iconTone}
              role={iconLabel ? 'img' : undefined}
              style={iconStyle}
            >
              <SgDsLibraryIcon name={icon} size="1em" />
            </span>
          ) : null}
          {hasTitle ? (
            <SgDsLibraryText
              as={titleAs}
              className="section-title-heading"
              variant={titleVariant}
              weight={titleWeight}
            >
              {title}
            </SgDsLibraryText>
          ) : null}
        </div>
        {hasSubtitle ? (
          <SgDsLibraryText
            as="span"
            className="section-title-subtitle"
            tone={subtitleTone}
            variant={subtitleVariant}
          >
            {subtitle}
          </SgDsLibraryText>
        ) : null}
      </div>

      {hasCustomGroups ? (
        <div className="section-title-groups">
          {children}
        </div>
      ) : hasActions ? (
        <div className="section-title-actions">
          {hasTextAction1 ? (
            <SgDsLibraryButton
              leadingIcon={action1IconPosition === 'leading' ? action1Icon : undefined}
              size={actionSize}
              trailingIcon={action1IconPosition === 'trailing' ? action1Icon : undefined}
              variant={action1Variant}
            >
              {action1Label}
            </SgDsLibraryButton>
          ) : null}
          {hasTextAction2 ? (
            <SgDsLibraryButton
              leadingIcon={action2IconPosition === 'leading' ? action2Icon : undefined}
              size={actionSize}
              trailingIcon={action2IconPosition === 'trailing' ? action2Icon : undefined}
              variant={action2Variant}
            >
              {action2Label}
            </SgDsLibraryButton>
          ) : null}
          {hasIconAction1 ? (
            <SgDsLibraryButton
              aria-label={iconAction1Label}
              iconOnly
              leadingIcon={iconAction1Icon}
              shape="pill"
              size={actionSize}
              variant={iconActionVariant}
            />
          ) : null}
          {hasIconAction2 ? (
            <SgDsLibraryButton
              aria-label={iconAction2Label}
              iconOnly
              leadingIcon={iconAction2Icon}
              shape="pill"
              size={actionSize}
              variant={iconActionVariant}
            />
          ) : null}
        </div>
      ) : null}
    </Component>
  );
}

export type SgDsLibrarySectionTitleGroupProps = HTMLAttributes<HTMLDivElement> & {
  align?: SgDsLibrarySectionTitleGroupAlign;
  children?: ReactNode;
};

export function SgDsLibrarySectionTitleGroup(rawProps: SgDsLibrarySectionTitleGroupProps) {
  const {
    align = 'start',
    children,
    className = '',
    ...props
  } = resolveWorkbenchModeProps(rawProps);

  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'section-title-group', className].filter(Boolean).join(' ')}
      data-align={align === 'end' ? 'end' : undefined}
    >
      {children}
    </div>
  );
}

function formatSectionTitleTokenReference(collectionId: string | undefined, tokenId: string | undefined): string | null {
  const collection = collectionId?.trim();
  const token = tokenId?.trim();
  return collection && token ? `var(--ds-token-${collection}-${token})` : null;
}

export default SgDsLibrarySectionTitle;

// frontend/src/components/SectionTitle.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Button from './Button.vue'
import Icon from './Icon.vue'
import Text from './Text.vue'

const attrs = useAttrs()

const props = defineProps({
  action1Icon: { default: '' },
  action1IconPosition: { default: 'trailing' },
  action1Label: { default: '' },
  action1Variant: { default: 'soft' },
  action2Icon: { default: '' },
  action2IconPosition: { default: 'trailing' },
  action2Label: { default: '' },
  action2Variant: { default: 'soft' },
  actionSize: { default: 'sm' },
  align: { default: 'start' },
  as: { default: 'header' },
  icon: { default: 'sparkles' },
  iconAction1Icon: { default: '' },
  iconAction1Label: { default: '' },
  iconAction2Icon: { default: '' },
  iconAction2Label: { default: '' },
  iconActionVariant: { default: 'soft' },
  iconColor: { default: '' },
  iconColorToken: { default: '' },
  iconColorTokenCollection: { default: '' },
  iconLabel: { default: '' },
  iconTone: { default: 'brand' },
  showIcon: { default: true },
  subtitle: { default: '' },
  subtitleTone: { default: 'tertiary' },
  subtitleVariant: { default: 'body-sm' },
  title: { default: '섹션 타이틀' },
  titleAs: { default: 'h3' },
  titleVariant: { default: 'heading-3' },
  titleWeight: { default: 'bold' },
  wrapActions: { default: true },
})

defineOptions({ inheritAttrs: false })

const showMainIcon = computed(() => props.showIcon && Boolean(props.icon))
const hasTitle = computed(() => props.title !== null && props.title !== undefined && props.title !== '')
const hasSubtitle = computed(() => props.subtitle !== null && props.subtitle !== undefined && props.subtitle !== '')
const hasTextAction1 = computed(() => Boolean(props.action1Label))
const hasTextAction2 = computed(() => Boolean(props.action2Label))
const hasIconAction1 = computed(() => Boolean(props.iconAction1Icon && props.iconAction1Label))
const hasIconAction2 = computed(() => Boolean(props.iconAction2Icon && props.iconAction2Label))
const hasActions = computed(() => hasTextAction1.value || hasTextAction2.value || hasIconAction1.value || hasIconAction2.value)

const resolvedIconColor = computed(() => {
  const collection = props.iconColorTokenCollection?.trim()
  const token = props.iconColorToken?.trim()
  return (collection && token) ? `var(--ds-token-${collection}-${token})` : props.iconColor
})

const iconStyle = computed(() => resolvedIconColor.value
  ? { '--c-section-title-icon-color': resolvedIconColor.value }
  : undefined
)

const classes = computed(() =>
  ['sg-ds-library-scope', 'section-title', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <component
    :is="props.as"
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-align="props.align"
    :data-custom-actions="$slots.default ? true : undefined"
    :data-wrap-actions="props.wrapActions ? true : undefined"
  >
    <div class="section-title-copy">
      <div class="section-title-main">
        <span
          v-if="showMainIcon"
          :aria-hidden="props.iconLabel ? undefined : true"
          :aria-label="props.iconLabel || undefined"
          class="section-title-icon"
          :data-tone="props.iconTone"
          :role="props.iconLabel ? 'img' : undefined"
          :style="iconStyle"
        >
          <Icon :name="props.icon" size="1em" />
        </span>
        <Text
          v-if="hasTitle"
          :as="props.titleAs"
          class="section-title-heading"
          :variant="props.titleVariant"
          :weight="props.titleWeight"
        >
          {{ props.title }}
        </Text>
      </div>
      <Text
        v-if="hasSubtitle"
        as="span"
        class="section-title-subtitle"
        :tone="props.subtitleTone"
        :variant="props.subtitleVariant"
      >
        {{ props.subtitle }}
      </Text>
    </div>

    <div v-if="$slots.default" class="section-title-groups">
      <slot />
    </div>
    <div v-else-if="hasActions" class="section-title-actions">
      <Button
        v-if="hasTextAction1"
        :leading-icon="props.action1IconPosition === 'leading' ? props.action1Icon : undefined"
        :size="props.actionSize"
        :trailing-icon="props.action1IconPosition === 'trailing' ? props.action1Icon : undefined"
        :variant="props.action1Variant"
      >
        {{ props.action1Label }}
      </Button>
      <Button
        v-if="hasTextAction2"
        :leading-icon="props.action2IconPosition === 'leading' ? props.action2Icon : undefined"
        :size="props.actionSize"
        :trailing-icon="props.action2IconPosition === 'trailing' ? props.action2Icon : undefined"
        :variant="props.action2Variant"
      >
        {{ props.action2Label }}
      </Button>
      <Button
        v-if="hasIconAction1"
        :aria-label="props.iconAction1Label"
        :icon-only="true"
        :leading-icon="props.iconAction1Icon"
        shape="pill"
        :size="props.actionSize"
        :variant="props.iconActionVariant"
      />
      <Button
        v-if="hasIconAction2"
        :aria-label="props.iconAction2Label"
        :icon-only="true"
        :leading-icon="props.iconAction2Icon"
        shape="pill"
        :size="props.actionSize"
        :variant="props.iconActionVariant"
      />
    </div>
  </component>
</template>
