// frontend/src/libraries/sg-ds-library/components/Stack.tsx
import { useCallback, useEffect, useRef, useState, type CSSProperties, type HTMLAttributes, type ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryStackAlign = 'stretch' | 'start' | 'center' | 'end';
export type SgDsLibraryStackAs = 'div' | 'main' | 'section' | 'article' | 'aside' | 'header' | 'footer' | 'nav';
export type SgDsLibraryStackBackground = 'none' | 'surface' | 'soft' | 'subtle' | 'muted' | 'inverse' | 'accent' | 'glass';
export type SgDsLibraryStackDirection = 'column' | 'row';
export type SgDsLibraryStackGap = 'none' | 'xxs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
export type SgDsLibraryStackJustify = 'start' | 'center' | 'end' | 'between';
export type SgDsLibraryStackMask = 'none' | 'fade';
export type SgDsLibraryStackOverflow = 'visible' | 'hidden' | 'auto' | 'scroll' | 'clip';
export type SgDsLibraryStackPadding = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
export type SgDsLibraryStackPosition = 'static' | 'relative' | 'sticky';
export type SgDsLibraryStackRadius = 'none' | 'sm' | 'md' | 'lg' | 'pill';

export type SgDsLibraryStackProps = HTMLAttributes<HTMLElement> & {
  align?: SgDsLibraryStackAlign;
  as?: SgDsLibraryStackAs;
  background?: SgDsLibraryStackBackground;
  bottom?: string;
  children?: ReactNode;
  direction?: SgDsLibraryStackDirection;
  flex?: string;
  gap?: SgDsLibraryStackGap;
  glassBlur?: number | string;
  height?: string;
  justify?: SgDsLibraryStackJustify;
  left?: string;
  marginBlock?: string;
  marginBottom?: string;
  marginInline?: string;
  marginLeft?: string;
  marginRight?: string;
  marginTop?: string;
  mask?: SgDsLibraryStackMask;
  maskAngle?: number | string;
  maskEnd?: number | string;
  maskStart?: number | string;
  maxHeight?: string;
  maxWidth?: string;
  minHeight?: string;
  minWidth?: string;
  overflow?: SgDsLibraryStackOverflow;
  overflowX?: SgDsLibraryStackOverflow;
  overflowY?: SgDsLibraryStackOverflow;
  padding?: SgDsLibraryStackPadding;
  paddingBlock?: string;
  paddingBottom?: string;
  paddingInline?: string;
  paddingLeft?: string;
  paddingRight?: string;
  paddingTop?: string;
  position?: SgDsLibraryStackPosition;
  radius?: SgDsLibraryStackRadius;
  right?: string;
  scrollFade?: boolean;
  textAlign?: CSSProperties['textAlign'];
  top?: string;
  width?: string;
  wrap?: boolean;
  zIndex?: string;
};

const STACK_GAP_VALUES: Record<string, string> = {
  none: '0px',
  xxs: 'var(--c-stack-gap-xxs)',
  xs: 'var(--c-stack-gap-xs)',
  sm: 'var(--c-stack-gap-sm)',
  md: 'var(--c-stack-gap-md)',
  lg: 'var(--c-stack-gap-lg)',
  xl: 'var(--c-stack-gap-xl)',
  '2xl': 'var(--c-stack-gap-2xl)',
};

const STACK_PADDING_VALUES: Record<string, string> = {
  none: '0px',
  xs: 'var(--c-stack-padding-xs)',
  sm: 'var(--c-stack-padding-sm)',
  md: 'var(--c-stack-padding-md)',
  lg: 'var(--c-stack-padding-lg)',
  xl: 'var(--c-stack-padding-xl)',
};

type StackStyle = CSSProperties & {
  '--c-stack-gap'?: string;
  '--c-stack-glass-blur'?: string;
  '--c-stack-mask-angle'?: string;
  '--c-stack-mask-end'?: string;
  '--c-stack-mask-start'?: string;
  '--c-stack-padding'?: string;
};

type StackScrollFadeEdges = {
  bottom: boolean;
  left: boolean;
  right: boolean;
  top: boolean;
};

const EMPTY_STACK_SCROLL_FADE_EDGES: StackScrollFadeEdges = {
  bottom: false,
  left: false,
  right: false,
  top: false,
};

export function SgDsLibraryStack(rawProps: SgDsLibraryStackProps) {
  const {
    align = 'stretch',
    as = 'div',
    background = 'none',
    bottom,
    children,
    className = '',
    direction = 'column',
    flex,
    gap = 'md',
    glassBlur,
    height,
    justify = 'start',
    left,
    marginBlock,
    marginBottom,
    marginInline,
    marginLeft,
    marginRight,
    marginTop,
    mask = 'none',
    maskAngle,
    maskEnd,
    maskStart,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    overflow,
    overflowX,
    overflowY,
    padding = 'none',
    paddingBlock,
    paddingBottom,
    paddingInline,
    paddingLeft,
    paddingRight,
    paddingTop,
    position = 'static',
    radius = 'none',
    right,
    scrollFade = false,
    style,
    textAlign,
    top,
    width,
    wrap = false,
    zIndex,
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const stackRef = useRef<HTMLElement | null>(null);
  const [scrollFadeEdges, setScrollFadeEdges] = useState<StackScrollFadeEdges>(EMPTY_STACK_SCROLL_FADE_EDGES);
  const setStackNode = useCallback((node: HTMLElement | null) => {
    stackRef.current = node;
  }, []);
  const customStyle: StackStyle = {};
  const resolvedGap = resolveStackValue(gap, STACK_GAP_VALUES);
  const resolvedPadding = resolveStackValue(padding, STACK_PADDING_VALUES);

  if (!isNamedStackValue(gap, STACK_GAP_VALUES)) {
    customStyle['--c-stack-gap'] = resolvedGap;
  }
  if (!isNamedStackValue(padding, STACK_PADDING_VALUES)) {
    customStyle['--c-stack-padding'] = resolvedPadding;
  }
  if (mask !== 'none') {
    if (maskAngle !== undefined) {
      customStyle['--c-stack-mask-angle'] = formatStackAngle(maskAngle);
    }
    if (maskStart !== undefined) {
      customStyle['--c-stack-mask-start'] = formatStackPercentage(maskStart);
    }
    if (maskEnd !== undefined) {
      customStyle['--c-stack-mask-end'] = formatStackPercentage(maskEnd);
    }
  }
  if (glassBlur !== undefined) {
    customStyle['--c-stack-glass-blur'] = formatStackLength(glassBlur);
  }
  applyStackLength(customStyle, 'width', width);
  applyStackLength(customStyle, 'minWidth', minWidth);
  applyStackLength(customStyle, 'maxWidth', maxWidth);
  applyStackLength(customStyle, 'height', height);
  applyStackLength(customStyle, 'minHeight', minHeight);
  applyStackLength(customStyle, 'maxHeight', maxHeight);
  applyStackValue(customStyle, 'flex', flex);
  if (position !== 'static') {
    customStyle.position = position;
  }
  applyStackLength(customStyle, 'top', top);
  applyStackLength(customStyle, 'right', right);
  applyStackLength(customStyle, 'bottom', bottom);
  applyStackLength(customStyle, 'left', left);
  applyStackValue(customStyle, 'zIndex', zIndex);
  if (overflow && overflow !== 'visible') {
    customStyle.overflow = overflow;
  }
  if (overflowX && overflowX !== 'visible') {
    customStyle.overflowX = overflowX;
  }
  if (overflowY && overflowY !== 'visible') {
    customStyle.overflowY = overflowY;
  }
  applyStackLength(customStyle, 'marginTop', marginTop);
  applyStackLength(customStyle, 'marginRight', marginRight);
  applyStackLength(customStyle, 'marginBottom', marginBottom);
  applyStackLength(customStyle, 'marginLeft', marginLeft);
  applyStackValue(customStyle, 'marginInline', marginInline);
  applyStackValue(customStyle, 'marginBlock', marginBlock);
  applyStackLength(customStyle, 'paddingTop', paddingTop);
  applyStackLength(customStyle, 'paddingRight', paddingRight);
  applyStackLength(customStyle, 'paddingBottom', paddingBottom);
  applyStackLength(customStyle, 'paddingLeft', paddingLeft);
  applyStackValue(customStyle, 'paddingInline', paddingInline);
  applyStackValue(customStyle, 'paddingBlock', paddingBlock);
  if (textAlign) {
    customStyle.textAlign = textAlign;
  }
  const stackStyle = Object.keys(customStyle).length > 0
    ? ({ ...customStyle, ...style } as CSSProperties)
    : style;
  const Component = as;

  useEffect(() => {
    if (!scrollFade) {
      setScrollFadeEdges((current) => (
        areStackScrollFadeEdgesEqual(current, EMPTY_STACK_SCROLL_FADE_EDGES)
          ? current
          : EMPTY_STACK_SCROLL_FADE_EDGES
      ));
      return;
    }

    const node = stackRef.current;
    if (!node) return;

    let frame = 0;
    const updateScrollFadeEdges = () => {
      if (frame) {
        window.cancelAnimationFrame(frame);
      }
      frame = window.requestAnimationFrame(() => {
        frame = 0;
        const nextEdges = getStackScrollFadeEdges(node);
        setScrollFadeEdges((current) => (
          areStackScrollFadeEdgesEqual(current, nextEdges) ? current : nextEdges
        ));
      });
    };

    updateScrollFadeEdges();
    node.addEventListener('scroll', updateScrollFadeEdges, { passive: true });
    const resizeObserver = typeof ResizeObserver !== 'undefined'
      ? new ResizeObserver(updateScrollFadeEdges)
      : null;
    resizeObserver?.observe(node);
    Array.from(node.children).forEach((child) => resizeObserver?.observe(child));
    window.addEventListener('resize', updateScrollFadeEdges);

    return () => {
      if (frame) {
        window.cancelAnimationFrame(frame);
      }
      node.removeEventListener('scroll', updateScrollFadeEdges);
      resizeObserver?.disconnect();
      window.removeEventListener('resize', updateScrollFadeEdges);
    };
  }, [as, children, height, maxHeight, maxWidth, minHeight, minWidth, overflow, overflowX, overflowY, scrollFade, style, width]);

  return (
    <Component
      {...props}
      ref={setStackNode as never}
      className={['sg-ds-library-scope', 'stack', className].filter(Boolean).join(' ')}
      data-align={align === 'stretch' ? undefined : align}
      data-background={background === 'none' ? undefined : background}
      data-direction={direction === 'column' ? undefined : direction}
      data-gap={isNamedStackValue(gap, STACK_GAP_VALUES) ? gap : undefined}
      data-justify={justify === 'start' ? undefined : justify}
      data-mask={mask === 'none' ? undefined : mask}
      data-padding={isNamedStackValue(padding, STACK_PADDING_VALUES) ? padding : undefined}
      data-radius={radius === 'none' ? undefined : radius}
      data-scroll-fade={scrollFade ? 'true' : undefined}
      data-scroll-fade-bottom={scrollFade && scrollFadeEdges.bottom ? 'true' : undefined}
      data-scroll-fade-left={scrollFade && scrollFadeEdges.left ? 'true' : undefined}
      data-scroll-fade-right={scrollFade && scrollFadeEdges.right ? 'true' : undefined}
      data-scroll-fade-top={scrollFade && scrollFadeEdges.top ? 'true' : undefined}
      data-wrap={wrap ? 'true' : undefined}
      style={stackStyle}
    >
      {children}
    </Component>
  );
}

function resolveStackValue(value: string, values: Record<string, string>): string {
  return values[value] ?? value;
}

function isNamedStackValue(value: string, values: Record<string, string>): boolean {
  return Object.prototype.hasOwnProperty.call(values, value);
}

function getStackScrollFadeEdges(node: HTMLElement): StackScrollFadeEdges {
  const computedStyle = window.getComputedStyle(node);
  const maxScrollTop = Math.max(0, node.scrollHeight - node.clientHeight);
  const maxScrollLeft = Math.max(0, node.scrollWidth - node.clientWidth);
  const canScrollY = maxScrollTop > 1 && isScrollableStackOverflow(computedStyle.overflowY);
  const canScrollX = maxScrollLeft > 1 && isScrollableStackOverflow(computedStyle.overflowX);
  const scrollTop = Math.max(0, node.scrollTop);
  const scrollLeft = Math.max(0, node.scrollLeft);

  return {
    bottom: canScrollY && scrollTop < maxScrollTop - 1,
    left: canScrollX && scrollLeft > 1,
    right: canScrollX && scrollLeft < maxScrollLeft - 1,
    top: canScrollY && scrollTop > 1,
  };
}

function isScrollableStackOverflow(value: string): boolean {
  return value === 'auto' || value === 'scroll' || value === 'overlay';
}

function areStackScrollFadeEdgesEqual(left: StackScrollFadeEdges, right: StackScrollFadeEdges): boolean {
  return (
    left.bottom === right.bottom &&
    left.left === right.left &&
    left.right === right.right &&
    left.top === right.top
  );
}

function formatStackAngle(value: number | string): string {
  const text = String(value).trim();
  return /[a-z)]$/i.test(text) ? text : `${text}deg`;
}

function formatStackPercentage(value: number | string): string {
  const text = String(value).trim();
  return text.endsWith('%') ? text : `${text}%`;
}

function formatStackLength(value: number | string): string {
  const text = String(value).trim();
  if (!text) return '0px';
  return /[a-z%)]$/i.test(text) ? text : `${text}px`;
}

function applyStackLength(style: CSSProperties, key: keyof CSSProperties, value: string | undefined): void {
  if (value === undefined || value.trim() === '') return;
  style[key] = formatStackLength(value) as never;
}

function applyStackValue(style: CSSProperties, key: keyof CSSProperties, value: string | undefined): void {
  if (value === undefined || value.trim() === '') return;
  style[key] = value as never;
}

export default SgDsLibraryStack;

// frontend/src/components/Stack.vue
<script setup>
import { ref, computed, onMounted, onUnmounted, watch, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  align: { default: 'stretch' },
  as: { default: 'div' },
  background: { default: 'none' },
  bottom: { default: undefined },
  direction: { default: 'column' },
  flex: { default: undefined },
  gap: { default: 'md' },
  glassBlur: { default: undefined },
  height: { default: undefined },
  justify: { default: 'start' },
  left: { default: undefined },
  marginBlock: { default: undefined },
  marginBottom: { default: undefined },
  marginInline: { default: undefined },
  marginLeft: { default: undefined },
  marginRight: { default: undefined },
  marginTop: { default: undefined },
  mask: { default: 'none' },
  maskAngle: { default: undefined },
  maskEnd: { default: undefined },
  maskStart: { default: undefined },
  maxHeight: { default: undefined },
  maxWidth: { default: undefined },
  minHeight: { default: undefined },
  minWidth: { default: undefined },
  overflow: { default: undefined },
  overflowX: { default: undefined },
  overflowY: { default: undefined },
  padding: { default: 'none' },
  paddingBlock: { default: undefined },
  paddingBottom: { default: undefined },
  paddingInline: { default: undefined },
  paddingLeft: { default: undefined },
  paddingRight: { default: undefined },
  paddingTop: { default: undefined },
  position: { default: 'static' },
  radius: { default: 'none' },
  right: { default: undefined },
  scrollFade: { default: false },
  textAlign: { default: undefined },
  top: { default: undefined },
  width: { default: undefined },
  wrap: { default: false },
  zIndex: { default: undefined },
})

const STACK_GAP_VALUES = {
  none: '0px',
  xxs: 'var(--c-stack-gap-xxs)',
  xs: 'var(--c-stack-gap-xs)',
  sm: 'var(--c-stack-gap-sm)',
  md: 'var(--c-stack-gap-md)',
  lg: 'var(--c-stack-gap-lg)',
  xl: 'var(--c-stack-gap-xl)',
  '2xl': 'var(--c-stack-gap-2xl)',
}

const STACK_PADDING_VALUES = {
  none: '0px',
  xs: 'var(--c-stack-padding-xs)',
  sm: 'var(--c-stack-padding-sm)',
  md: 'var(--c-stack-padding-md)',
  lg: 'var(--c-stack-padding-lg)',
  xl: 'var(--c-stack-padding-xl)',
}

function resolveStackValue(value, values) {
  return values[value] ?? value
}

function isNamedStackValue(value, values) {
  return Object.prototype.hasOwnProperty.call(values, value)
}

function formatStackAngle(value) {
  const text = String(value).trim()
  return /[a-z)]$/i.test(text) ? text : `${text}deg`
}

function formatStackPercentage(value) {
  const text = String(value).trim()
  return text.endsWith('%') ? text : `${text}%`
}

function formatStackLength(value) {
  const text = String(value).trim()
  if (!text) return '0px'
  return /[a-z%)]$/i.test(text) ? text : `${text}px`
}

function applyStackLength(style, key, value) {
  if (value === undefined || String(value).trim() === '') return
  style[key] = formatStackLength(value)
}

function applyStackValue(style, key, value) {
  if (value === undefined || String(value).trim() === '') return
  style[key] = value
}

const stackStyle = computed(() => {
  const customStyle = {}

  if (!isNamedStackValue(props.gap, STACK_GAP_VALUES)) {
    customStyle['--c-stack-gap'] = resolveStackValue(props.gap, STACK_GAP_VALUES)
  }
  if (!isNamedStackValue(props.padding, STACK_PADDING_VALUES)) {
    customStyle['--c-stack-padding'] = resolveStackValue(props.padding, STACK_PADDING_VALUES)
  }
  if (props.mask !== 'none') {
    if (props.maskAngle !== undefined) {
      customStyle['--c-stack-mask-angle'] = formatStackAngle(props.maskAngle)
    }
    if (props.maskStart !== undefined) {
      customStyle['--c-stack-mask-start'] = formatStackPercentage(props.maskStart)
    }
    if (props.maskEnd !== undefined) {
      customStyle['--c-stack-mask-end'] = formatStackPercentage(props.maskEnd)
    }
  }
  if (props.glassBlur !== undefined) {
    customStyle['--c-stack-glass-blur'] = formatStackLength(props.glassBlur)
  }

  applyStackLength(customStyle, 'width', props.width)
  applyStackLength(customStyle, 'minWidth', props.minWidth)
  applyStackLength(customStyle, 'maxWidth', props.maxWidth)
  applyStackLength(customStyle, 'height', props.height)
  applyStackLength(customStyle, 'minHeight', props.minHeight)
  applyStackLength(customStyle, 'maxHeight', props.maxHeight)
  applyStackValue(customStyle, 'flex', props.flex)

  if (props.position !== 'static') {
    customStyle.position = props.position
  }

  applyStackLength(customStyle, 'top', props.top)
  applyStackLength(customStyle, 'right', props.right)
  applyStackLength(customStyle, 'bottom', props.bottom)
  applyStackLength(customStyle, 'left', props.left)
  applyStackValue(customStyle, 'zIndex', props.zIndex)

  if (props.overflow && props.overflow !== 'visible') {
    customStyle.overflow = props.overflow
  }
  if (props.overflowX && props.overflowX !== 'visible') {
    customStyle.overflowX = props.overflowX
  }
  if (props.overflowY && props.overflowY !== 'visible') {
    customStyle.overflowY = props.overflowY
  }

  applyStackLength(customStyle, 'marginTop', props.marginTop)
  applyStackLength(customStyle, 'marginRight', props.marginRight)
  applyStackLength(customStyle, 'marginBottom', props.marginBottom)
  applyStackLength(customStyle, 'marginLeft', props.marginLeft)
  applyStackValue(customStyle, 'marginInline', props.marginInline)
  applyStackValue(customStyle, 'marginBlock', props.marginBlock)
  applyStackLength(customStyle, 'paddingTop', props.paddingTop)
  applyStackLength(customStyle, 'paddingRight', props.paddingRight)
  applyStackLength(customStyle, 'paddingBottom', props.paddingBottom)
  applyStackLength(customStyle, 'paddingLeft', props.paddingLeft)
  applyStackValue(customStyle, 'paddingInline', props.paddingInline)
  applyStackValue(customStyle, 'paddingBlock', props.paddingBlock)

  if (props.textAlign) {
    customStyle.textAlign = props.textAlign
  }

  const attrStyle = attrs.style ?? {}
  return Object.keys(customStyle).length > 0
    ? { ...customStyle, ...attrStyle }
    : attrStyle
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'stack', attrs.class].filter(Boolean).join(' ')
)

// Scroll fade
const stackRef = ref(null)
const scrollFadeEdges = ref({ bottom: false, left: false, right: false, top: false })

function isScrollableStackOverflow(value) {
  return value === 'auto' || value === 'scroll' || value === 'overlay'
}

function getStackScrollFadeEdges(node) {
  const computedStyle = window.getComputedStyle(node)
  const maxScrollTop = Math.max(0, node.scrollHeight - node.clientHeight)
  const maxScrollLeft = Math.max(0, node.scrollWidth - node.clientWidth)
  const canScrollY = maxScrollTop > 1 && isScrollableStackOverflow(computedStyle.overflowY)
  const canScrollX = maxScrollLeft > 1 && isScrollableStackOverflow(computedStyle.overflowX)
  const scrollTop = Math.max(0, node.scrollTop)
  const scrollLeft = Math.max(0, node.scrollLeft)
  return {
    bottom: canScrollY && scrollTop < maxScrollTop - 1,
    left: canScrollX && scrollLeft > 1,
    right: canScrollX && scrollLeft < maxScrollLeft - 1,
    top: canScrollY && scrollTop > 1,
  }
}

let scrollFadeFrame = 0
let scrollFadeCleanup = null

function setupScrollFade() {
  if (scrollFadeCleanup) {
    scrollFadeCleanup()
    scrollFadeCleanup = null
  }

  if (!props.scrollFade) {
    scrollFadeEdges.value = { bottom: false, left: false, right: false, top: false }
    return
  }

  const node = stackRef.value
  if (!node) return

  const updateScrollFadeEdges = () => {
    if (scrollFadeFrame) {
      window.cancelAnimationFrame(scrollFadeFrame)
    }
    scrollFadeFrame = window.requestAnimationFrame(() => {
      scrollFadeFrame = 0
      scrollFadeEdges.value = getStackScrollFadeEdges(node)
    })
  }

  updateScrollFadeEdges()
  node.addEventListener('scroll', updateScrollFadeEdges, { passive: true })

  const resizeObserver = typeof ResizeObserver !== 'undefined'
    ? new ResizeObserver(updateScrollFadeEdges)
    : null
  resizeObserver?.observe(node)
  Array.from(node.children).forEach((child) => resizeObserver?.observe(child))
  window.addEventListener('resize', updateScrollFadeEdges)

  scrollFadeCleanup = () => {
    if (scrollFadeFrame) {
      window.cancelAnimationFrame(scrollFadeFrame)
    }
    node.removeEventListener('scroll', updateScrollFadeEdges)
    resizeObserver?.disconnect()
    window.removeEventListener('resize', updateScrollFadeEdges)
  }
}

onMounted(() => {
  setupScrollFade()
})

onUnmounted(() => {
  if (scrollFadeCleanup) scrollFadeCleanup()
})

watch(
  () => [
    props.as,
    props.height,
    props.maxHeight,
    props.maxWidth,
    props.minHeight,
    props.minWidth,
    props.overflow,
    props.overflowX,
    props.overflowY,
    props.scrollFade,
    props.width,
  ],
  () => {
    setupScrollFade()
  }
)
</script>

<template>
  <component
    :is="props.as"
    v-bind="{ ...($attrs), class: undefined, style: undefined }"
    ref="stackRef"
    :class="classes"
    :style="stackStyle"
    :data-align="props.align !== 'stretch' ? props.align : undefined"
    :data-background="props.background !== 'none' ? props.background : undefined"
    :data-direction="props.direction !== 'column' ? props.direction : undefined"
    :data-gap="isNamedStackValue(props.gap, STACK_GAP_VALUES) ? props.gap : undefined"
    :data-justify="props.justify !== 'start' ? props.justify : undefined"
    :data-mask="props.mask !== 'none' ? props.mask : undefined"
    :data-padding="isNamedStackValue(props.padding, STACK_PADDING_VALUES) ? props.padding : undefined"
    :data-radius="props.radius !== 'none' ? props.radius : undefined"
    :data-scroll-fade="props.scrollFade ? 'true' : undefined"
    :data-scroll-fade-bottom="props.scrollFade && scrollFadeEdges.bottom ? 'true' : undefined"
    :data-scroll-fade-left="props.scrollFade && scrollFadeEdges.left ? 'true' : undefined"
    :data-scroll-fade-right="props.scrollFade && scrollFadeEdges.right ? 'true' : undefined"
    :data-scroll-fade-top="props.scrollFade && scrollFadeEdges.top ? 'true' : undefined"
    :data-wrap="props.wrap ? 'true' : undefined"
  >
    <slot />
  </component>
</template>
