// frontend/src/libraries/sg-ds-library/components/Stat.tsx
import type { LiHTMLAttributes } from 'react';
import { SgDsLibraryIcon } from './Icon';
import { SgDsLibraryText } from './Text';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryStatTone = 'default' | 'brand';

export type SgDsLibraryStatProps = Omit<LiHTMLAttributes<HTMLLIElement>, 'children'> & {
  icon?: string;
  label?: string;
  tone?: SgDsLibraryStatTone;
  value?: string | number;
};

export function SgDsLibraryStat(rawProps: SgDsLibraryStatProps) {
  const {
  className = '',
  icon,
  label = 'plays',
  tone = 'default',
  value = '124K',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <li
      {...props}
      className={['sg-ds-library-scope', 'stat', className].filter(Boolean).join(' ')}
      data-tone={tone === 'brand' ? 'brand' : undefined}
    >
      {icon ? <SgDsLibraryIcon name={icon} size="1em" /> : null}
      <SgDsLibraryText as="strong" tone="inherit" variant="ui" weight="semibold">{value}</SgDsLibraryText>
      <SgDsLibraryText as="span" tone="inherit" variant="ui-sm">{label}</SgDsLibraryText>
    </li>
  );
}

export default SgDsLibraryStat;

// frontend/src/components/Stat.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Icon from './Icon.vue'
import Text from './Text.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  icon: { type: String, default: undefined },
  label: { type: String, default: 'plays' },
  tone: { type: String, default: 'default' },
  value: { type: [String, Number], default: '124K' },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'stat', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <li
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-tone="props.tone === 'brand' ? 'brand' : undefined"
  >
    <Icon v-if="props.icon" :name="props.icon" size="1em" />
    <Text as="strong" tone="inherit" variant="ui" weight="semibold">{{ props.value }}</Text>
    <Text as="span" tone="inherit" variant="ui-sm">{{ props.label }}</Text>
  </li>
</template>
