// frontend/src/libraries/sg-ds-library/components/Toolbar.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryToolbarAlign = 'start' | 'center' | 'end' | 'between';
export type SgDsLibraryToolbarSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryToolbarVariant = 'default' | 'divided';
export type SgDsLibraryToolbarGroupAlign = 'start' | 'end';

export type SgDsLibraryToolbarProps = HTMLAttributes<HTMLDivElement> & {
  align?: SgDsLibraryToolbarAlign;
  children?: ReactNode;
  startSlot?: ReactNode;
  endSlot?: ReactNode;
  size?: SgDsLibraryToolbarSize;
  variant?: SgDsLibraryToolbarVariant;
  wrap?: boolean;
};

export function SgDsLibraryToolbar(rawProps: SgDsLibraryToolbarProps) {
  const {
  align = 'start',
  children,
  className = '',
  endSlot,
  size = 'md',
  startSlot,
  variant = 'default',
  wrap = false,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'toolbar', className].filter(Boolean).join(' ')}
      data-align={align === 'start' ? undefined : align}
      data-size={size}
      data-variant={variant === 'divided' ? 'divided' : undefined}
      data-wrap={wrap ? 'true' : undefined}
    >
      {startSlot || endSlot ? (
        <>
          {startSlot ? <div className="toolbar-start">{startSlot}</div> : null}
          {endSlot ? <div className="toolbar-end">{endSlot}</div> : null}
        </>
      ) : children}
    </div>
  );
}

export type SgDsLibraryToolbarGroupProps = HTMLAttributes<HTMLDivElement> & {
  align?: SgDsLibraryToolbarGroupAlign;
  children?: ReactNode;
};

export function SgDsLibraryToolbarGroup(rawProps: SgDsLibraryToolbarGroupProps) {
  const {
  align = 'start',
  children,
  className = '',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'toolbar-group', className].filter(Boolean).join(' ')}
      data-align={align === 'end' ? 'end' : undefined}
    >
      {children}
    </div>
  );
}

export default SgDsLibraryToolbar;

// frontend/src/components/Toolbar.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  align: { type: String, default: 'start' },
  size: { type: String, default: 'md' },
  variant: { type: String, default: 'default' },
  wrap: { type: Boolean, default: false },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'toolbar', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <div
    v-bind="{ ...($attrs), class: undefined }"
    :class="classes"
    :data-align="props.align !== 'start' ? props.align : undefined"
    :data-size="props.size"
    :data-variant="props.variant === 'divided' ? 'divided' : undefined"
    :data-wrap="props.wrap ? 'true' : undefined"
  >
    <template v-if="$slots.start || $slots.end">
      <div v-if="$slots.start" class="toolbar-start">
        <slot name="start" />
      </div>
      <div v-if="$slots.end" class="toolbar-end">
        <slot name="end" />
      </div>
    </template>
    <slot v-else />
  </div>
</template>
