// frontend/src/libraries/sg-ds-library/components/Tooltip.tsx
import { useId } from 'react';
import type { HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryTooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

export type SgDsLibraryTooltipProps = Omit<HTMLAttributes<HTMLSpanElement>, 'children'> & {
  trigger: ReactNode;
  tip: ReactNode;
  placement?: SgDsLibraryTooltipPlacement;
  arrow?: boolean;
  tipId?: string;
};

export function SgDsLibraryTooltip(rawProps: SgDsLibraryTooltipProps) {
  const {
  arrow = true,
  className = '',
  placement = 'top',
  tip,
  tipId,
  trigger,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const autoId = useId();
  const resolvedId = tipId ?? `tip-${autoId}`;

  return (
    <span
      {...props}
      className={['sg-ds-library-scope', 'tooltip-wrapper', className].filter(Boolean).join(' ')}
    >
      <span className="tooltip-trigger" tabIndex={0} aria-describedby={resolvedId}>
        {trigger}
      </span>
      <span className="tooltip" id={resolvedId} role="tooltip" data-placement={placement}>
        {tip}
        {arrow ? <span className="tooltip-arrow" aria-hidden="true" /> : null}
      </span>
    </span>
  );
}

export default SgDsLibraryTooltip;

// frontend/src/components/Tooltip.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  placement: { type: String, default: 'top' },
  arrow: { type: Boolean, default: true },
  tipId: { type: String, default: undefined },
})

let idCounter = 0
const autoId = `tip-${++idCounter}-${Math.random().toString(36).slice(2, 7)}`
const resolvedId = computed(() => props.tipId ?? autoId)

const classes = computed(() =>
  ['sg-ds-library-scope', 'tooltip-wrapper', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <span v-bind="{ ...($attrs), class: undefined }" :class="classes">
    <span class="tooltip-trigger" :tabindex="0" :aria-describedby="resolvedId">
      <slot name="trigger" />
    </span>
    <span class="tooltip" :id="resolvedId" role="tooltip" :data-placement="props.placement">
      <slot name="tip" />
      <span v-if="props.arrow" class="tooltip-arrow" aria-hidden="true" />
    </span>
  </span>
</template>
