// frontend/src/libraries/sg-ds-library/components/UserBlock.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import {
  SgDsLibraryAvatar,
  type SgDsLibraryAvatarShape,
  type SgDsLibraryAvatarSize,
  type SgDsLibraryAvatarStatus,
  type SgDsLibraryAvatarTone,
} from './Avatar';
import { SgDsLibraryButton, type SgDsLibraryButtonProps } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryUserBlockSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryUserBlockDirection = 'row' | 'stack';

export type SgDsLibraryUserBlockProps = HTMLAttributes<HTMLDivElement> & {
  children?: ReactNode;
  name?: string;
  meta?: string;
  initials?: string;
  avatarAlt?: string;
  avatarIcon?: ReactNode;
  avatarInitials?: string;
  avatarQuietStatus?: boolean;
  avatarShape?: SgDsLibraryAvatarShape;
  avatarSrc?: string;
  avatarStatus?: SgDsLibraryAvatarStatus;
  avatarStatusLabel?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  avatarSize?: SgDsLibraryAvatarSize;
  verified?: boolean;
  size?: SgDsLibraryUserBlockSize;
  direction?: SgDsLibraryUserBlockDirection;
  action1Icon?: string;
  action1Label?: string;
  action1Variant?: SgDsLibraryButtonProps['variant'];
  action1AriaLabel?: string;
  action2Icon?: string;
  action2Label?: string;
  action2Variant?: SgDsLibraryButtonProps['variant'];
  action2AriaLabel?: string;
  /* action3*: UserCard가 Pick으로 참조하는 예약 슬롯. UserBlock 자체는 렌더하지
   * 않지만, 선언이 없으면 rest 스프레드로 DOM에 누수되고 타입도 깨진다. */
  action3Icon?: string;
  action3Label?: string;
  action3Variant?: SgDsLibraryButtonProps['variant'];
  action3AriaLabel?: string;
  tailSlot?: ReactNode;
};

export function SgDsLibraryUserBlock(rawProps: SgDsLibraryUserBlockProps) {
  const {
  action1AriaLabel,
  action1Icon,
  action1Label,
  action1Variant = 'ghost',
  action2AriaLabel,
  action2Icon,
  action2Label,
  action2Variant = 'primary',
  action3AriaLabel: _action3AriaLabel,
  action3Icon: _action3Icon,
  action3Label: _action3Label,
  action3Variant: _action3Variant,
  avatarAlt = '',
  avatarIcon,
  avatarInitials,
  avatarQuietStatus = false,
  avatarShape = 'circle',
  avatarSize = 'md',
  avatarSrc,
  avatarStatus,
  avatarStatusLabel,
  avatarTone = 'neutral',
  children,
  className = '',
  direction = 'row',
  initials = 'U',
  meta,
  name = 'User',
  size = 'md',
  tailSlot,
  verified = false,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const actionButtons = tailSlot === undefined && children === undefined
    ? [
        renderUserBlockAction('action1', action1Label, action1Icon, action1Variant, action1AriaLabel),
        renderUserBlockAction('action2', action2Label, action2Icon, action2Variant, action2AriaLabel),
      ].filter(Boolean)
    : [];
  const tail = tailSlot ?? children ?? (actionButtons.length > 0 ? <div className="user-block-actions">{actionButtons}</div> : null);
  const resolvedInitials = avatarInitials ?? initials;

  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'user-block', className].filter(Boolean).join(' ')}
      data-size={size}
      data-direction={direction === 'stack' ? 'stack' : undefined}
    >
      <SgDsLibraryAvatar
        alt={avatarAlt}
        icon={avatarIcon}
        initials={resolvedInitials}
        quietStatus={avatarQuietStatus}
        shape={avatarShape}
        size={avatarSize}
        src={avatarSrc}
        status={avatarStatus}
        statusLabel={avatarStatusLabel}
        tone={avatarTone}
      />
      <div className="user-block-body">
        <span className="user-block-name">
          {name}
          {verified ? (
            <span className="user-block-verified" aria-label="Verified">
              <SgDsLibraryIcon name="badge-check" size="1em" />
            </span>
          ) : null}
        </span>
        {meta ? <span className="user-block-meta">{meta}</span> : null}
      </div>
      {tail ? <div className="user-block-tail">{tail}</div> : null}
    </div>
  );
}

function renderUserBlockAction(
  key: string,
  label: string | undefined,
  icon: string | undefined,
  variant: SgDsLibraryButtonProps['variant'],
  ariaLabel: string | undefined,
): ReactNode {
  const resolvedLabel = typeof label === 'string' ? label.trim() : '';
  const resolvedIcon = typeof icon === 'string' ? icon.trim() : '';
  if (!resolvedLabel && !resolvedIcon) return null;

  const iconOnly = !resolvedLabel;
  return (
    <SgDsLibraryButton
      key={key}
      aria-label={iconOnly ? (ariaLabel || resolvedIcon) : ariaLabel}
      iconOnly={iconOnly}
      leadingIcon={resolvedIcon || undefined}
      size="sm"
      variant={variant}
    >
      {resolvedLabel || ariaLabel || resolvedIcon}
    </SgDsLibraryButton>
  );
}

export default SgDsLibraryUserBlock;

// frontend/src/components/UserBlock.vue
<script setup>
import { computed, useAttrs, useSlots } from 'vue'
import Avatar from './Avatar.vue'
import Button from './Button.vue'
import Icon from './Icon.vue'

const attrs = useAttrs()
const slots = useSlots()

const props = defineProps({
  name: { default: 'User' },
  meta: { default: undefined },
  initials: { default: 'U' },
  avatarAlt: { default: '' },
  avatarInitials: { default: undefined },
  avatarQuietStatus: { default: false },
  avatarShape: { default: 'circle' },
  avatarSize: { default: 'md' },
  avatarSrc: { default: undefined },
  avatarStatus: { default: undefined },
  avatarStatusLabel: { default: undefined },
  avatarTone: { default: 'neutral' },
  verified: { default: false },
  size: { default: 'md' },
  direction: { default: 'row' },
  action1Icon: { default: undefined },
  action1Label: { default: undefined },
  action1Variant: { default: 'ghost' },
  action1AriaLabel: { default: undefined },
  action2Icon: { default: undefined },
  action2Label: { default: undefined },
  action2Variant: { default: 'primary' },
  action2AriaLabel: { default: undefined },
})

defineOptions({ inheritAttrs: false })

const classes = computed(() =>
  ['sg-ds-library-scope', 'user-block', attrs.class].filter(Boolean).join(' ')
)

const resolvedInitials = computed(() => props.avatarInitials ?? props.initials)

const hasTailSlot = computed(() => !!slots.tail)
const hasDefaultSlot = computed(() => !!slots.default)
const showActionsDiv = computed(() => !hasTailSlot.value && !hasDefaultSlot.value)

function resolveAction(label, icon) {
  const resolvedLabel = typeof label === 'string' ? label.trim() : ''
  const resolvedIcon = typeof icon === 'string' ? icon.trim() : ''
  if (!resolvedLabel && !resolvedIcon) return null
  return { resolvedLabel, resolvedIcon, iconOnly: !resolvedLabel }
}

const action1 = computed(() => resolveAction(props.action1Label, props.action1Icon))
const action2 = computed(() => resolveAction(props.action2Label, props.action2Icon))
const hasActions = computed(() => !!(action1.value || action2.value))
</script>

<template>
  <div
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-size="props.size"
    :data-direction="props.direction === 'stack' ? 'stack' : undefined"
  >
    <Avatar
      :alt="props.avatarAlt"
      :initials="resolvedInitials"
      :quiet-status="props.avatarQuietStatus"
      :shape="props.avatarShape"
      :size="props.avatarSize"
      :src="props.avatarSrc"
      :status="props.avatarStatus"
      :status-label="props.avatarStatusLabel"
      :tone="props.avatarTone"
    >
      <template v-if="$slots['avatar-icon']" #icon>
        <slot name="avatar-icon" />
      </template>
    </Avatar>

    <div class="user-block-body">
      <span class="user-block-name">
        {{ props.name }}
        <span v-if="props.verified" class="user-block-verified" aria-label="Verified">
          <Icon name="badge-check" size="1em" />
        </span>
      </span>
      <span v-if="props.meta" class="user-block-meta">{{ props.meta }}</span>
    </div>

    <div v-if="hasTailSlot" class="user-block-tail">
      <slot name="tail" />
    </div>
    <div v-else-if="hasDefaultSlot" class="user-block-tail">
      <slot />
    </div>
    <div v-else-if="showActionsDiv && hasActions" class="user-block-tail">
      <div class="user-block-actions">
        <Button
          v-if="action1"
          :aria-label="action1.iconOnly ? (props.action1AriaLabel || action1.resolvedIcon) : props.action1AriaLabel"
          :icon-only="action1.iconOnly"
          :leading-icon="action1.resolvedIcon || undefined"
          size="sm"
          :variant="props.action1Variant"
        >
          {{ action1.resolvedLabel || props.action1AriaLabel || action1.resolvedIcon }}
        </Button>
        <Button
          v-if="action2"
          :aria-label="action2.iconOnly ? (props.action2AriaLabel || action2.resolvedIcon) : props.action2AriaLabel"
          :icon-only="action2.iconOnly"
          :leading-icon="action2.resolvedIcon || undefined"
          size="sm"
          :variant="props.action2Variant"
        >
          {{ action2.resolvedLabel || props.action2AriaLabel || action2.resolvedIcon }}
        </Button>
      </div>
    </div>
  </div>
</template>
