// frontend/src/libraries/sg-ds-library/components/VideoListCard.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';
import {
  SgDsLibraryAvatar,
  type SgDsLibraryAvatarShape,
  type SgDsLibraryAvatarSize,
  type SgDsLibraryAvatarTone,
} from './Avatar';
import { SgDsLibraryBadge, type SgDsLibraryBadgeStatus, type SgDsLibraryBadgeVariant } from './Badge';
import { SgDsLibraryButton, type SgDsLibraryButtonSize } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { SgDsLibraryMediaFrame, type SgDsLibraryMediaFrameAspect, type SgDsLibraryMediaFrameSize } from './MediaFrame';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryVideoListCardSize = 'lg' | 'sm';
export type SgDsLibraryVideoListCardVariant = 'vertical' | 'horizontal';

export type SgDsLibraryVideoListCardProps = Omit<HTMLAttributes<HTMLElement>, 'title'> & {
  actionIcon?: string;
  actionLabel?: string;
  actionSize?: SgDsLibraryButtonSize;
  avatarAlt?: string;
  avatarInitials?: string;
  avatarShape?: SgDsLibraryAvatarShape;
  avatarSize?: SgDsLibraryAvatarSize;
  avatarSrc?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  badgeStatus?: SgDsLibraryBadgeStatus;
  badgeText?: string;
  badgeVariant?: SgDsLibraryBadgeVariant;
  creatorBadge?: ReactNode;
  creatorBadgeStatus?: SgDsLibraryBadgeStatus;
  creatorBadgeVariant?: SgDsLibraryBadgeVariant;
  creatorName?: ReactNode;
  creatorVerified?: boolean;
  duration?: string;
  eyebrow?: ReactNode;
  eyebrowColor?: string;
  eyebrowColorToken?: string;
  eyebrowColorTokenCollection?: string;
  mediaSize?: SgDsLibraryMediaFrameSize;
  meta?: ReactNode;
  progress?: number | string;
  progressLabel?: string;
  showAction?: boolean;
  showAvatar?: boolean;
  showGrain?: boolean;
  showPlay?: boolean;
  size?: SgDsLibraryVideoListCardSize;
  thumbnailAspect?: SgDsLibraryMediaFrameAspect;
  thumbnailBackground?: string;
  thumbnailImageUrl?: string;
  thumbnailWidth?: number | string;
  title?: ReactNode;
  titleLines?: number | string;
  variant?: SgDsLibraryVideoListCardVariant;
};

export function SgDsLibraryVideoListCard(rawProps: SgDsLibraryVideoListCardProps) {
  const {
    actionIcon = 'ellipsis',
    actionLabel = 'More options',
    actionSize,
    avatarAlt = '',
    avatarInitials = '코다',
    avatarShape = 'circle',
    avatarSize,
    avatarSrc = '',
    avatarTone = 'brand',
    badgeStatus = 'warning',
    badgeText = '15+',
    badgeVariant = 'solid',
    className = '',
    creatorBadge = '후원자 145k',
    creatorBadgeStatus = 'neutral',
    creatorBadgeVariant = 'flat',
    creatorName = '코다 / Koda',
    creatorVerified = true,
    duration = '17:02',
    eyebrow,
    eyebrowColor,
    eyebrowColorToken,
    eyebrowColorTokenCollection,
    mediaSize = 'md',
    meta = '92K 시청 · 1주 전',
    progress = 64,
    progressLabel = 'Media progress',
    showAction = true,
    showAvatar,
    showGrain = true,
    showPlay = false,
    size = 'lg',
    style,
    thumbnailAspect = '16/9',
    thumbnailBackground = 'linear-gradient(140deg, #0c1429, #4c1d95 50%, #be185d)',
    thumbnailImageUrl = '',
    thumbnailWidth = '50%',
    title = '새벽이 떠오를 때 — 2인 콜라보 단편',
    titleLines,
    variant = 'vertical',
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const resolvedShowAvatar = showAvatar ?? variant === 'vertical';
  const resolvedAvatarSize = avatarSize ?? (size === 'lg' ? 'md' : 'sm');
  const resolvedActionSize = actionSize ?? (size === 'lg' && variant === 'vertical' ? 'md' : 'sm');
  const hasAvatar = resolvedShowAvatar && Boolean(avatarSrc || avatarInitials);
  const hasCreatorLine = Boolean(creatorName || creatorBadge || (creatorVerified && creatorName));
  const thumbnailWidthCss = formatVideoListCardCssDimension(thumbnailWidth);
  const titleLineCount = formatVideoListCardLineCount(titleLines);
  const eyebrowCssColor = toVideoListCardCssColor(
    formatVideoListCardTokenReference(eyebrowColorTokenCollection, eyebrowColorToken) ?? eyebrowColor,
  );
  const rootStyle = {
    ...style,
    ...(thumbnailWidthCss ? { '--c-video-list-card-thumbnail-width': thumbnailWidthCss } : null),
    ...(titleLineCount ? { '--c-video-list-card-title-lines': titleLineCount } : null),
    ...(eyebrowCssColor ? { '--video-list-card-eyebrow-color': eyebrowCssColor } : null),
  } as CSSProperties;

  return (
    <article
      {...props}
      className={['sg-ds-library-scope', 'video-list-card', className].filter(Boolean).join(' ')}
      data-size={size}
      data-variant={variant}
      style={rootStyle}
    >
      <SgDsLibraryMediaFrame
        className="video-list-card-media"
        aspect={thumbnailAspect}
        background={thumbnailBackground}
        badgeStatus={badgeStatus}
        badgeText={badgeText}
        badgeVariant={badgeVariant}
        captionEyebrow=""
        captionTitle=""
        duration={duration}
        progress={progress}
        progressLabel={progressLabel}
        showGrain={showGrain}
        showPlay={showPlay}
        size={mediaSize}
        src={thumbnailImageUrl}
      />
      <div className="video-list-card-info">
        {hasAvatar ? (
          <SgDsLibraryAvatar
            alt={avatarAlt}
            className="video-list-card-avatar"
            initials={avatarInitials}
            shape={avatarShape}
            size={resolvedAvatarSize}
            src={avatarSrc}
            tone={avatarTone}
          />
        ) : null}
        <div className="video-list-card-body">
          {eyebrow ? <span className="video-list-card-eyebrow">{eyebrow}</span> : null}
          <span className="video-list-card-title">{title}</span>
          {hasCreatorLine ? (
            <span className="video-list-card-creator">
              {creatorName ? (
                <span className="video-list-card-creator-identity">
                  <span className="video-list-card-creator-name">{creatorName}</span>
                  {creatorVerified ? (
                  <SgDsLibraryIcon
                    className="video-list-card-verified"
                    color="var(--c-video-list-card-verified-color)"
                    name="badge-check"
                    size="12"
                    strokeWidth="2.5"
                    />
                  ) : null}
                </span>
              ) : null}
              {creatorBadge ? (
                <SgDsLibraryBadge
                  className="video-list-card-creator-badge"
                  size="sm"
                  status={creatorBadgeStatus}
                  variant={creatorBadgeVariant}
                >
                  {creatorBadge}
                </SgDsLibraryBadge>
              ) : null}
            </span>
          ) : null}
          {meta ? <span className="video-list-card-meta">{meta}</span> : null}
        </div>
        {showAction ? (
          <SgDsLibraryButton
            aria-label={actionLabel}
            className="video-list-card-action"
            iconOnly
            leadingIcon={actionIcon}
            size={resolvedActionSize}
            variant="ghost"
          >
            {actionLabel}
          </SgDsLibraryButton>
        ) : null}
      </div>
    </article>
  );
}

function formatVideoListCardCssDimension(value: number | string | undefined): string | null {
  if (typeof value === 'number') return Number.isFinite(value) ? `${value}px` : null;
  const trimmed = value?.trim();
  return trimmed || null;
}

function formatVideoListCardLineCount(value: number | string | undefined): string | null {
  if (typeof value === 'number') return Number.isFinite(value) && value > 0 ? String(Math.round(value)) : null;
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? String(Math.round(parsed)) : null;
}

function formatVideoListCardTokenReference(collectionId: string | undefined, tokenId: string | undefined): string | null {
  const collection = collectionId?.trim();
  const token = tokenId?.trim();
  return collection && token ? `var(--ds-token-${collection}-${token})` : null;
}

function toVideoListCardCssColor(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed || undefined;
}

export default SgDsLibraryVideoListCard;

// frontend/src/components/VideoListCard.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Avatar from './Avatar.vue'
import Badge from './Badge.vue'
import Button from './Button.vue'
import Icon from './Icon.vue'
import MediaFrame from './MediaFrame.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  actionIcon: { default: 'ellipsis' },
  actionLabel: { default: 'More options' },
  actionSize: { default: undefined },
  avatarAlt: { default: '' },
  avatarInitials: { default: '코다' },
  avatarShape: { default: 'circle' },
  avatarSize: { default: undefined },
  avatarSrc: { default: '' },
  avatarTone: { default: 'brand' },
  badgeStatus: { default: 'warning' },
  badgeText: { default: '15+' },
  badgeVariant: { default: 'solid' },
  creatorBadge: { default: '후원자 145k' },
  creatorBadgeStatus: { default: 'neutral' },
  creatorBadgeVariant: { default: 'flat' },
  creatorName: { default: '코다 / Koda' },
  creatorVerified: { default: true },
  duration: { default: '17:02' },
  eyebrow: { default: undefined },
  eyebrowColor: { default: undefined },
  eyebrowColorToken: { default: undefined },
  eyebrowColorTokenCollection: { default: undefined },
  mediaSize: { default: 'md' },
  meta: { default: '92K 시청 · 1주 전' },
  progress: { default: 64 },
  progressLabel: { default: 'Media progress' },
  showAction: { default: true },
  showAvatar: { default: undefined },
  showGrain: { default: true },
  showPlay: { default: false },
  size: { default: 'lg' },
  thumbnailAspect: { default: '16/9' },
  thumbnailBackground: { default: 'linear-gradient(140deg, #0c1429, #4c1d95 50%, #be185d)' },
  thumbnailImageUrl: { default: '' },
  thumbnailWidth: { default: '50%' },
  title: { default: '새벽이 떠오를 때 — 2인 콜라보 단편' },
  titleLines: { default: undefined },
  variant: { default: 'vertical' },
})

const resolvedShowAvatar = computed(() => props.showAvatar ?? props.variant === 'vertical')
const resolvedAvatarSize = computed(() => props.avatarSize ?? (props.size === 'lg' ? 'md' : 'sm'))
const resolvedActionSize = computed(() => props.actionSize ?? (props.size === 'lg' && props.variant === 'vertical' ? 'md' : 'sm'))
const hasAvatar = computed(() => resolvedShowAvatar.value && Boolean(props.avatarSrc || props.avatarInitials))
const hasCreatorLine = computed(() => Boolean(props.creatorName || props.creatorBadge || (props.creatorVerified && props.creatorName)))

function formatCssDimension(value) {
  if (typeof value === 'number') return Number.isFinite(value) ? `${value}px` : null
  const trimmed = value?.trim()
  return trimmed || null
}

function formatLineCount(value) {
  if (typeof value === 'number') return Number.isFinite(value) && value > 0 ? String(Math.round(value)) : null
  const parsed = Number(value)
  return Number.isFinite(parsed) && parsed > 0 ? String(Math.round(parsed)) : null
}

function formatTokenReference(collectionId, tokenId) {
  const collection = collectionId?.trim()
  const token = tokenId?.trim()
  return collection && token ? `var(--ds-token-${collection}-${token})` : null
}

function toCssColor(value) {
  const trimmed = value?.trim()
  return trimmed || undefined
}

const classes = computed(() =>
  ['sg-ds-library-scope', 'video-list-card', attrs.class].filter(Boolean).join(' ')
)

const rootStyle = computed(() => {
  const thumbnailWidthCss = formatCssDimension(props.thumbnailWidth)
  const titleLineCount = formatLineCount(props.titleLines)
  const eyebrowCssColor = toCssColor(
    formatTokenReference(props.eyebrowColorTokenCollection, props.eyebrowColorToken) ?? props.eyebrowColor
  )
  return {
    ...(attrs.style || {}),
    ...(thumbnailWidthCss ? { '--c-video-list-card-thumbnail-width': thumbnailWidthCss } : {}),
    ...(titleLineCount ? { '--c-video-list-card-title-lines': titleLineCount } : {}),
    ...(eyebrowCssColor ? { '--video-list-card-eyebrow-color': eyebrowCssColor } : {}),
  }
})
</script>

<template>
  <article
    v-bind="{ ...attrs, class: undefined, style: undefined }"
    :class="classes"
    :style="rootStyle"
    :data-size="props.size"
    :data-variant="props.variant"
  >
    <MediaFrame
      class="video-list-card-media"
      :aspect="props.thumbnailAspect"
      :background="props.thumbnailBackground"
      :badge-status="props.badgeStatus"
      :badge-text="props.badgeText"
      :badge-variant="props.badgeVariant"
      caption-eyebrow=""
      caption-title=""
      :duration="props.duration"
      :progress="props.progress"
      :progress-label="props.progressLabel"
      :show-grain="props.showGrain"
      :show-play="props.showPlay"
      :size="props.mediaSize"
      :src="props.thumbnailImageUrl"
    />
    <div class="video-list-card-info">
      <Avatar
        v-if="hasAvatar"
        :alt="props.avatarAlt"
        class="video-list-card-avatar"
        :initials="props.avatarInitials"
        :shape="props.avatarShape"
        :size="resolvedAvatarSize"
        :src="props.avatarSrc"
        :tone="props.avatarTone"
      />
      <div class="video-list-card-body">
        <span v-if="props.eyebrow" class="video-list-card-eyebrow">{{ props.eyebrow }}</span>
        <span class="video-list-card-title">{{ props.title }}</span>
        <span v-if="hasCreatorLine" class="video-list-card-creator">
          <span v-if="props.creatorName" class="video-list-card-creator-identity">
            <span class="video-list-card-creator-name">{{ props.creatorName }}</span>
            <Icon
              v-if="props.creatorVerified"
              class="video-list-card-verified"
              color="var(--c-video-list-card-verified-color)"
              name="badge-check"
              size="12"
              stroke-width="2.5"
            />
          </span>
          <Badge
            v-if="props.creatorBadge"
            class="video-list-card-creator-badge"
            size="sm"
            :status="props.creatorBadgeStatus"
            :variant="props.creatorBadgeVariant"
          >
            {{ props.creatorBadge }}
          </Badge>
        </span>
        <span v-if="props.meta" class="video-list-card-meta">{{ props.meta }}</span>
      </div>
      <Button
        v-if="props.showAction"
        :aria-label="props.actionLabel"
        class="video-list-card-action"
        :icon-only="true"
        :leading-icon="props.actionIcon"
        :size="resolvedActionSize"
        variant="ghost"
      >
        {{ props.actionLabel }}
      </Button>
    </div>
  </article>
</template>
