// frontend/src/components/Checkbox.vue
<script setup>
import { ref, watch, computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  disabled: {
    default: undefined,
  },
  indeterminate: {
    default: false,
  },
  inputClassName: {
    default: '',
  },
  label: {
    default: 'Remember me',
  },
  size: {
    default: 'md',
  },
})

const labelClasses = computed(() =>
  ['sg-ds-library-scope', 'checkbox-label', attrs.class].filter(Boolean).join(' ')
)

const inputClasses = computed(() =>
  ['checkbox', props.inputClassName].filter(Boolean).join(' ')
)

const inputRef = ref(null)

watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) inputRef.value.indeterminate = val
  },
  { immediate: true }
)
</script>

<template>
  <label
    v-bind="{ ...$attrs, class: undefined }"
    :class="labelClasses"
    :data-size="props.size"
    :data-disabled="props.disabled || undefined"
  >
    <input
      ref="inputRef"
      type="checkbox"
      :class="inputClasses"
      :data-size="props.size"
      :data-indeterminate="props.indeterminate || undefined"
      :disabled="props.disabled"
      :aria-disabled="props.disabled || undefined"
      :aria-checked="props.indeterminate ? 'mixed' : undefined"
    />
    <span class="checkbox-label-text">{{ props.label }}</span>
  </label>
</template>

// frontend/src/libraries/sg-ds-library/components/Checkbox.tsx
import type { InputHTMLAttributes, ReactNode } from 'react';
import { useEffect, useRef } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryCheckboxSize = 'sm' | 'md' | 'lg';

export type SgDsLibraryCheckboxProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'children' | 'size' | 'type'> & {
  indeterminate?: boolean;
  inputClassName?: string;
  label?: ReactNode;
  size?: SgDsLibraryCheckboxSize;
};

export function SgDsLibraryCheckbox(rawProps: SgDsLibraryCheckboxProps) {
  const {
  className = '',
  disabled,
  indeterminate = false,
  inputClassName = '',
  label = 'Remember me',
  size = 'md',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (inputRef.current) inputRef.current.indeterminate = indeterminate;
  }, [indeterminate]);

  return (
    <label
      className={['sg-ds-library-scope', 'checkbox-label', className].filter(Boolean).join(' ')}
      data-size={size}
      data-disabled={disabled || undefined}
    >
      <input
        {...props}
        ref={inputRef}
        type="checkbox"
        className={['checkbox', inputClassName].filter(Boolean).join(' ')}
        data-size={size}
        data-indeterminate={indeterminate || undefined}
        disabled={disabled}
        aria-disabled={disabled || undefined}
        aria-checked={indeterminate ? 'mixed' : undefined}
      />
      <span className="checkbox-label-text">{label}</span>
    </label>
  );
}

export default SgDsLibraryCheckbox;
