// frontend/src/components/Dialog.vue
<script setup>
import { ref, computed, watch, onMounted, onUnmounted, useAttrs } from 'vue'
import Button from './Button.vue'
import Icon from './Icon.vue'
import Text from './Text.vue'

const attrs = useAttrs()

const props = defineProps({
  action1Icon: { default: undefined },
  action1Label: { default: undefined },
  action1Variant: { default: 'ghost' },
  action2Icon: { default: undefined },
  action2Label: { default: undefined },
  action2Variant: { default: 'primary' },
  align: { default: 'center' },
  bordered: { default: false },
  description: { default: undefined },
  dimmed: { default: true },
  footerButtonLayout: { default: 'right' },
  floating: { default: true },
  onAction1: { default: undefined },
  onAction2: { default: undefined },
  onDismiss: { default: undefined },
  open: { default: true },
  scroll: { default: false },
  showClose: { default: true },
  size: { default: 'md' },
  title: { default: undefined },
})

defineOptions({ inheritAttrs: false })

const bodyRef = ref(null)
const uid = Math.random().toString(36).slice(2)
const titleId = attrs['aria-labelledby'] ?? `${uid}-title`
const descriptionId = attrs['aria-describedby'] ?? `${uid}-description`

const hasAction1 = computed(() => typeof props.action1Label === 'string' && props.action1Label.trim().length > 0)
const hasAction2 = computed(() => typeof props.action2Label === 'string' && props.action2Label.trim().length > 0)
const actionButtonSize = computed(() => props.size === 'sm' ? 'sm' : props.size === 'md' ? 'md' : 'lg')

const scrollState = ref({ canScrollDown: false, canScrollUp: false })

let frameId = null
let scrollCleanup = null

const commitScrollState = () => {
  frameId = null
  const el = bodyRef.value
  if (!el) return
  const maxScrollTop = Math.max(0, el.scrollHeight - el.clientHeight)
  const next = {
    canScrollDown: maxScrollTop - el.scrollTop > 1,
    canScrollUp: el.scrollTop > 1,
  }
  if (
    scrollState.value.canScrollDown !== next.canScrollDown ||
    scrollState.value.canScrollUp !== next.canScrollUp
  ) {
    scrollState.value = next
  }
}

const updateScrollState = () => {
  if (frameId !== null) return
  frameId = window.requestAnimationFrame(commitScrollState)
}

const setupScrollListeners = () => {
  const el = bodyRef.value
  if (!props.open || !props.scroll || !el) {
    scrollState.value = { canScrollDown: false, canScrollUp: false }
    return
  }

  updateScrollState()
  el.addEventListener('scroll', updateScrollState, { passive: true })
  window.addEventListener('resize', updateScrollState)

  const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(updateScrollState)
  observer?.observe(el)
  Array.from(el.children).forEach((child) => observer?.observe(child))

  scrollCleanup = () => {
    if (frameId !== null) window.cancelAnimationFrame(frameId)
    el.removeEventListener('scroll', updateScrollState)
    window.removeEventListener('resize', updateScrollState)
    observer?.disconnect()
  }
}

const teardownScrollListeners = () => {
  if (scrollCleanup) {
    scrollCleanup()
    scrollCleanup = null
  }
}

onMounted(() => {
  setupScrollListeners()
})

onUnmounted(() => {
  teardownScrollListeners()
})

watch(
  () => [props.open, props.scroll, props.size],
  () => {
    teardownScrollListeners()
    setupScrollListeners()
  }
)

const handleBodyKeyDown = (event) => {
  if (!props.scroll || event.target !== event.currentTarget) return
  const el = bodyRef.value
  if (!el) return
  const pageStep = Math.max(48, el.clientHeight * 0.82)
  if (event.key === 'PageDown' || event.key === ' ') {
    event.preventDefault()
    el.scrollBy({ behavior: 'smooth', top: pageStep })
  }
  if (event.key === 'PageUp') {
    event.preventDefault()
    el.scrollBy({ behavior: 'smooth', top: -pageStep })
  }
  if (event.key === 'ArrowDown') {
    event.preventDefault()
    el.scrollBy({ behavior: 'smooth', top: 40 })
  }
  if (event.key === 'ArrowUp') {
    event.preventDefault()
    el.scrollBy({ behavior: 'smooth', top: -40 })
  }
  if (event.key === 'End') {
    event.preventDefault()
    el.scrollTo({ behavior: 'smooth', top: el.scrollHeight })
  }
  if (event.key === 'Home') {
    event.preventDefault()
    el.scrollTo({ behavior: 'smooth', top: 0 })
  }
}

const handleAction1Click = (event) => {
  props.onAction1?.()
  event.currentTarget.closest('dialog')?.close('action1')
}

const handleAction2Click = (event) => {
  props.onAction2?.()
  event.currentTarget.closest('dialog')?.close('action2')
}

const handleCloseClick = () => {
  props.onDismiss?.()
}

const dialogClasses = computed(() =>
  ['sg-ds-library-scope', 'dialog', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <div aria-hidden="true" class="sg-ds-library-scope dialog-backdrop" v-if="props.open && props.floating && props.dimmed" />
  <dialog
    v-bind="{ ...attrs, class: undefined }"
    :class="dialogClasses"
    :aria-describedby="props.description ? descriptionId : undefined"
    :aria-labelledby="props.title ? titleId : undefined"
    :data-align="props.align"
    :data-bordered="props.bordered || undefined"
    :data-can-scroll-down="(props.scroll && scrollState.canScrollDown) || undefined"
    :data-can-scroll-up="(props.scroll && scrollState.canScrollUp) || undefined"
    :data-dimmed="props.dimmed"
    :data-floating="props.floating"
    :data-scroll="props.scroll || undefined"
    :data-size="props.size"
    :open="props.open"
  >
    <!-- Header -->
    <header class="sg-ds-library-scope dialog-header">
      <slot name="header">
        <Text v-if="props.title" as="h2" class="dialog-title" variant="heading-3" :id="titleId">{{ props.title }}</Text>
        <Text v-if="props.description" as="p" class="dialog-description" tone="secondary" variant="caption" :id="descriptionId">{{ props.description }}</Text>
        <button
          v-if="props.showClose"
          aria-label="Close dialog"
          class="sg-ds-library-scope dialog-close"
          type="button"
          @click="handleCloseClick"
        >
          <Icon name="x" size="1em" />
        </button>
      </slot>
    </header>

    <!-- Body -->
    <div
      ref="bodyRef"
      class="sg-ds-library-scope dialog-body"
      :data-scroll="props.scroll || undefined"
      :tabindex="props.scroll ? 0 : undefined"
      @keydown="props.scroll ? handleBodyKeyDown : undefined"
    >
      <slot />
    </div>

    <!-- Footer -->
    <footer
      v-if="hasAction1 || hasAction2"
      class="sg-ds-library-scope dialog-footer"
      :data-layout="props.footerButtonLayout"
    >
      <Button
        v-if="hasAction1"
        :leading-icon="props.action1Icon"
        :size="actionButtonSize"
        :variant="props.action1Variant"
        @click="handleAction1Click"
      >{{ props.action1Label }}</Button>
      <Button
        v-if="hasAction2"
        :leading-icon="props.action2Icon"
        :size="actionButtonSize"
        :variant="props.action2Variant"
        @click="handleAction2Click"
      >{{ props.action2Label }}</Button>
    </footer>
  </dialog>
</template>

// frontend/src/libraries/sg-ds-library/components/Dialog.tsx
import { forwardRef, useEffect, useId, useRef, useState, type ButtonHTMLAttributes, type DialogHTMLAttributes, type HTMLAttributes, type KeyboardEvent, type MouseEvent, type ReactNode } from 'react';
import { SgDsLibraryButton, type SgDsLibraryButtonProps } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { SgDsLibraryText } from './Text';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryDialogSize = 'sm' | 'md' | 'lg' | 'xl' | 'full';
export type SgDsLibraryDialogAlign = 'center' | 'top';
export type SgDsLibraryDialogFooterButtonLayout = 'right' | 'full';

export type SgDsLibraryDialogProps = Omit<DialogHTMLAttributes<HTMLDialogElement>, 'title'> & {
  action1Icon?: string;
  action1Label?: string;
  action1Variant?: SgDsLibraryButtonProps['variant'];
  action2Icon?: string;
  action2Label?: string;
  action2Variant?: SgDsLibraryButtonProps['variant'];
  align?: SgDsLibraryDialogAlign;
  bordered?: boolean;
  children?: ReactNode;
  description?: ReactNode;
  dimmed?: boolean;
  footerButtonLayout?: SgDsLibraryDialogFooterButtonLayout;
  floating?: boolean;
  onAction1?: () => void;
  onAction2?: () => void;
  onDismiss?: () => void;
  open?: boolean;
  scroll?: boolean;
  showClose?: boolean;
  size?: SgDsLibraryDialogSize;
  title?: ReactNode;
};

export type SgDsLibraryDialogHeaderProps = Omit<HTMLAttributes<HTMLElement>, 'title'> & {
  children?: ReactNode;
  description?: ReactNode;
  descriptionId?: string;
  onClose?: () => void;
  showClose?: boolean;
  title?: ReactNode;
  titleId?: string;
};

export type SgDsLibraryDialogTitleProps = HTMLAttributes<HTMLHeadingElement> & {
  children?: ReactNode;
};

export type SgDsLibraryDialogDescriptionProps = HTMLAttributes<HTMLParagraphElement> & {
  children?: ReactNode;
};

export type SgDsLibraryDialogBodyProps = HTMLAttributes<HTMLDivElement> & {
  children?: ReactNode;
  scroll?: boolean;
};

export type SgDsLibraryDialogFooterProps = HTMLAttributes<HTMLElement> & {
  children?: ReactNode;
  layout?: SgDsLibraryDialogFooterButtonLayout;
};

export type SgDsLibraryDialogCloseProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  label?: string;
};

export function SgDsLibraryDialog(rawProps: SgDsLibraryDialogProps) {
  const {
  action1Icon,
  action1Label,
  action1Variant = 'ghost',
  action2Icon,
  action2Label,
  action2Variant = 'primary',
  align = 'center',
  bordered = false,
  children,
  className = '',
  description,
  dimmed = true,
  footerButtonLayout = 'right',
  floating = true,
  onAction1,
  onAction2,
  onDismiss,
  open = true,
  scroll = false,
  showClose = true,
  size = 'md',
  title,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const bodyRef = useRef<HTMLDivElement | null>(null);
  const generatedId = useId();
  const titleId = props['aria-labelledby'] ?? `${generatedId}-title`;
  const descriptionId = props['aria-describedby'] ?? `${generatedId}-description`;
  const hasAction1 = typeof action1Label === 'string' && action1Label.trim().length > 0;
  const hasAction2 = typeof action2Label === 'string' && action2Label.trim().length > 0;
  const actionButtonSize: SgDsLibraryButtonProps['size'] = size === 'sm' ? 'sm' : size === 'md' ? 'md' : 'lg';
  const [scrollState, setScrollState] = useState({ canScrollDown: false, canScrollUp: false });

  useEffect(() => {
    const bodyElement = bodyRef.current;
    if (!open || !scroll || !bodyElement) {
      setScrollState({ canScrollDown: false, canScrollUp: false });
      return undefined;
    }

    let frameId: number | null = null;
    const commitScrollState = () => {
      frameId = null;
      const maxScrollTop = Math.max(0, bodyElement.scrollHeight - bodyElement.clientHeight);
      const nextState = {
        canScrollDown: maxScrollTop - bodyElement.scrollTop > 1,
        canScrollUp: bodyElement.scrollTop > 1,
      };
      setScrollState((current) => (
        current.canScrollDown === nextState.canScrollDown && current.canScrollUp === nextState.canScrollUp
          ? current
          : nextState
      ));
    };
    const updateScrollState = () => {
      if (frameId !== null) return;
      frameId = window.requestAnimationFrame(commitScrollState);
    };

    updateScrollState();
    bodyElement.addEventListener('scroll', updateScrollState, { passive: true });
    window.addEventListener('resize', updateScrollState);
    const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(updateScrollState);
    observer?.observe(bodyElement);
    Array.from(bodyElement.children).forEach((child) => observer?.observe(child));
    return () => {
      if (frameId !== null) window.cancelAnimationFrame(frameId);
      bodyElement.removeEventListener('scroll', updateScrollState);
      window.removeEventListener('resize', updateScrollState);
      observer?.disconnect();
    };
  }, [children, open, scroll, size]);

  const handleBodyKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (!scroll || event.target !== event.currentTarget) return;
    const bodyElement = bodyRef.current;
    if (!bodyElement) return;
    const pageStep = Math.max(48, bodyElement.clientHeight * 0.82);
    if (event.key === 'PageDown' || event.key === ' ') {
      event.preventDefault();
      bodyElement.scrollBy({ behavior: 'smooth', top: pageStep });
    }
    if (event.key === 'PageUp') {
      event.preventDefault();
      bodyElement.scrollBy({ behavior: 'smooth', top: -pageStep });
    }
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      bodyElement.scrollBy({ behavior: 'smooth', top: 40 });
    }
    if (event.key === 'ArrowUp') {
      event.preventDefault();
      bodyElement.scrollBy({ behavior: 'smooth', top: -40 });
    }
    if (event.key === 'End') {
      event.preventDefault();
      bodyElement.scrollTo({ behavior: 'smooth', top: bodyElement.scrollHeight });
    }
    if (event.key === 'Home') {
      event.preventDefault();
      bodyElement.scrollTo({ behavior: 'smooth', top: 0 });
    }
  };

  const handleAction1Click = (event: MouseEvent<HTMLButtonElement>) => {
    onAction1?.();
    event.currentTarget.closest('dialog')?.close('action1');
  };

  const handleAction2Click = (event: MouseEvent<HTMLButtonElement>) => {
    onAction2?.();
    event.currentTarget.closest('dialog')?.close('action2');
  };

  return (
    <>
      {open && floating && dimmed ? <div aria-hidden="true" className="sg-ds-library-scope dialog-backdrop" /> : null}
      <dialog
        {...props}
        aria-describedby={description ? descriptionId : undefined}
        aria-labelledby={title ? titleId : undefined}
        className={['sg-ds-library-scope', 'dialog', className].filter(Boolean).join(' ')}
        data-align={align}
        data-bordered={bordered || undefined}
        data-can-scroll-down={scroll && scrollState.canScrollDown || undefined}
        data-can-scroll-up={scroll && scrollState.canScrollUp || undefined}
        data-dimmed={dimmed}
        data-floating={floating}
        data-scroll={scroll || undefined}
        data-size={size}
        open={open}
      >
        <SgDsLibraryDialogHeader
          description={description}
          descriptionId={descriptionId}
          onClose={onDismiss}
          showClose={showClose}
          title={title}
          titleId={titleId}
        />
        <SgDsLibraryDialogBody onKeyDown={scroll ? handleBodyKeyDown : undefined} ref={bodyRef} scroll={scroll} tabIndex={scroll ? 0 : undefined}>{children}</SgDsLibraryDialogBody>
        {hasAction1 || hasAction2 ? (
          <SgDsLibraryDialogFooter layout={footerButtonLayout}>
            {hasAction1 ? (
              <SgDsLibraryButton leadingIcon={action1Icon} size={actionButtonSize} variant={action1Variant} onClick={handleAction1Click}>{action1Label}</SgDsLibraryButton>
            ) : null}
            {hasAction2 ? (
              <SgDsLibraryButton leadingIcon={action2Icon} size={actionButtonSize} variant={action2Variant} onClick={handleAction2Click}>{action2Label}</SgDsLibraryButton>
            ) : null}
          </SgDsLibraryDialogFooter>
        ) : null}
      </dialog>
    </>
  );
}

export function SgDsLibraryDialogHeader(rawProps: SgDsLibraryDialogHeaderProps) {
  const {
  children,
  className = '',
  description,
  descriptionId,
  onClose,
  showClose = true,
  title,
  titleId,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const content = children ?? (
    <>
      {title ? <SgDsLibraryDialogTitle id={titleId}>{title}</SgDsLibraryDialogTitle> : null}
      {description ? <SgDsLibraryDialogDescription id={descriptionId}>{description}</SgDsLibraryDialogDescription> : null}
      {showClose ? <SgDsLibraryDialogClose onClick={() => onClose?.()} /> : null}
    </>
  );

  return <header {...props} className={['sg-ds-library-scope', 'dialog-header', className].filter(Boolean).join(' ')}>{content}</header>;
}

export function SgDsLibraryDialogTitle(rawProps: SgDsLibraryDialogTitleProps) {
  const { children, className = '', ...props } = resolveWorkbenchModeProps(rawProps);
  return <SgDsLibraryText {...props} as="h2" className={['dialog-title', className].filter(Boolean).join(' ')} variant="heading-3">{children}</SgDsLibraryText>;
}

export function SgDsLibraryDialogDescription(rawProps: SgDsLibraryDialogDescriptionProps) {
  const { children, className = '', ...props } = resolveWorkbenchModeProps(rawProps);
  return <SgDsLibraryText {...props} as="p" className={['dialog-description', className].filter(Boolean).join(' ')} tone="secondary" variant="caption">{children}</SgDsLibraryText>;
}

export const SgDsLibraryDialogBody = forwardRef<HTMLDivElement, SgDsLibraryDialogBodyProps>(function SgDsLibraryDialogBody({ children, className = '', scroll = false, ...props }, ref) {
  return <div {...props} className={['sg-ds-library-scope', 'dialog-body', className].filter(Boolean).join(' ')} data-scroll={scroll || undefined} ref={ref}>{children}</div>;
});

export function SgDsLibraryDialogFooter(rawProps: SgDsLibraryDialogFooterProps) {
  const { children, className = '', layout = 'right', ...props } = resolveWorkbenchModeProps(rawProps);
  return <footer {...props} className={['sg-ds-library-scope', 'dialog-footer', className].filter(Boolean).join(' ')} data-layout={layout}>{children}</footer>;
}

export function SgDsLibraryDialogClose(rawProps: SgDsLibraryDialogCloseProps) {
  const { className = '', label = 'Close dialog', onClick, type = 'button', ...props } = resolveWorkbenchModeProps(rawProps);
  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    onClick?.(event);
    if (!event.defaultPrevented) {
      event.currentTarget.closest('dialog')?.close();
    }
  };

  return (
    <button {...props} aria-label={label} className={['sg-ds-library-scope', 'dialog-close', className].filter(Boolean).join(' ')} onClick={handleClick} type={type}>
      <SgDsLibraryIcon name="x" size="1em" />
    </button>
  );
}

export default SgDsLibraryDialog;
