// frontend/src/components/Divider.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  label: { default: null },
  orientation: { default: 'horizontal' },
  variant: { default: 'solid' },
  inset: { default: 'none' },
  labelPosition: { default: 'center' },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'divider', attrs.class].filter(Boolean).join(' ')
)

const labeledClasses = computed(() =>
  ['sg-ds-library-scope', 'divider-labeled', attrs.class].filter(Boolean).join(' ')
)

const dataOrientation = computed(() =>
  props.orientation !== 'horizontal' ? props.orientation : undefined
)

const dataVariant = computed(() =>
  props.variant !== 'solid' ? props.variant : undefined
)

const dataInset = computed(() =>
  props.inset !== 'none' ? props.inset : undefined
)

const dataLabelPosition = computed(() =>
  props.labelPosition !== 'center' ? props.labelPosition : undefined
)

const attrsWithoutClass = computed(() => {
  const { class: _, ...rest } = attrs
  return rest
})
</script>

<template>
  <div
    v-if="props.label != null && props.orientation === 'horizontal'"
    v-bind="attrsWithoutClass"
    :class="labeledClasses"
    role="separator"
    :data-label-position="dataLabelPosition"
    :data-orientation="dataOrientation"
    :data-variant="dataVariant"
    :data-inset="dataInset"
  >
    <span class="divider-label">{{ props.label }}</span>
  </div>

  <div
    v-else-if="props.orientation === 'vertical'"
    v-bind="attrsWithoutClass"
    :class="classes"
    role="separator"
    aria-orientation="vertical"
    :data-orientation="dataOrientation"
    :data-variant="dataVariant"
    :data-inset="dataInset"
  />

  <hr
    v-else
    v-bind="attrsWithoutClass"
    :class="classes"
    :data-orientation="dataOrientation"
    :data-variant="dataVariant"
    :data-inset="dataInset"
  />
</template>

// frontend/src/libraries/sg-ds-library/components/Divider.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryDividerOrientation = 'horizontal' | 'vertical';
export type SgDsLibraryDividerVariant = 'solid' | 'dashed' | 'dotted';
export type SgDsLibraryDividerInset = 'none' | 'start' | 'end' | 'both';
export type SgDsLibraryDividerLabelPosition = 'left' | 'center' | 'right';

export type SgDsLibraryDividerProps = Omit<HTMLAttributes<HTMLElement>, 'children'> & {
  label?: ReactNode;
  orientation?: SgDsLibraryDividerOrientation;
  variant?: SgDsLibraryDividerVariant;
  inset?: SgDsLibraryDividerInset;
  /**
   * Position of the label along the divider. Horizontal-only — has no
   * effect when orientation is vertical (vertical dividers don't support
   * labels in the source design system).
   */
  labelPosition?: SgDsLibraryDividerLabelPosition;
};

export function SgDsLibraryDivider(rawProps: SgDsLibraryDividerProps) {
  const {
  className = '',
  inset = 'none',
  label,
  labelPosition = 'center',
  orientation = 'horizontal',
  variant = 'solid',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const dataAttrs = {
    'data-orientation': orientation === 'horizontal' ? undefined : orientation,
    'data-variant': variant === 'solid' ? undefined : variant,
    'data-inset': inset === 'none' ? undefined : inset,
  };

  if (label != null && orientation === 'horizontal') {
    return (
      <div
        {...props}
        className={['sg-ds-library-scope', 'divider-labeled', className].filter(Boolean).join(' ')}
        role="separator"
        data-label-position={labelPosition === 'center' ? undefined : labelPosition}
        {...dataAttrs}
      >
        <span className="divider-label">{label}</span>
      </div>
    );
  }

  if (orientation === 'vertical') {
    return (
      <div
        {...props}
        className={['sg-ds-library-scope', 'divider', className].filter(Boolean).join(' ')}
        role="separator"
        aria-orientation="vertical"
        {...dataAttrs}
      />
    );
  }

  return (
    <hr
      {...(props as HTMLAttributes<HTMLHRElement>)}
      className={['sg-ds-library-scope', 'divider', className].filter(Boolean).join(' ')}
      {...dataAttrs}
    />
  );
}

export default SgDsLibraryDivider;
