// frontend/src/components/Input.vue
<script setup>
import { computed, useAttrs, useId } from 'vue'
import Button from './Button.vue'
import Icon from './Icon.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  clearLabel: { default: 'Clear input' },
  clearable: { default: false },
  description: { default: undefined },
  disabled: { default: undefined },
  id: { default: undefined },
  inputClass: { default: '' },
  label: { default: undefined },
  labelPosition: { default: 'outside' },
  leadingIcon: { default: undefined },
  onClear: { default: undefined },
  readOnly: { default: undefined },
  shape: { default: 'default' },
  size: { default: 'md' },
  state: { default: 'default' },
  style: { default: undefined },
  trailingIcon: { default: undefined },
  type: { default: 'text' },
})

const generatedId = useId()
const inputId = computed(() => props.id ?? generatedId)
const descriptionId = computed(() => props.description ? `${inputId.value}-description` : undefined)

const hasInsideLabel = computed(() => Boolean(props.label) && props.labelPosition === 'inside')
const hasOutsideLabel = computed(() => Boolean(props.label) && props.labelPosition === 'outside')
const hasFieldChrome = computed(() => Boolean(props.label || props.description))

const hasLeadingIcon = computed(() => Boolean(props.leadingIcon))
const hasTrailingIcon = computed(() => !props.clearable && Boolean(props.trailingIcon))
const hasWrapper = computed(() => Boolean(hasLeadingIcon.value || hasTrailingIcon.value || props.clearable || hasInsideLabel.value))

const inputClasses = computed(() => [
  hasWrapper.value ? null : 'sg-ds-library-scope',
  'input',
  hasLeadingIcon.value ? 'input--with-leading-icon' : null,
  (hasTrailingIcon.value || props.clearable) ? 'input--with-trailing-icon' : null,
  hasInsideLabel.value ? 'input--with-inside-label' : null,
  props.inputClass,
  (hasWrapper.value || hasFieldChrome.value) ? null : attrs.class,
].filter(Boolean).join(' '))

const wrapperClasses = computed(() => [
  'sg-ds-library-scope',
  'input-wrapper',
  hasFieldChrome.value ? '' : attrs.class,
].filter(Boolean).join(' '))

const fieldClasses = computed(() => [
  'sg-ds-library-scope',
  'input-field',
  attrs.class,
].filter(Boolean).join(' '))

const inputStyle = computed(() => (hasWrapper.value || hasFieldChrome.value) ? undefined : props.style)
const wrapperStyle = computed(() => hasFieldChrome.value ? undefined : props.style)

const inputAttrs = computed(() => {
  const { class: _class, style: _style, ...rest } = attrs
  return rest
})
</script>

<template>
  <!-- With field chrome (label outside or description) -->
  <div
    v-if="hasFieldChrome"
    v-bind="{ ...inputAttrs, class: undefined, style: undefined }"
    :class="fieldClasses"
    :style="props.style"
    :data-label-position="props.labelPosition"
    :data-size="props.size"
    :data-state="props.state !== 'default' ? props.state : undefined"
  >
    <label
      v-if="hasOutsideLabel"
      class="input-label input-label-outside"
      :for="inputId"
    >{{ props.label }}</label>

    <!-- Wrapper with icons / inside label / clear button -->
    <div
      v-if="hasWrapper"
      :class="wrapperClasses"
      :style="wrapperStyle"
      :data-size="props.size"
      :data-label-position="hasInsideLabel ? 'inside' : undefined"
    >
      <span v-if="hasLeadingIcon" class="input-icon input-icon-leading" aria-hidden="true">
        <slot name="leadingIcon">
          <Icon :name="props.leadingIcon" size="1em" />
        </slot>
      </span>
      <label
        v-if="hasInsideLabel"
        class="input-label input-label-inside"
        :for="inputId"
      >{{ props.label }}</label>
      <input
        v-bind="inputAttrs"
        :id="inputId"
        :type="props.type"
        :class="inputClasses"
        :style="inputStyle"
        :data-size="props.size"
        :data-shape="props.shape === 'pill' ? 'pill' : undefined"
        :data-state="props.state !== 'default' ? props.state : undefined"
        :disabled="props.disabled"
        :aria-disabled="props.disabled || undefined"
        :aria-describedby="descriptionId"
        :readonly="props.readOnly"
      />
      <span v-if="hasTrailingIcon" class="input-icon input-icon-trailing" aria-hidden="true">
        <slot name="trailingIcon">
          <Icon :name="props.trailingIcon" size="1em" />
        </slot>
      </span>
      <Button
        v-if="props.clearable"
        type="button"
        class="input-clear"
        :aria-label="props.clearLabel"
        :disabled="props.disabled || props.readOnly"
        :icon-only="true"
        :label="props.clearLabel"
        leading-icon="x"
        shape="pill"
        :size="props.size"
        variant="soft"
        @click="props.onClear"
      />
    </div>

    <!-- Bare input (no wrapper needed) -->
    <input
      v-else
      v-bind="inputAttrs"
      :id="inputId"
      :type="props.type"
      :class="inputClasses"
      :style="inputStyle"
      :data-size="props.size"
      :data-shape="props.shape === 'pill' ? 'pill' : undefined"
      :data-state="props.state !== 'default' ? props.state : undefined"
      :disabled="props.disabled"
      :aria-disabled="props.disabled || undefined"
      :aria-describedby="descriptionId"
      :readonly="props.readOnly"
    />

    <span v-if="props.description" class="input-description" :id="descriptionId">{{ props.description }}</span>
  </div>

  <!-- With wrapper but no field chrome -->
  <div
    v-else-if="hasWrapper"
    v-bind="{ ...inputAttrs, class: undefined, style: undefined }"
    :class="wrapperClasses"
    :style="wrapperStyle"
    :data-size="props.size"
    :data-label-position="hasInsideLabel ? 'inside' : undefined"
  >
    <span v-if="hasLeadingIcon" class="input-icon input-icon-leading" aria-hidden="true">
      <slot name="leadingIcon">
        <Icon :name="props.leadingIcon" size="1em" />
      </slot>
    </span>
    <label
      v-if="hasInsideLabel"
      class="input-label input-label-inside"
      :for="inputId"
    >{{ props.label }}</label>
    <input
      v-bind="inputAttrs"
      :id="inputId"
      :type="props.type"
      :class="inputClasses"
      :style="inputStyle"
      :data-size="props.size"
      :data-shape="props.shape === 'pill' ? 'pill' : undefined"
      :data-state="props.state !== 'default' ? props.state : undefined"
      :disabled="props.disabled"
      :aria-disabled="props.disabled || undefined"
      :aria-describedby="descriptionId"
      :readonly="props.readOnly"
    />
    <span v-if="hasTrailingIcon" class="input-icon input-icon-trailing" aria-hidden="true">
      <slot name="trailingIcon">
        <Icon :name="props.trailingIcon" size="1em" />
      </slot>
    </span>
    <Button
      v-if="props.clearable"
      type="button"
      class="input-clear"
      :aria-label="props.clearLabel"
      :disabled="props.disabled || props.readOnly"
      :icon-only="true"
      :label="props.clearLabel"
      leading-icon="x"
      shape="pill"
      :size="props.size"
      variant="soft"
      @click="props.onClear"
    />
  </div>

  <!-- Bare input (no wrapper, no field chrome) -->
  <input
    v-else
    v-bind="{ ...inputAttrs, class: undefined, style: undefined }"
    :id="inputId"
    :type="props.type"
    :class="inputClasses"
    :style="inputStyle"
    :data-size="props.size"
    :data-shape="props.shape === 'pill' ? 'pill' : undefined"
    :data-state="props.state !== 'default' ? props.state : undefined"
    :disabled="props.disabled"
    :aria-disabled="props.disabled || undefined"
    :aria-describedby="descriptionId"
    :readonly="props.readOnly"
  />
</template>

// frontend/src/libraries/sg-ds-library/components/Input.tsx
import { useId, type InputHTMLAttributes, type ReactNode } from 'react';
import { SgDsLibraryButton } from './Button';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryInputSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryInputShape = 'default' | 'pill';
export type SgDsLibraryInputState = 'default' | 'error' | 'success';
export type SgDsLibraryInputType = 'text' | 'search' | 'email' | 'password' | 'url' | 'tel' | 'number';
export type SgDsLibraryInputLabelPosition = 'outside' | 'inside';

export type SgDsLibraryInputProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'children' | 'size' | 'type'> & {
  clearLabel?: string;
  clearable?: boolean;
  description?: ReactNode;
  label?: ReactNode;
  labelPosition?: SgDsLibraryInputLabelPosition;
  inputClassName?: string;
  /** Icon name from the project asset picker (workbench `control: 'icon'`). */
  leadingIcon?: string;
  /** Direct React node override for the leading slot. */
  leadingIconNode?: ReactNode;
  onClear?: () => void;
  shape?: SgDsLibraryInputShape;
  size?: SgDsLibraryInputSize;
  state?: SgDsLibraryInputState;
  /** Icon name from the project asset picker (workbench `control: 'icon'`). */
  trailingIcon?: string;
  /** Direct React node override for the trailing slot. */
  trailingIconNode?: ReactNode;
  type?: SgDsLibraryInputType;
};

function renderIconSlot(
  name: string | undefined,
  node: ReactNode | undefined,
): ReactNode {
  if (node !== undefined) return node;
  if (name) return <SgDsLibraryIcon name={name} size="1em" />;
  return null;
}

export function SgDsLibraryInput(rawProps: SgDsLibraryInputProps) {
  const {
  className = '',
  clearLabel = 'Clear input',
  clearable = false,
  description,
  disabled,
  id,
  inputClassName = '',
  label,
  labelPosition = 'outside',
  leadingIcon,
  leadingIconNode,
  onClear,
  readOnly,
  shape = 'default',
  size = 'md',
  state = 'default',
  style,
  trailingIcon,
  trailingIconNode,
  type = 'text',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const descriptionId = description ? `${inputId}-description` : undefined;
  const lead = renderIconSlot(leadingIcon, leadingIconNode);
  const trail = clearable ? null : renderIconSlot(trailingIcon, trailingIconNode);
  const hasInsideLabel = Boolean(label) && labelPosition === 'inside';
  const hasOutsideLabel = Boolean(label) && labelPosition === 'outside';
  const hasFieldChrome = Boolean(label || description);
  const hasWrapper = Boolean(lead || trail || clearable || hasInsideLabel);
  const inputClass = [
    hasWrapper ? null : 'sg-ds-library-scope',
    'input',
    lead ? 'input--with-leading-icon' : null,
    trail || clearable ? 'input--with-trailing-icon' : null,
    hasInsideLabel ? 'input--with-inside-label' : null,
    inputClassName,
    hasWrapper || hasFieldChrome ? null : className,
  ].filter(Boolean).join(' ');

  // Author styling (e.g. width) targets the component's root element — the
  // field/wrapper when present, otherwise the bare input — so the inner input
  // (always width:100%) fills the sized component instead of the style landing
  // on the input while the wrapper independently stretches.
  const inputStyle = hasWrapper || hasFieldChrome ? undefined : style;
  const wrapperStyle = hasFieldChrome ? undefined : style;

  const input = (
    <input
      {...props}
      id={inputId}
      type={type}
      className={inputClass}
      style={inputStyle}
      data-size={size}
      data-shape={shape === 'pill' ? 'pill' : undefined}
      data-state={state === 'default' ? undefined : state}
      disabled={disabled}
      aria-disabled={disabled || undefined}
      aria-describedby={descriptionId}
      readOnly={readOnly}
    />
  );

  const control = hasWrapper ? (
    <div
      className={['sg-ds-library-scope', 'input-wrapper', hasFieldChrome ? '' : className].filter(Boolean).join(' ')}
      style={wrapperStyle}
      data-size={size}
      data-label-position={hasInsideLabel ? 'inside' : undefined}
    >
      {lead ? (
        <span className="input-icon input-icon-leading" aria-hidden="true">
          {lead}
        </span>
      ) : null}
      {hasInsideLabel ? <label className="input-label input-label-inside" htmlFor={inputId}>{label}</label> : null}
      {input}
      {trail ? (
        <span className="input-icon input-icon-trailing" aria-hidden="true">
          {trail}
        </span>
      ) : null}
      {clearable ? (
        <SgDsLibraryButton
          type="button"
          className="input-clear"
          aria-label={clearLabel}
          disabled={disabled || readOnly}
          iconOnly
          label={clearLabel}
          leadingIcon="x"
          onClick={onClear}
          shape="pill"
          size={size}
          variant="soft"
        />
      ) : null}
    </div>
  ) : input;

  if (!hasFieldChrome) return control;

  return (
    <div
      className={['sg-ds-library-scope', 'input-field', className].filter(Boolean).join(' ')}
      style={style}
      data-label-position={labelPosition}
      data-size={size}
      data-state={state === 'default' ? undefined : state}
    >
      {hasOutsideLabel ? <label className="input-label input-label-outside" htmlFor={inputId}>{label}</label> : null}
      {control}
      {description ? <span className="input-description" id={descriptionId}>{description}</span> : null}
    </div>
  );
}

export default SgDsLibraryInput;
