// frontend/src/components/NavItem.vue
<script setup>
import { computed, useAttrs, useSlots } from 'vue'
import Icon from './Icon.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const slots = useSlots()

const props = defineProps({
  as: { type: String, default: undefined },
  current: { type: Boolean, default: false },
  icon: { type: String, default: undefined },
  label: { type: String, default: 'Navigation item' },
  selected: { type: Boolean, default: false },
  size: { type: String, default: 'md' },
  variant: { type: String, default: 'default' },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'nav-item', attrs.class].filter(Boolean).join(' ')
)

// Merge $attrs (minus class) with shared data/aria attributes into one object
const mergedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs
  return {
    ...rest,
    'aria-current': props.current ? 'page' : undefined,
    'aria-selected': props.selected ? true : undefined,
    'data-size': props.size,
    'data-selected': props.selected ? 'true' : undefined,
    'data-variant': props.variant !== 'default' ? props.variant : undefined,
  }
})

const buttonAttrs = computed(() => ({
  ...mergedAttrs.value,
  type: mergedAttrs.value.type ?? 'button',
}))

const hasIcon = computed(() => !!(slots.icon || props.icon))

const isButton = computed(() =>
  props.as === 'button' || (props.as === undefined && !attrs.href)
)

function handleAnchorClick(event) {
  const href = attrs.href
  if (!href || href === '#') event.preventDefault()
}
</script>

<template>
  <button
    v-if="isButton"
    v-bind="buttonAttrs"
    :class="classes"
  >
    <span v-if="hasIcon" class="nav-item-icon" aria-hidden="true">
      <slot name="icon">
        <Icon :name="props.icon" size="1em" />
      </slot>
    </span>
    <span class="nav-item-label">
      <slot>{{ props.label }}</slot>
    </span>
    <span v-if="$slots.tail" class="nav-item-tail">
      <slot name="tail" />
    </span>
  </button>

  <a
    v-else
    v-bind="mergedAttrs"
    :class="classes"
    @click="handleAnchorClick"
  >
    <span v-if="hasIcon" class="nav-item-icon" aria-hidden="true">
      <slot name="icon">
        <Icon :name="props.icon" size="1em" />
      </slot>
    </span>
    <span class="nav-item-label">
      <slot>{{ props.label }}</slot>
    </span>
    <span v-if="$slots.tail" class="nav-item-tail">
      <slot name="tail" />
    </span>
  </a>
</template>

// frontend/src/libraries/sg-ds-library/components/NavItem.tsx
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryIcon } from './Icon';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryNavItemSize = 'sm' | 'md' | 'lg';
export type SgDsLibraryNavItemVariant = 'default' | 'rail';

type CommonProps = {
  children?: ReactNode;
  current?: boolean;
  icon?: string;
  iconNode?: ReactNode;
  label?: ReactNode;
  selected?: boolean;
  size?: SgDsLibraryNavItemSize;
  tail?: ReactNode;
  variant?: SgDsLibraryNavItemVariant;
};

export type SgDsLibraryNavItemLinkProps = AnchorHTMLAttributes<HTMLAnchorElement> & CommonProps & {
  as?: 'a';
};

export type SgDsLibraryNavItemButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & CommonProps & {
  as: 'button';
};

export type SgDsLibraryNavItemProps = SgDsLibraryNavItemLinkProps | SgDsLibraryNavItemButtonProps;

function renderNavItemIcon(icon: string | undefined, iconNode: ReactNode | undefined): ReactNode {
  if (iconNode !== undefined) return iconNode;
  if (icon) return <SgDsLibraryIcon name={icon} size="1em" />;
  return null;
}

function hasNavItemContent(value: ReactNode): boolean {
  return value !== null && value !== undefined && value !== false && !(typeof value === 'string' && value.length === 0);
}

export function SgDsLibraryNavItem(rawProps: SgDsLibraryNavItemProps) {
  const {
  as,
  children,
  className = '',
  current = false,
  icon,
  iconNode,
  label = 'Navigation item',
  selected = false,
  size = 'md',
  tail,
  variant = 'default',
  ...domProps
} = resolveWorkbenchModeProps(rawProps);
  const content = hasNavItemContent(children) ? children : label;
  const resolvedIcon = renderNavItemIcon(icon, iconNode);
  const sharedClassName = ['sg-ds-library-scope', 'nav-item', className].filter(Boolean).join(' ');
  const sharedAttrs = {
    'aria-current': current ? 'page' as const : undefined,
    'aria-selected': selected ? true : undefined,
    'data-size': size,
    'data-selected': selected ? 'true' : undefined,
    'data-variant': variant === 'default' ? undefined : variant,
  };

  const inner = (
    <>
      {resolvedIcon ? <span className="nav-item-icon" aria-hidden="true">{resolvedIcon}</span> : null}
      <span className="nav-item-label">{content}</span>
      {tail ? <span className="nav-item-tail">{tail}</span> : null}
    </>
  );

  const anchorHref = (domProps as AnchorHTMLAttributes<HTMLAnchorElement>).href;

  if (as === 'button' || (as === undefined && anchorHref === undefined)) {
    const buttonProps = domProps as ButtonHTMLAttributes<HTMLButtonElement>;
    return (
      <button
        {...buttonProps}
        className={sharedClassName}
        type={buttonProps.type ?? 'button'}
        {...sharedAttrs}
      >
        {inner}
      </button>
    );
  }

  const { href, onClick, ...anchorProps } = domProps as AnchorHTMLAttributes<HTMLAnchorElement>;
  return (
    <a
      {...anchorProps}
      className={sharedClassName}
      href={href}
      onClick={(event) => {
        if (!href || href === '#') event.preventDefault();
        onClick?.(event);
      }}
      {...sharedAttrs}
    >
      {inner}
    </a>
  );
}

export default SgDsLibraryNavItem;
