// frontend/src/components/PostListItem.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Avatar from './Avatar.vue'
import MediaFrame from './MediaFrame.vue'

const attrs = useAttrs()

const props = defineProps({
  mediaFrameProps: { type: Object, default: () => ({}) },
  mediaAspect: { type: String, default: undefined },
  mediaSize: { type: String, default: undefined },
  mediaBackground: { type: String, default: undefined },
  mediaBackgroundToken: { type: String, default: undefined },
  mediaBackgroundTokenCollection: { type: String, default: undefined },
  mediaBadgeStatus: { type: String, default: undefined },
  mediaBadgeText: { type: String, default: undefined },
  mediaBadgeVariant: { type: String, default: undefined },
  mediaCaptionEyebrow: { type: String, default: undefined },
  mediaCaptionTitle: { type: String, default: undefined },
  mediaDuration: { type: String, default: undefined },
  mediaImageUrl: { type: String, default: undefined },
  mediaLive: { type: Boolean, default: undefined },
  mediaLiveLabel: { type: String, default: undefined },
  mediaLocked: { type: Boolean, default: undefined },
  mediaLockActionIcon: { type: String, default: undefined },
  mediaLockActionLabel: { type: String, default: undefined },
  mediaLockActionShape: { type: String, default: undefined },
  mediaLockActionSize: { type: String, default: undefined },
  mediaLockActionVariant: { type: String, default: undefined },
  mediaLockIcon: { type: String, default: undefined },
  mediaLockMessage: { type: String, default: undefined },
  mediaLockTitle: { type: String, default: undefined },
  mediaClassName: { type: String, default: '' },
  mediaOnUnlock: { type: Function, default: undefined },
  mediaPlayLabel: { type: String, default: undefined },
  mediaProgress: { type: [Number, String], default: undefined },
  mediaProgressLabel: { type: String, default: undefined },
  mediaShowGrain: { type: Boolean, default: undefined },
  mediaShowPlay: { type: Boolean, default: undefined },
  mediaSrc: { type: String, default: undefined },
  mediaStyle: { type: Object, default: undefined },
  mediaViewerCount: { type: String, default: undefined },
  mediaWidth: { type: [Number, String], default: undefined },
  thumbnailBackground: { type: String, default: undefined },
  thumbnailImageUrl: { type: String, default: undefined },
  thumbnailAspect: { type: String, default: undefined },
  thumbnailWidth: { type: [Number, String], default: undefined },
  avatarAlt: { type: String, default: undefined },
  avatarShape: { type: String, default: 'circle' },
  avatarSize: { type: String, default: 'xs' },
  avatarSrc: { type: String, default: undefined },
  avatarTone: { type: String, default: 'neutral' },
  showAvatar: { type: Boolean, default: true },
  showPlay: { type: Boolean, default: undefined },
  eyebrowColor: { type: String, default: undefined },
  eyebrowColorToken: { type: String, default: undefined },
  eyebrowColorTokenCollection: { type: String, default: undefined },
  initials: { type: String, default: undefined },
  size: { type: String, default: 'sm' },
  variant: { type: String, default: 'horizontal' },
})

function formatPostListItemCssDimension(value) {
  if (typeof value === 'number') return Number.isFinite(value) ? `${value}px` : null
  const trimmed = value?.trim()
  return trimmed || null
}

function toPostListItemMediaText(value) {
  if (typeof value === 'string' || typeof value === 'number') return String(value)
  return undefined
}

function formatPostListItemTokenReference(collectionId, tokenId) {
  const collection = collectionId?.trim()
  const token = tokenId?.trim()
  return collection && token ? `var(--ds-token-${collection}-${token})` : null
}

function toPostListItemCssColor(value) {
  const trimmed = value?.trim()
  return trimmed || undefined
}

const classes = computed(() =>
  ['sg-ds-library-scope', 'post-list-item', attrs.class].filter(Boolean).join(' ')
)

const mediaFrameClassName = computed(() => props.mediaFrameProps.className ?? '')
const mediaFrameStyle = computed(() => props.mediaFrameProps.style)

const mediaWidthCss = computed(() =>
  formatPostListItemCssDimension(
    props.mediaWidth ?? props.thumbnailWidth ?? mediaFrameStyle.value?.width ?? '128px'
  )
)

const hasAvatar = computed(() => props.showAvatar && Boolean(props.avatarSrc || props.initials))

const resolvedAvatarSize = computed(() => props.avatarSize ?? (props.size === 'lg' ? 'sm' : 'xs'))

const resolvedMediaAspect = computed(() =>
  props.mediaAspect ?? props.thumbnailAspect ?? props.mediaFrameProps.aspect ?? '16/9'
)

const resolvedMediaSize = computed(() =>
  props.mediaSize ?? props.mediaFrameProps.size ?? 'md'
)

const resolvedMediaBackground = computed(() =>
  props.mediaBackground ?? props.thumbnailBackground ?? props.mediaFrameProps.background ?? ''
)

const resolvedMediaBackgroundToken = computed(() =>
  props.mediaBackgroundToken ?? props.mediaFrameProps.backgroundToken ?? ''
)

const resolvedMediaBackgroundTokenCollection = computed(() =>
  props.mediaBackgroundTokenCollection ?? props.mediaFrameProps.backgroundTokenCollection ?? ''
)

const resolvedMediaSrc = computed(() =>
  props.mediaSrc ?? props.thumbnailImageUrl ?? props.mediaFrameProps.src ?? ''
)

const resolvedMediaImageUrl = computed(() =>
  props.mediaImageUrl ?? props.mediaFrameProps.imageUrl ?? ''
)

const resolvedMediaDuration = computed(() =>
  props.mediaDuration ?? props.mediaFrameProps.duration ?? ''
)

const resolvedMediaBadgeText = computed(() =>
  props.mediaBadgeText ?? props.mediaFrameProps.badgeText ?? ''
)

const resolvedMediaShowPlay = computed(() =>
  props.mediaShowPlay ?? props.showPlay ?? props.mediaFrameProps.showPlay ?? false
)

const resolvedMediaStyle = computed(() => ({
  ...(mediaFrameStyle.value ?? {}),
  ...(props.mediaStyle ?? {}),
  width: props.variant === 'vertical' ? '100%' : (mediaWidthCss.value ?? undefined),
}))

const eyebrowCssColor = computed(() =>
  toPostListItemCssColor(
    formatPostListItemTokenReference(props.eyebrowColorTokenCollection, props.eyebrowColorToken) ?? props.eyebrowColor
  )
)

const rootStyle = computed(() => {
  const base = attrs.style ?? {}
  if (eyebrowCssColor.value) {
    return { ...base, '--post-list-item-eyebrow-color': eyebrowCssColor.value }
  }
  return base
})

const mediaFrameClass = computed(() =>
  ['post-list-item-media', mediaFrameClassName.value, props.mediaClassName].filter(Boolean).join(' ')
)
</script>

<template>
  <div
    v-bind="{ ...$attrs, class: undefined, style: undefined }"
    :class="classes"
    :data-size="props.size"
    :data-variant="props.variant"
    :style="rootStyle"
  >
    <MediaFrame
      v-bind="props.mediaFrameProps"
      :aspect="resolvedMediaAspect"
      :size="resolvedMediaSize"
      :background="resolvedMediaBackground"
      :background-token="resolvedMediaBackgroundToken"
      :background-token-collection="resolvedMediaBackgroundTokenCollection"
      :badge-status="props.mediaBadgeStatus ?? props.mediaFrameProps.badgeStatus"
      :badge-text="resolvedMediaBadgeText"
      :badge-variant="props.mediaBadgeVariant ?? props.mediaFrameProps.badgeVariant"
      :caption-eyebrow="props.mediaCaptionEyebrow ?? props.mediaFrameProps.captionEyebrow ?? ''"
      :caption-title="props.mediaCaptionTitle ?? props.mediaFrameProps.captionTitle ?? ''"
      :class="mediaFrameClass"
      :duration="resolvedMediaDuration"
      :image-url="resolvedMediaImageUrl"
      :live="props.mediaLive ?? props.mediaFrameProps.live ?? false"
      :live-label="props.mediaLiveLabel ?? props.mediaFrameProps.liveLabel ?? ''"
      :locked="props.mediaLocked ?? props.mediaFrameProps.locked ?? false"
      :lock-action-icon="props.mediaLockActionIcon ?? props.mediaFrameProps.lockActionIcon ?? ''"
      :lock-action-label="props.mediaLockActionLabel ?? props.mediaFrameProps.lockActionLabel ?? ''"
      :lock-action-shape="props.mediaLockActionShape ?? props.mediaFrameProps.lockActionShape ?? 'pill'"
      :lock-action-size="props.mediaLockActionSize ?? props.mediaFrameProps.lockActionSize ?? 'sm'"
      :lock-action-variant="props.mediaLockActionVariant ?? props.mediaFrameProps.lockActionVariant ?? 'primary'"
      :lock-icon="props.mediaLockIcon ?? props.mediaFrameProps.lockIcon ?? ''"
      :lock-message="props.mediaLockMessage ?? props.mediaFrameProps.lockMessage ?? ''"
      :lock-title="props.mediaLockTitle ?? props.mediaFrameProps.lockTitle ?? ''"
      :on-unlock="props.mediaOnUnlock ?? props.mediaFrameProps.onUnlock"
      :progress="props.mediaProgress ?? props.mediaFrameProps.progress"
      :progress-label="props.mediaProgressLabel ?? props.mediaFrameProps.progressLabel ?? ''"
      :show-grain="props.mediaShowGrain ?? props.mediaFrameProps.showGrain ?? true"
      :show-play="resolvedMediaShowPlay"
      :src="resolvedMediaSrc"
      :style="resolvedMediaStyle"
      :viewer-count="props.mediaViewerCount ?? props.mediaFrameProps.viewerCount ?? ''"
      :play-label="props.mediaPlayLabel ?? props.mediaFrameProps.playLabel ?? ''"
    >
      <slot name="media-overlay" />
    </MediaFrame>

    <div
      class="post-list-item-body"
      :data-avatar="hasAvatar ? 'true' : 'false'"
      :data-avatar-size="hasAvatar ? resolvedAvatarSize : undefined"
    >
      <span class="post-list-item-main">
        <Avatar
          v-if="hasAvatar"
          :alt="props.avatarAlt"
          class="post-list-item-avatar"
          :initials="props.initials"
          :shape="props.avatarShape"
          :size="resolvedAvatarSize"
          :src="props.avatarSrc"
          :tone="props.avatarTone"
        />
        <span class="post-list-item-content">
          <span v-if="$slots.eyebrow" class="post-list-item-eyebrow">
            <slot name="eyebrow" />
          </span>
          <span class="post-list-item-title">
            <slot name="title">Post title</slot>
          </span>
          <span v-if="$slots.meta" class="post-list-item-meta">
            <slot name="meta" />
          </span>
        </span>
      </span>
      <span v-if="$slots.caption" class="post-list-item-caption">
        <slot name="caption" />
      </span>
    </div>
  </div>
</template>

// frontend/src/libraries/sg-ds-library/components/PostListItem.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';
import {
  SgDsLibraryAvatar,
  type SgDsLibraryAvatarShape,
  type SgDsLibraryAvatarSize,
  type SgDsLibraryAvatarTone,
} from './Avatar';
import type { SgDsLibraryBadgeStatus, SgDsLibraryBadgeVariant } from './Badge';
import type { SgDsLibraryButtonShape, SgDsLibraryButtonSize, SgDsLibraryButtonVariant } from './Button';
import {
  SgDsLibraryMediaFrame,
  type SgDsLibraryMediaFrameAspect,
  type SgDsLibraryMediaFrameProps,
  type SgDsLibraryMediaFrameSize,
} from './MediaFrame';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryPostListItemAspect = SgDsLibraryMediaFrameAspect;
export type SgDsLibraryPostListItemSize = 'lg' | 'sm';
export type SgDsLibraryPostListItemVariant = 'horizontal' | 'vertical';

export type SgDsLibraryPostListItemProps = HTMLAttributes<HTMLDivElement> & {
  mediaFrameProps?: SgDsLibraryMediaFrameProps;
  mediaAspect?: SgDsLibraryMediaFrameAspect;
  mediaSize?: SgDsLibraryMediaFrameSize;
  mediaBackground?: string;
  mediaBackgroundToken?: string;
  mediaBackgroundTokenCollection?: string;
  mediaBadgeStatus?: SgDsLibraryBadgeStatus;
  mediaBadgeText?: string;
  mediaBadgeVariant?: SgDsLibraryBadgeVariant;
  mediaCaptionEyebrow?: string;
  mediaCaptionTitle?: string;
  mediaDuration?: string;
  mediaImageUrl?: string;
  mediaLive?: boolean;
  mediaLiveLabel?: string;
  mediaLocked?: boolean;
  mediaLockActionIcon?: string;
  mediaLockActionLabel?: string;
  mediaLockActionShape?: SgDsLibraryButtonShape;
  mediaLockActionSize?: SgDsLibraryButtonSize;
  mediaLockActionVariant?: SgDsLibraryButtonVariant;
  mediaLockIcon?: string;
  mediaLockMessage?: string;
  mediaLockTitle?: string;
  mediaClassName?: string;
  mediaOnUnlock?: SgDsLibraryMediaFrameProps['onUnlock'];
  mediaOverlaySlot?: ReactNode;
  mediaPlayLabel?: string;
  mediaProgress?: number | string;
  mediaProgressLabel?: string;
  mediaShowGrain?: boolean;
  mediaShowPlay?: boolean;
  mediaSrc?: string;
  mediaStyle?: CSSProperties;
  mediaViewerCount?: string;
  mediaWidth?: number | string;
  /** @deprecated Use mediaBackground. */
  thumbnailBackground?: string;
  /** @deprecated Use mediaSrc or mediaImageUrl. */
  thumbnailImageUrl?: string;
  /** @deprecated Use mediaAspect. */
  thumbnailAspect?: SgDsLibraryPostListItemAspect;
  /** @deprecated Use mediaWidth. */
  thumbnailWidth?: number | string;
  avatarAlt?: string;
  avatarShape?: SgDsLibraryAvatarShape;
  avatarSize?: SgDsLibraryAvatarSize;
  avatarSrc?: string;
  avatarTone?: SgDsLibraryAvatarTone;
  badge?: ReactNode;
  duration?: ReactNode;
  showAvatar?: boolean;
  showPlay?: boolean;
  eyebrow?: ReactNode;
  eyebrowColor?: string;
  eyebrowColorToken?: string;
  eyebrowColorTokenCollection?: string;
  initials?: string;
  title?: ReactNode;
  meta?: ReactNode;
  caption?: ReactNode;
  size?: SgDsLibraryPostListItemSize;
  variant?: SgDsLibraryPostListItemVariant;
};

export function SgDsLibraryPostListItem(rawProps: SgDsLibraryPostListItemProps) {
  const {
    avatarAlt,
    avatarShape = 'circle',
    avatarSize = 'xs',
    avatarSrc,
    avatarTone = 'neutral',
    badge,
    caption,
    className = '',
    duration,
    eyebrow,
    eyebrowColor,
    eyebrowColorToken,
    eyebrowColorTokenCollection,
    initials,
    mediaAspect,
    mediaBackground,
    mediaBackgroundToken,
    mediaBackgroundTokenCollection,
    mediaBadgeStatus,
    mediaBadgeText,
    mediaBadgeVariant,
    mediaCaptionEyebrow,
    mediaCaptionTitle,
    mediaClassName = '',
    mediaDuration,
    mediaFrameProps = {},
    mediaImageUrl,
    mediaLive,
    mediaLiveLabel,
    mediaLocked,
    mediaLockActionIcon,
    mediaLockActionLabel,
    mediaLockActionShape,
    mediaLockActionSize,
    mediaLockActionVariant,
    mediaLockIcon,
    mediaLockMessage,
    mediaLockTitle,
    mediaOnUnlock,
    mediaOverlaySlot,
    mediaPlayLabel,
    mediaProgress,
    mediaProgressLabel,
    mediaShowGrain,
    mediaShowPlay,
    mediaSize,
    mediaSrc,
    mediaStyle,
    mediaViewerCount,
    mediaWidth,
    meta,
    showAvatar = true,
    showPlay,
    size = 'sm',
    style,
    thumbnailAspect,
    thumbnailBackground,
    thumbnailImageUrl,
    thumbnailWidth,
    title = 'Post title',
    variant = 'horizontal',
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const mediaFrameClassName = mediaFrameProps.className ?? '';
  const mediaFrameStyle = mediaFrameProps.style;
  const mediaWidthCss = formatPostListItemCssDimension(
    mediaWidth ?? thumbnailWidth ?? mediaFrameStyle?.width ?? '128px',
  );
  const hasAvatar = showAvatar && Boolean(avatarSrc || initials);
  const resolvedAvatarSize = avatarSize ?? (size === 'lg' ? 'sm' : 'xs');
  const resolvedMediaAspect = mediaAspect ?? thumbnailAspect ?? mediaFrameProps.aspect ?? '16/9';
  const resolvedMediaSize = mediaSize ?? mediaFrameProps.size ?? 'md';
  const resolvedMediaBackground = mediaBackground ?? thumbnailBackground ?? mediaFrameProps.background ?? '';
  const resolvedMediaBackgroundToken = mediaBackgroundToken ?? mediaFrameProps.backgroundToken ?? '';
  const resolvedMediaBackgroundTokenCollection = mediaBackgroundTokenCollection ?? mediaFrameProps.backgroundTokenCollection ?? '';
  const resolvedMediaSrc = mediaSrc ?? thumbnailImageUrl ?? mediaFrameProps.src ?? '';
  const resolvedMediaImageUrl = mediaImageUrl ?? mediaFrameProps.imageUrl ?? '';
  const resolvedMediaDuration = mediaDuration ?? toPostListItemMediaText(duration) ?? mediaFrameProps.duration ?? '';
  const resolvedMediaBadgeText = mediaBadgeText ?? toPostListItemMediaText(badge) ?? mediaFrameProps.badgeText ?? '';
  const resolvedMediaShowPlay = mediaShowPlay ?? showPlay ?? mediaFrameProps.showPlay ?? false;
  const resolvedMediaStyle = {
    ...(mediaFrameStyle ?? {}),
    ...(mediaStyle ?? {}),
    width: variant === 'vertical' ? '100%' : mediaWidthCss ?? undefined,
  } as CSSProperties;
  const eyebrowCssColor = toPostListItemCssColor(
    formatPostListItemTokenReference(eyebrowColorTokenCollection, eyebrowColorToken) ?? eyebrowColor,
  );
  const rootStyle = eyebrowCssColor
    ? ({
        ...style,
        '--post-list-item-eyebrow-color': eyebrowCssColor,
      } as CSSProperties)
    : style;
  return (
    <div
      {...props}
      className={['sg-ds-library-scope', 'post-list-item', className].filter(Boolean).join(' ')}
      data-size={size}
      data-variant={variant}
      style={rootStyle}
    >
      <SgDsLibraryMediaFrame
        {...mediaFrameProps}
        aspect={resolvedMediaAspect}
        size={resolvedMediaSize}
        background={resolvedMediaBackground}
        backgroundToken={resolvedMediaBackgroundToken}
        backgroundTokenCollection={resolvedMediaBackgroundTokenCollection}
        badgeStatus={mediaBadgeStatus ?? mediaFrameProps.badgeStatus}
        badgeText={resolvedMediaBadgeText}
        badgeVariant={mediaBadgeVariant ?? mediaFrameProps.badgeVariant}
        captionEyebrow={mediaCaptionEyebrow ?? mediaFrameProps.captionEyebrow ?? ''}
        captionTitle={mediaCaptionTitle ?? mediaFrameProps.captionTitle ?? ''}
        className={['post-list-item-media', mediaFrameClassName, mediaClassName].filter(Boolean).join(' ')}
        duration={resolvedMediaDuration}
        imageUrl={resolvedMediaImageUrl}
        live={mediaLive ?? mediaFrameProps.live ?? false}
        liveLabel={mediaLiveLabel ?? mediaFrameProps.liveLabel ?? ''}
        locked={mediaLocked ?? mediaFrameProps.locked ?? false}
        lockActionIcon={mediaLockActionIcon ?? mediaFrameProps.lockActionIcon ?? ''}
        lockActionLabel={mediaLockActionLabel ?? mediaFrameProps.lockActionLabel ?? ''}
        lockActionShape={mediaLockActionShape ?? mediaFrameProps.lockActionShape ?? 'pill'}
        lockActionSize={mediaLockActionSize ?? mediaFrameProps.lockActionSize ?? 'sm'}
        lockActionVariant={mediaLockActionVariant ?? mediaFrameProps.lockActionVariant ?? 'primary'}
        lockIcon={mediaLockIcon ?? mediaFrameProps.lockIcon ?? ''}
        lockMessage={mediaLockMessage ?? mediaFrameProps.lockMessage ?? ''}
        lockTitle={mediaLockTitle ?? mediaFrameProps.lockTitle ?? ''}
        onUnlock={mediaOnUnlock ?? mediaFrameProps.onUnlock}
        overlaySlot={mediaOverlaySlot ?? mediaFrameProps.overlaySlot}
        playLabel={mediaPlayLabel ?? mediaFrameProps.playLabel ?? ''}
        progress={mediaProgress ?? mediaFrameProps.progress}
        progressLabel={mediaProgressLabel ?? mediaFrameProps.progressLabel ?? ''}
        showGrain={mediaShowGrain ?? mediaFrameProps.showGrain ?? true}
        showPlay={resolvedMediaShowPlay}
        src={resolvedMediaSrc}
        style={resolvedMediaStyle}
        viewerCount={mediaViewerCount ?? mediaFrameProps.viewerCount ?? ''}
      />
      <div
        className="post-list-item-body"
        data-avatar={hasAvatar ? 'true' : 'false'}
        data-avatar-size={hasAvatar ? resolvedAvatarSize : undefined}
      >
        <span className="post-list-item-main">
          {hasAvatar ? (
            <SgDsLibraryAvatar
              alt={avatarAlt}
              className="post-list-item-avatar"
              initials={initials}
              shape={avatarShape}
              size={resolvedAvatarSize}
              src={avatarSrc}
              tone={avatarTone}
            />
          ) : null}
          <span className="post-list-item-content">
            {eyebrow ? <span className="post-list-item-eyebrow">{eyebrow}</span> : null}
            <span className="post-list-item-title">{title}</span>
            {meta ? <span className="post-list-item-meta">{meta}</span> : null}
          </span>
        </span>
        {caption ? <span className="post-list-item-caption">{caption}</span> : null}
      </div>
    </div>
  );
}

function formatPostListItemCssDimension(value: number | string | undefined): string | null {
  if (typeof value === 'number') return Number.isFinite(value) ? `${value}px` : null;
  const trimmed = value?.trim();
  return trimmed || null;
}

function toPostListItemMediaText(value: ReactNode | undefined): string | undefined {
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  return undefined;
}

function formatPostListItemTokenReference(collectionId: string | undefined, tokenId: string | undefined): string | null {
  const collection = collectionId?.trim();
  const token = tokenId?.trim();
  return collection && token ? `var(--ds-token-${collection}-${token})` : null;
}

function toPostListItemCssColor(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed || undefined;
}

export default SgDsLibraryPostListItem;
