// frontend/src/components/Rail.vue
<script setup>
import { computed, useAttrs } from 'vue'
import Divider from './Divider.vue'
import FollowRow from './FollowRow.vue'
import Icon from './Icon.vue'
import Link from './Link.vue'
import NavItem from './NavItem.vue'
import RailFooter from './RailFooter.vue'
import RailGroup from './RailGroup.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  activeItem: { default: 'home' },
  brand: { default: 'StudioGrid' },
  collapsed: { default: false },
  footerPrimaryLabel: { default: 'Dark mode' },
  footerSecondaryLabel: { default: 'Settings' },
  showFollowing: { default: true },
  showFooter: { default: true },
  size: { default: 'default' },
  subtitle: { default: 'Creator studio' },
})

const ariaLabel = computed(() => attrs['aria-label'] ?? `${props.brand} navigation`)

const classes = computed(() =>
  ['sg-ds-library-scope', 'app-rail', attrs.class].filter(Boolean).join(' ')
)
</script>

<template>
  <aside
    v-bind="{ ...attrs, class: undefined }"
    :aria-label="ariaLabel"
    :class="classes"
    :data-collapsed="props.collapsed || undefined"
    :data-size="props.size !== 'default' ? props.size : undefined"
  >
    <slot>
      <header class="rail-head">
        <div class="rail-brand" :aria-label="props.brand">
          <span class="rail-brand-mark" aria-hidden="true">
            <Icon name="sparkles" size="1em" />
          </span>
          <span class="rail-brand-text">
            <span class="rail-brand-name">{{ props.brand }}</span>
            <span v-if="props.subtitle" class="rail-brand-subtitle">{{ props.subtitle }}</span>
          </span>
        </div>
      </header>

      <div class="rail-body">
        <RailGroup aria-label="Primary">
          <NavItem :current="props.activeItem === 'home'" icon="house" label="Home" variant="rail" />
          <NavItem :current="props.activeItem === 'live'" icon="radio" label="Live" tail="12" variant="rail" />
          <NavItem :current="props.activeItem === 'library'" icon="library" label="Library" variant="rail" />
          <NavItem :current="props.activeItem === 'messages'" icon="bell" label="Messages" tail="3" variant="rail" />
        </RailGroup>

        <template v-if="props.showFollowing">
          <Divider inset="both" />
          <RailGroup label="Following" variant="follow">
            <template #tail>
              <Link size="sm" variant="subtle">All</Link>
            </template>
            <FollowRow initials="HL" name="Hailey Luna" state="live" />
            <FollowRow avatar-tone="teal" initials="NV" name="NeoVoice" />
            <FollowRow avatar-tone="violet" initials="MX" name="Mika X" />
          </RailGroup>
        </template>
      </div>

      <RailFooter
        v-if="props.showFooter"
        :primary-label="props.footerPrimaryLabel"
        :secondary-label="props.footerSecondaryLabel"
      />
    </slot>
  </aside>
</template>

// frontend/src/libraries/sg-ds-library/components/Rail.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { SgDsLibraryDivider } from './Divider';
import { SgDsLibraryFollowRow } from './FollowRow';
import { SgDsLibraryIcon } from './Icon';
import { SgDsLibraryLink } from './Link';
import { SgDsLibraryNavItem } from './NavItem';
import { SgDsLibraryRailFooter } from './RailFooter';
import { SgDsLibraryRailGroup } from './RailGroup';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibraryRailActiveItem = 'home' | 'live' | 'library' | 'messages';
export type SgDsLibraryRailSize = 'compact' | 'default' | 'wide';

export type SgDsLibraryRailProps = HTMLAttributes<HTMLElement> & {
  activeItem?: SgDsLibraryRailActiveItem;
  brand?: string;
  children?: ReactNode;
  collapsed?: boolean;
  footerPrimaryLabel?: string;
  footerSecondaryLabel?: string;
  showFollowing?: boolean;
  showFooter?: boolean;
  size?: SgDsLibraryRailSize;
  subtitle?: string;
};

export function SgDsLibraryRail(rawProps: SgDsLibraryRailProps) {
  const {
  activeItem = 'home',
  brand = 'StudioGrid',
  children,
  className = '',
  collapsed = false,
  footerPrimaryLabel = 'Dark mode',
  footerSecondaryLabel = 'Settings',
  showFollowing = true,
  showFooter = true,
  size = 'default',
  subtitle = 'Creator studio',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const ariaLabel = props['aria-label'] ?? `${brand} navigation`;

  return (
    <aside
      {...props}
      aria-label={ariaLabel}
      className={['sg-ds-library-scope', 'app-rail', className].filter(Boolean).join(' ')}
      data-collapsed={collapsed || undefined}
      data-size={size === 'default' ? undefined : size}
    >
      {children ?? (
        <>
          <header className="rail-head">
            <div className="rail-brand" aria-label={brand}>
              <span className="rail-brand-mark" aria-hidden="true">
                <SgDsLibraryIcon name="sparkles" size="1em" />
              </span>
              <span className="rail-brand-text">
                <span className="rail-brand-name">{brand}</span>
                {subtitle ? <span className="rail-brand-subtitle">{subtitle}</span> : null}
              </span>
            </div>
          </header>

          <div className="rail-body">
            <SgDsLibraryRailGroup aria-label="Primary">
              <SgDsLibraryNavItem current={activeItem === 'home'} icon="house" label="Home" variant="rail" />
              <SgDsLibraryNavItem current={activeItem === 'live'} icon="radio" label="Live" tail="12" variant="rail" />
              <SgDsLibraryNavItem current={activeItem === 'library'} icon="library" label="Library" variant="rail" />
              <SgDsLibraryNavItem current={activeItem === 'messages'} icon="bell" label="Messages" tail="3" variant="rail" />
            </SgDsLibraryRailGroup>

            {showFollowing ? (
              <>
                <SgDsLibraryDivider inset="both" />
                <SgDsLibraryRailGroup
                  label="Following"
                  tailSlot={<SgDsLibraryLink size="sm" variant="subtle">All</SgDsLibraryLink>}
                  variant="follow"
                >
                  <SgDsLibraryFollowRow initials="HL" name="Hailey Luna" state="live" />
                  <SgDsLibraryFollowRow avatarTone="teal" initials="NV" name="NeoVoice" />
                  <SgDsLibraryFollowRow avatarTone="violet" initials="MX" name="Mika X" />
                </SgDsLibraryRailGroup>
              </>
            ) : null}
          </div>

          {showFooter ? (
            <SgDsLibraryRailFooter
              primaryLabel={footerPrimaryLabel}
              secondaryLabel={footerSecondaryLabel}
            />
          ) : null}
        </>
      )}
    </aside>
  );
}

export default SgDsLibraryRail;
