// frontend/src/components/Switch.vue
<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const props = defineProps({
  inputClassName: { type: String, default: '' },
  label: { type: String, default: 'Enable notifications' },
  size: { type: String, default: 'md' },
  disabled: { type: Boolean, default: undefined },
})

const labelClasses = computed(() =>
  ['sg-ds-library-scope', 'switch-label', attrs.class].filter(Boolean).join(' ')
)

const inputClasses = computed(() =>
  ['switch', 'switch-input', props.inputClassName].filter(Boolean).join(' ')
)
</script>

<template>
  <label
    v-bind="{ ...($attrs), class: undefined }"
    :class="labelClasses"
    :data-size="props.size"
    :data-disabled="props.disabled || undefined"
  >
    <input
      type="checkbox"
      role="switch"
      :class="inputClasses"
      :data-size="props.size"
      :disabled="props.disabled"
      :aria-disabled="props.disabled || undefined"
    />
    <span class="switch-track" :data-size="props.size" aria-hidden="true">
      <span class="switch-thumb" />
    </span>
    <span class="switch-label-text">{{ props.label }}</span>
  </label>
</template>

// frontend/src/libraries/sg-ds-library/components/Switch.tsx
import type { InputHTMLAttributes, ReactNode } from 'react';
import { resolveWorkbenchModeProps } from './_shared';

export type SgDsLibrarySwitchSize = 'sm' | 'md' | 'lg';

export type SgDsLibrarySwitchProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'children' | 'size' | 'type'> & {
  inputClassName?: string;
  label?: ReactNode;
  size?: SgDsLibrarySwitchSize;
};

export function SgDsLibrarySwitch(rawProps: SgDsLibrarySwitchProps) {
  const {
  className = '',
  disabled,
  inputClassName = '',
  label = 'Enable notifications',
  size = 'md',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <label
      className={['sg-ds-library-scope', 'switch-label', className].filter(Boolean).join(' ')}
      data-size={size}
      data-disabled={disabled || undefined}
    >
      <input
        {...props}
        type="checkbox"
        role="switch"
        className={['switch', 'switch-input', inputClassName].filter(Boolean).join(' ')}
        data-size={size}
        disabled={disabled}
        aria-disabled={disabled || undefined}
      />
      <span className="switch-track" data-size={size} aria-hidden="true">
        <span className="switch-thumb" />
      </span>
      <span className="switch-label-text">{label}</span>
    </label>
  );
}

export default SgDsLibrarySwitch;
