// frontend/src/components/UserCard.vue
<script setup>
import { computed, useAttrs, useSlots } from 'vue'
import UserBlock from './UserBlock.vue'
import CreditBalanceCard from './CreditBalanceCard.vue'

const attrs = useAttrs()
const slots = useSlots()

const props = defineProps({
  // Identity props (passed down to UserBlock)
  action1AriaLabel: { default: undefined },
  action1Icon: { default: undefined },
  action1Label: { default: undefined },
  action1Variant: { default: undefined },
  action2AriaLabel: { default: undefined },
  action2Icon: { default: undefined },
  action2Label: { default: undefined },
  action2Variant: { default: undefined },
  action3AriaLabel: { default: undefined },
  action3Icon: { default: undefined },
  action3Label: { default: undefined },
  action3Variant: { default: undefined },
  avatarAlt: { default: undefined },
  avatarQuietStatus: { default: undefined },
  avatarShape: { default: undefined },
  avatarSize: { default: undefined },
  avatarSrc: { default: undefined },
  avatarStatus: { default: undefined },
  avatarStatusLabel: { default: undefined },
  avatarTone: { default: undefined },
  direction: { default: undefined },
  initials: { default: 'HL' },
  meta: { default: 'Creator · live now' },
  name: { default: 'Hailey Luna' },
  size: { default: undefined },
  verified: { default: true },
  // Card-level props
  tint: { default: 'sunken' },
  variant: { default: 'solid' },
})

const classes = computed(() =>
  ['sg-ds-library-scope', 'card', 'user-card', attrs.class].filter(Boolean).join(' ')
)

const headClasses = computed(() =>
  ['sg-ds-library-scope', 'user-card-head'].filter(Boolean).join(' ')
)

// Build identity props to pass to UserBlock, omitting undefined values
const identityProps = computed(() => {
  const raw = {
    action1AriaLabel: props.action1AriaLabel,
    action1Icon: props.action1Icon,
    action1Label: props.action1Label,
    action1Variant: props.action1Variant,
    action2AriaLabel: props.action2AriaLabel,
    action2Icon: props.action2Icon,
    action2Label: props.action2Label,
    action2Variant: props.action2Variant,
    action3AriaLabel: props.action3AriaLabel,
    action3Icon: props.action3Icon,
    action3Label: props.action3Label,
    action3Variant: props.action3Variant,
    avatarAlt: props.avatarAlt,
    avatarQuietStatus: props.avatarQuietStatus,
    avatarShape: props.avatarShape,
    avatarSize: props.avatarSize,
    avatarSrc: props.avatarSrc,
    avatarStatus: props.avatarStatus,
    avatarStatusLabel: props.avatarStatusLabel,
    avatarTone: props.avatarTone,
    direction: props.direction,
    initials: props.initials,
    meta: props.meta,
    name: props.name,
    size: props.size,
    verified: props.verified,
  }
  return Object.fromEntries(Object.entries(raw).filter(([, v]) => v !== undefined))
})

// Omit "more" action3 props from head's UserBlock
const headUserBlockProps = computed(() => {
  const action3Icon = typeof identityProps.value.action3Icon === 'string'
    ? identityProps.value.action3Icon.trim()
    : ''
  const isMoreAction = ['ellipsis', 'ellipsis-vertical', 'more-horizontal', 'more-vertical'].includes(action3Icon)
  if (!isMoreAction) return identityProps.value
  const { action3AriaLabel, action3Icon: _icon, action3Label, action3Variant, ...rest } = identityProps.value
  return rest
})
</script>

<template>
  <article
    v-bind="{ ...$attrs, class: undefined }"
    :class="classes"
    :data-variant="props.variant"
  >
    <slot>
      <!-- Default layout when no slot content is provided -->
      <!-- Head section -->
      <header :class="headClasses">
        <slot name="head">
          <UserBlock
            :initials="headUserBlockProps.initials ?? 'HL'"
            :meta="headUserBlockProps.meta ?? 'Creator'"
            :name="headUserBlockProps.name ?? 'Hailey Luna'"
            :verified="headUserBlockProps.verified ?? true"
            v-bind="headUserBlockProps"
          />
        </slot>
      </header>

      <!-- Stats section (default tint) -->
      <section
        class="sg-ds-library-scope user-card-section"
        :data-tint="undefined"
      >
        <slot name="stats">
          <dl class="sg-ds-library-scope user-card-stats">
            <slot name="stats-items">
              <div class="sg-ds-library-scope user-card-stat">
                <dd class="user-card-stat-value">128</dd>
                <dt class="user-card-stat-label">포스트</dt>
              </div>
              <div class="sg-ds-library-scope user-card-stat">
                <dd class="user-card-stat-value">12.4K</dd>
                <dt class="user-card-stat-label">팔로워</dt>
              </div>
              <div class="sg-ds-library-scope user-card-stat">
                <dd class="user-card-stat-value">384</dd>
                <dt class="user-card-stat-label">팔로잉</dt>
              </div>
            </slot>
          </dl>
        </slot>
      </section>

      <!-- Section slot (tinted) -->
      <section
        class="sg-ds-library-scope user-card-section"
        :data-tint="props.tint !== 'default' ? props.tint : undefined"
      >
        <slot name="section">
          <CreditBalanceCard />
        </slot>
      </section>
    </slot>
  </article>
</template>

// frontend/src/libraries/sg-ds-library/components/UserCard.tsx
import { Children, cloneElement, isValidElement, type HTMLAttributes, type ReactElement, type ReactNode } from 'react';
import type { SgDsLibraryCardVariant } from './Card';
import { SgDsLibraryCreditBalanceCard } from './CreditBalanceCard';
import { resolveWorkbenchModeProps } from './_shared';
import {
  SgDsLibraryUserBlock,
  type SgDsLibraryUserBlockProps,
} from './UserBlock';

export type SgDsLibraryUserCardSectionTint = 'default' | 'sunken' | 'brand';
type SgDsLibraryUserCardIdentityProps = Pick<
  SgDsLibraryUserBlockProps,
  | 'action1AriaLabel'
  | 'action1Icon'
  | 'action1Label'
  | 'action1Variant'
  | 'action2AriaLabel'
  | 'action2Icon'
  | 'action2Label'
  | 'action2Variant'
  | 'action3AriaLabel'
  | 'action3Icon'
  | 'action3Label'
  | 'action3Variant'
  | 'avatarAlt'
  | 'avatarQuietStatus'
  | 'avatarShape'
  | 'avatarSize'
  | 'avatarSrc'
  | 'avatarStatus'
  | 'avatarStatusLabel'
  | 'avatarTone'
  | 'direction'
  | 'initials'
  | 'meta'
  | 'name'
  | 'size'
  | 'verified'
>;

export type SgDsLibraryUserCardProps = HTMLAttributes<HTMLElement> & SgDsLibraryUserCardIdentityProps & {
  children?: ReactNode;
  sectionSlot?: ReactNode;
  tint?: SgDsLibraryUserCardSectionTint;
  variant?: SgDsLibraryCardVariant;
};

export type SgDsLibraryUserCardHeadProps = HTMLAttributes<HTMLElement> & SgDsLibraryUserCardIdentityProps & {
  children?: ReactNode;
};

export type SgDsLibraryUserCardSectionProps = HTMLAttributes<HTMLElement> & {
  children?: ReactNode;
  tint?: SgDsLibraryUserCardSectionTint;
};

export type SgDsLibraryUserCardStatsProps = HTMLAttributes<HTMLDListElement> & {
  children?: ReactNode;
  followersLabel?: ReactNode;
  followersValue?: ReactNode;
  followingLabel?: ReactNode;
  followingValue?: ReactNode;
  postsLabel?: ReactNode;
  postsValue?: ReactNode;
};

export type SgDsLibraryUserCardStatProps = HTMLAttributes<HTMLDivElement> & {
  label?: ReactNode;
  value?: ReactNode;
};

export function SgDsLibraryUserCard(rawProps: SgDsLibraryUserCardProps) {
  const {
  action1AriaLabel,
  action1Icon,
  action1Label,
  action1Variant,
  action2AriaLabel,
  action2Icon,
  action2Label,
  action2Variant,
  action3AriaLabel,
  action3Icon,
  action3Label,
  action3Variant,
  avatarAlt,
  avatarQuietStatus,
  avatarShape,
  avatarSize,
  avatarSrc,
  avatarStatus,
  avatarStatusLabel,
  avatarTone,
  children,
  className = '',
  direction,
  initials,
  meta,
  name,
  sectionSlot,
  tint = 'sunken',
  variant = 'solid',
  size,
  verified,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const identityProps = getDefinedProps({
    action1AriaLabel,
    action1Icon,
    action1Label,
    action1Variant,
    action2AriaLabel,
    action2Icon,
    action2Label,
    action2Variant,
    action3AriaLabel,
    action3Icon,
    action3Label,
    action3Variant,
    avatarAlt,
    avatarQuietStatus,
    avatarShape,
    avatarSize,
    avatarSrc,
    avatarStatus,
    avatarStatusLabel,
    avatarTone,
    direction,
    initials,
    meta,
    name,
    size,
    verified,
  });
  const resolvedIdentityProps = {
    initials: 'HL',
    meta: 'Creator · live now',
    name: 'Hailey Luna',
    verified: true,
    ...identityProps,
  };
  const hasProvidedChildren = hasRenderableChildren(children);

  return (
    <article
      {...props}
      className={['sg-ds-library-scope', 'card', 'user-card', className].filter(Boolean).join(' ')}
      data-variant={variant}
    >
      {hasProvidedChildren ? enhanceUserCardChildren(children, identityProps, tint) : (
        <>
          <SgDsLibraryUserCardHead {...resolvedIdentityProps} />
          <SgDsLibraryUserCardSection tint="default">
            <SgDsLibraryUserCardStats />
          </SgDsLibraryUserCardSection>
          <SgDsLibraryUserCardSection tint={tint}>
            {sectionSlot ?? <SgDsLibraryCreditBalanceCard />}
          </SgDsLibraryUserCardSection>
        </>
      )}
    </article>
  );
}

export function SgDsLibraryUserCardHead(rawProps: SgDsLibraryUserCardHeadProps) {
  const {
  action1AriaLabel,
  action1Icon,
  action1Label,
  action1Variant,
  action2AriaLabel,
  action2Icon,
  action2Label,
  action2Variant,
  action3AriaLabel,
  action3Icon,
  action3Label,
  action3Variant,
  avatarAlt,
  avatarQuietStatus,
  avatarShape,
  avatarSize,
  avatarSrc,
  avatarStatus,
  avatarStatusLabel,
  avatarTone,
  children,
  className = '',
  direction,
  initials,
  meta,
  name,
  size,
  verified,
  ...props
} = resolveWorkbenchModeProps(rawProps);
  const identityProps = getDefinedProps({
    action1AriaLabel,
    action1Icon,
    action1Label,
    action1Variant,
    action2AriaLabel,
    action2Icon,
    action2Label,
    action2Variant,
    action3AriaLabel,
    action3Icon,
    action3Label,
    action3Variant,
    avatarAlt,
    avatarQuietStatus,
    avatarShape,
    avatarSize,
    avatarSrc,
    avatarStatus,
    avatarStatusLabel,
    avatarTone,
    direction,
    initials,
    meta,
    name,
    size,
    verified,
  });
  const identityContent = hasRenderableChildren(children)
    ? enhanceUserCardHeadChildren(children, identityProps)
    : <SgDsLibraryUserBlock initials="HL" meta="Creator" name="Hailey Luna" verified {...omitUserCardHeadMoreAction(identityProps)} />;

  return <header {...props} className={['sg-ds-library-scope', 'user-card-head', className].filter(Boolean).join(' ')}>{identityContent}</header>;
}

export function SgDsLibraryUserCardSection(rawProps: SgDsLibraryUserCardSectionProps) {
  const {
  children,
  className = '',
  tint = 'default',
  ...props
} = resolveWorkbenchModeProps(rawProps);
  return (
    <section {...props} className={['sg-ds-library-scope', 'user-card-section', className].filter(Boolean).join(' ')} data-tint={tint === 'default' ? undefined : tint}>
      {children}
    </section>
  );
}

export function SgDsLibraryUserCardStats(rawProps: SgDsLibraryUserCardStatsProps) {
  const {
    children,
    className = '',
    followersLabel = '팔로워',
    followersValue = '12.4K',
    followingLabel = '팔로잉',
    followingValue = '384',
    postsLabel = '포스트',
    postsValue = '128',
    ...props
  } = resolveWorkbenchModeProps(rawProps);
  const content = hasRenderableChildren(children) ? children : (
    <>
      <SgDsLibraryUserCardStat label={postsLabel} value={postsValue} />
      <SgDsLibraryUserCardStat label={followersLabel} value={followersValue} />
      <SgDsLibraryUserCardStat label={followingLabel} value={followingValue} />
    </>
  );

  return (
    <dl {...props} className={['sg-ds-library-scope', 'user-card-stats', className].filter(Boolean).join(' ')}>
      {content}
    </dl>
  );
}

export function SgDsLibraryUserCardStat(rawProps: SgDsLibraryUserCardStatProps) {
  const {
    className = '',
    label = '팔로워',
    value = '12.4K',
    ...props
  } = resolveWorkbenchModeProps(rawProps);

  return (
    <div {...props} className={['sg-ds-library-scope', 'user-card-stat', className].filter(Boolean).join(' ')}>
      <dd className="user-card-stat-value">{value}</dd>
      <dt className="user-card-stat-label">{label}</dt>
    </div>
  );
}

function hasRenderableChildren(children: ReactNode): boolean {
  if (children === null || children === undefined || children === false) return false;
  if (typeof children === 'string') return children.trim().length > 0;
  if (Array.isArray(children)) return children.some(hasRenderableChildren);
  return true;
}

function enhanceUserCardChildren(
  children: ReactNode,
  identityProps: Partial<SgDsLibraryUserCardIdentityProps>,
  tint: SgDsLibraryUserCardSectionTint | undefined,
): ReactNode {
  return Children.map(children, (child) => {
    if (!isValidElement(child)) return child;
    if (child.type === SgDsLibraryUserCardHead) {
      const childProps = child.props as SgDsLibraryUserCardHeadProps;
      return cloneElement(child as ReactElement<SgDsLibraryUserCardHeadProps>, {
        ...identityProps,
        ...childProps,
      }, childProps.children);
    }
    if (child.type === SgDsLibraryUserCardSection && tint !== undefined) {
      return cloneElement(child as ReactElement<SgDsLibraryUserCardSectionProps>, {
        ...child.props,
        tint: child.props.tint ?? tint,
      });
    }
    return child;
  });
}

function enhanceUserCardHeadChildren(
  children: ReactNode,
  identityProps: Partial<SgDsLibraryUserCardIdentityProps>,
): ReactNode {
  return Children.map(children, (child) => {
    if (!isValidElement(child)) return child;
    if (child.type === SgDsLibraryUserBlock) {
      const childProps = child.props as SgDsLibraryUserBlockProps;
      return cloneElement(child as ReactElement<SgDsLibraryUserBlockProps>, {
        ...omitUserCardHeadMoreAction({
          ...identityProps,
          ...childProps,
        }),
      }, childProps.children);
    }
    return child;
  });
}

function getDefinedProps<T extends Record<string, unknown>>(props: T): Partial<T> {
  return Object.fromEntries(Object.entries(props).filter(([, value]) => value !== undefined)) as Partial<T>;
}

function omitUserCardHeadMoreAction<T extends Partial<SgDsLibraryUserBlockProps>>(props: T): T {
  const action3Icon = typeof props.action3Icon === 'string' ? props.action3Icon.trim() : '';
  if (!['ellipsis', 'ellipsis-vertical', 'more-horizontal', 'more-vertical'].includes(action3Icon)) return props;
  const {
    action3AriaLabel: _action3AriaLabel,
    action3Icon: _action3Icon,
    action3Label: _action3Label,
    action3Variant: _action3Variant,
    ...rest
  } = props;
  return rest as T;
}

export default SgDsLibraryUserCard;
